wireapp/wire-ios-data-model

.travis.yml
README.md
Source/ManagedObjectContext/NSManagedObjectContext+zmessaging-Internal.h
Tests/Source/ManagedObjectContext/Migrations/DatabaseInitTests.m

Add .travis.yml and update README

---

Source/Model/User/ZMUser.m
Source/Public/ZMUser.h
Tests/Source/Model/User/ZMUserTests.m

- This is needed for tracking
- Includes tests

Checks if user is Otto the bot

---

Source/Model/User/ZMUser.m
Source/Public/ZMUser.h
Tests/Source/Model/User/ZMUserTests.m

- It came out that the user id for Otto would still have to change, so it was decided to go on with email detection

Better way of detecting bots (Anna and Otto)

---

.travis.yml

**What's in this PR?**
* Adjust notification settings and don't build pushes to branches other than `master` and `develop`

Adjust notification and build settings

---

Source/Model/User/ZMUser.m
Tests/Source/Model/User/ZMUserTests.m

Currently Anna is having an email anna@wire.com, and it is not matching to our regex

Detect anna@wire.com as bot

---

.travis.yml
Gemfile
Gemfile.lock

**What's in this PR?**
* Add build step to download Dangerfile
* print xcodebuild log if build fails

Add build step to download Dangerfile

---

Tests/Source/Model/Conversation/ZMConversationTests.m
Tests/Source/Model/CoreDataRelationshipsTests.m

This test was super flaky causing the build machines to fail the build

fix flaky test

---

Source/Model/Message/ConversationMessage+Deletion.swift
Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m

Unsent messages should not be editable.

do not allow editing of unsent text messages

---

Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.h
Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m

* Expose `useInMemoryStore` flag on `NSManagedObjectContext`

Expose `useInMemoryStore` flag on `NSManagedObjectContext`

---

Source/Model/Message/ConversationMessage+Reaction.swift
Tests/Source/Model/Messages/ZMMessageTests.m

* Only messages with a delivery state `.Sent` or `.Delivered` should be allowed to be liked.

Disable reactions for failed and pending messages

---

Source/Model/Message/ZMOTRMessage.m
Tests/Source/Model/Messages/ZMClientMessagesTests+Reaction.swift

This PR fix an issue that we would not handle remote unlike.

Handle receiving unlike

---

Source/Model/Conversation/ZMConversation+Internal.h
Source/Model/Message/ZMAssetClientMessage.h
Source/Model/User/ZMUser+Internal.h
Source/Model/ZMManagedObject+Internal.h

* The analyzer caught some nullability issues which have been fixed

Fix analyzer warnings

---

Source/Model/Conversation/ZMConversation+Ephemeral.swift
Tests/Source/Model/Conversation/ZMConversationTests+Ephemeral.swift

* Add  one day (86400 seconds) as message destruction timeout.

Add one day ephemeral timeout value

---

Source/Model/Message/ZMMessage.m
Tests/Source/Model/Messages/ZMClientMessageTests+Ephemeral.swift

**We now fetch all ephemeral messages on startup and check if their deletion date is in the past, if so we delete them.**
Until now we obfuscated all ephemeral messages sent by self if the application got killed and restarted, we now restart the timer if the delegation date is in the future and only obfuscate them when it is in the past (if the message is not be the self user we delete them when the deletion date passed and restart the timer if not).
Tests ~~in `wire-iso-message-strategy`~~, as well as in `wire-ios-sync-engine` still need to be updated to reflect these changes.

Do not obfuscate but instead restart timer on startup for message by self

---

Source/Model/Conversation/ZMConversation+Predicates.swift
Source/VoiceChannel/VoiceChannelV3.swift
Source/VoiceChannel/WireCallCenter.swift
Source/VoiceChannel/WireCallCenterMock.swift
ZMCDataModel.xcodeproj/project.pbxproj

We need a mock of the `WireCallCenter` since we can't make calls to AVS in our tests.

Add mock of WireCallCenter

---

Source/Model/Message/ZMMessage+Categorization.swift
Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift

We want to get messages by category only in a specific conversation

Filter message category query by conversation

---

Source/Model/Conversation/AssetCollection.swift
Source/Model/Conversation/AssetCollectionBatched.swift
Source/Model/Message/ZMMessage+Categorization.swift
Tests/Source/Model/Conversation/AssetCollectionBatchedTests.swift
Tests/Source/Model/Conversation/AssetColletionTests.swift

Any idea which hashValue to use? maybe just the including category?

Set excluding categoy more granularly

---

Source/Model/Message/ZMMessage+Categorization.swift
Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift

Ephemeral messages should not be display in collection categories

Do not categorise ephemeral messages

---

Source/Model/Conversation/AssetCollection.swift
Source/Model/Conversation/AssetCollectionBatched.swift

To avoid threading issues, we should avoid using the computed property syncMOC which access the uiMOC's userInfo and instead create a reference to the syncMOC which is then passed to the blocks.

Do not access the other moc’s userInfo

---

Source/Model/Message/ZMMessage+Categorization.swift
Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift

Merge https://github.com/wireapp/wire-ios-data-model/pull/115 first

Exclude incomplete images

---

Source/Model/Conversation/ZMConversation+SecurityLevel.swift

Some errors in the degradation logic:
- only append system message for secure if it was not already secure
- inverted timestamp of new system message about secure/insecure

Fix failing integration tests

---

Source/Model/UserClient/UserClient.swift
Tests/Source/Model/UserClient/UserClientTests.swift

* Fix a core data multithreading violation.

Fix threading violation in UserClient.resetSession

---

Source/Utilis/PersistedDataPatches.swift
Tests/Source/Utils/PersistedDataPatchesTests.swift

The comparison operator was returning a wrong value

Fix comparison operator for versions

---

Source/Model/Message/ZMMessage+Internal.h
Source/Model/Message/ZMMessage.m
Source/Model/Message/ZMOTRMessage.m
Source/Notifications/NotificationDispatcher.swift
Source/Notifications/SideEffectSources.swift
Tests/Source/Model/Observer/ConversationObserverTests.swift
Tests/Source/Model/Observer/MessageObserverTests.swift

Changes are better viewed by commit:
1) Clean-up - remove unnecessary mapping
2) Add `delivered` to `keyPathsAffectingValueForDeliveryState`

Fix message sending state update

---

Source/Model/Conversation/ZMConversation.m
Source/Model/Message/ZMMessage.m
Tests/Source/Model/Conversation/ZMConversationTests.m
Tests/Source/Model/Observer/NewUnreadMessageObserverTests.swift

Fix for https://wearezeta.atlassian.net/browse/ZIOS-8063
Also remove duplicated code I discovered while investigating this.

Don't resort hidden messages since it will make them visible again

---

Source/Model/Conversation/ZMConversationSecurityLevel.swift
Tests/Source/Utils/PersistedDataPatchesTests.swift
ZMCDataModel.xcodeproj/project.pbxproj

It seems the test introduced in #186 is quite flaky, trying to make it more stable

Fix for flaky test

---

Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.h
Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m

Expose the store URL to easily access the raw store (e.g. when running on simulator)

Expose store URL for debugging purposes

---

Source/Model/Conversation/ZMConversation+Internal.h
Source/Model/Conversation/ZMConversation.m
Source/Model/Message/GenericMessageScheduleNotification.swift
Source/Model/UserClient/UserClient.swift
Tests/Source/Model/UserClient/UserClientTests.swift
ZMCDataModel.xcodeproj/project.pbxproj

* Add session reset message to hidden messages instead of visible ones.

Hide session reset message

---

Source/Notifications/ObjectObserverTokens/UserClientChangeInfo.swift

Fixed swapped keys

---

Source/Notifications/NotificationDispatcher.swift
Source/Notifications/SnapshotCenter.swift
Tests/Source/Model/Observer/NotificationDispatcherTests.swift
Tests/Source/Model/Observer/SnapshotCenterTests.swift

The way we snapshot objects has changed to the following:
Previous behaviour:
Before merging changes from the syncContext context to the uiContext we were snapshotting objects that changed in the syncMOC and then compare the snapshots with after the merge. This was not 100% reliable as objects that were previously not realised in the uiMOC would need to fetched from the persistent store which would already have the committed but unsaved changes from the syncContext. Therefore some changes would go unnoticed.
Furthermore we observed a problem with inserted objects: If an object was inserted in the syncMOC, merged and then updated on the syncMOC and merged, it would not be contained in the refreshed objects in the contextDidChangeNotification. We would therefore not check it again for …

keep snapshots, calculate changes using updatedObjects in syncMOC

---

Tests/Source/Model/Conversation/ZMConversationTests.m

* Perform flaky tests on correct thread.

Perform test on correct thread

---

Source/Utilis/PersistedDataPatches.swift
Tests/Source/ManagedObjectContext/Migrations/OTRMigrationTests.m
Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift
Tests/Source/Model/User/ZMUserTests.m
Tests/Source/Model/UserClient/UserClientTests.swift
Tests/Source/Utils/PersistedDataPatchesTests.swift
ZMCDataModel.xcodeproj/xcshareddata/xcschemes/ZMCDataModel.xcscheme

Some tests were running code that is supposed to be executed on the sync thread on the main thread instead. 
Enabled Core Data concurrency debug flag for tests

Fix threading issues on all tests

---

Source/Model/User/ZMUser+Internal.h
Source/Model/User/ZMUser.m
Source/Model/User/ZMUser.swift

Added predicate to fetch number of connections to real users

---

Source/Model/Message/ConversationMessage+Reaction.swift

Return the client message when adding a reaction
I need to observe when a reaction is sent for the new background task API

return ClientMessage when adding a reaction

---

Source/ManagedObjectContext/ZMTestSession.m
Tests/Source/Model/Messages/BaseClientMessageTests.swift
Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift

Part of the ongoing process to optimise test suite memory usage (and possibly running time).

Tests: Clearing up some objects created during setUp

---

Source/Model/UserClient/UserClient.swift

To help investigate the issue of duplicate UserClient entries we add a precondition and logging.

Add precondition and logging when creating a UserClient

---

Source/Model/Analytics/Clusterizer+MessageCount.swift

* Add more buckets to message count clusterizer.

Add more buckets to message count clusterizer

---

Resources/zmessaging.xcdatamodeld/zmessaging2.30.0.xcdatamodel/contents
Source/Model/Conversation/Member.swift
Source/Model/Conversation/Permissions.swift
Source/Model/Conversation/Team.swift
Source/Model/Conversation/ZMConversation+Transport.m
Source/Model/User/ZMUser+Teams.swift
Source/Model/User/ZMUser.m
Source/Public/ZMUser+OneOnOne.h
Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
Tests/Source/Model/MemberTests.swift
Tests/Source/Model/PermissionsTests.swift
Tests/Source/Model/TeamTests.swift

* Parse transport response to create `Team`, `Permissions` and `Member`.
* Add `TeamType` protocol.

Parse transport response to create team, permissions and members

---

Source/ConversationList/ZMConversationList.m
Source/ConversationList/ZMConversationListDirectory.h
Source/ConversationList/ZMConversationListDirectory.m
Source/Model/Conversation/ZMConversation+Internal.h
Source/Model/Conversation/ZMConversation+Predicates.swift
Source/Model/Conversation/ZMConversation.m
Source/Model/UserClient/UserClient.swift
Source/Notifications/ConversationListObserverCenter.swift
Source/Notifications/ObjectObserverTokens/ConversationChangeInfo.swift
Source/Public/ZMConversationList.h
Tests/Source/Model/Conversation/ZMConversationTests+gapsAndWindows.m
Tests/Source/Model/Conversation/ZMConversationTests.m
Tests/Source/Model/ConversationList/ZMConversationListDirectoryTests+Teams.swift
Tests/Source/Model/ConversationList/ZMConversationListDirectoryTests.m
Tests/Source/Model/ConversationList/ZMConversationListTests+Teams.swift
Tests/Source/Model/ConversationList/ZMConversationListTests.m
Tests/Source/Model/Observer/ConversationListObserverTests.swift
WireDataModel.xcodeproj/project.pbxproj

* Inject optional team parameter into all conversation list methods.

Inject optional team parameter into all conversation list methods

---

Source/Model/Conversation/Permissions.swift
Tests/Source/Model/PermissionsTests.swift

* Add `setMemberPermission` Permissions value (see https://github.com/wireapp/architecture/pull/26).

Add `setMemberPermission` Permissions value

---

Source/Model/Conversation/ZMConversation.m
Tests/Source/Model/Conversation/ZMConversationTests.m

https://wearezeta.atlassian.net/browse/ZIOS-8663

Exclude team conversations in personal search

---

Source/Model/Conversation/Team.swift
Source/Model/User/ZMSearchUser.m
Source/Model/User/ZMUser.m
Source/Public/ZMBareUser.h
Tests/Source/Model/TeamTests.swift

Added a way to fetch all teams where the user is added as a guest to team conversations.

Finding out if user is a guest in any team

---

Source/Model/Conversation/ZMConversation+Teams.swift
Source/Model/Message/ZMMessage.m
Source/Public/ZMMessage.h
Tests/Source/Model/Conversation/ZMConversationTests+Teams.swift
WireDataModel.xcodeproj/project.pbxproj

A new system message type that does not change conversation `lastModifiedDate` on insertion

Added new system message type for team member leave

---

circle.yml

Added new style CircleCI config

---

Source/Model/User/ZMUser.swift
Tests/Source/Model/User/ZMUserTests.swift

Add test checking handle normalisation when searching

---

Source/Model/User/ZMSearchUser.m
Source/Model/User/ZMUser+Teams.swift
Source/Model/User/ZMUser.m
Source/Public/ZMBareUser.h

* Add method to check whether a user is guest in a conversation to `ZMBareUser`.

Add method to check whether a user is guest in a conversation to ZMBareUser

---

Source/Model/User/ZMUser.swift
Tests/Source/Model/User/ZMUserTests.swift

* Trimm whitespace in search predicate.

Trimm whitespace in search predicate

---

Source/Model/Conversation/ZMConversation+Internal.h
Source/Model/Conversation/ZMConversation.m

- Search should not filter by the team anymore.

Search predicate for conversations without team

---

Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.h
Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m

This code was previously in SE but I need it here to deal with in-memory db.

Add method for checking if a store exists at a given URL

---

Source/Model/Conversation/ZMConversation+SecurityLevel.swift
Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.m

- Check if the users are the members of the same team.

Correctly handle device verification for team users

---

Source/Model/Account.swift

* Mark account properties as public.

Mark account properties as public

---

Source/Model/Message/V2Asset.swift
Tests/Source/Model/Conversation/ZMConversationTests+Ephemeral.swift
Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift

The instance of `Unmanaged` must be released.

Fixed leaking CFString

---

Source/ManagedObjectContext/NSManagedObjectContext+TearDown.swift
Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.h
Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m
Source/Model/User/DisplayNameGenerator.swift
Source/Model/User/ZMUser.m
WireDataModel.xcodeproj/project.pbxproj

Copy of memory-related fixes from https://github.com/wireapp/wire-ios-data-model/pull/320

Cherry-picked memory fixes from fix/stack-initialization

---

Source/Model/User/ZMUser.swift
Tests/Source/Model/User/ZMUserTests.swift

This PR fixes https://wearezeta.atlassian.net/browse/ZIOS-8807

Sanitize assets keys for profile images

---

Source/ManagedObjectContext/Storage.swift

* Move store exists method to `StorageStack`.

Move store exists method to StorageStack

---

Source/ManagedObjectContext/NSPersistentStoreCoordinator+Wire.swift
Source/ManagedObjectContext/Storage.swift

Leaving out actual test code as it will conflict with planned changes

Changes after trying to fix tests

---

Source/ManagedObjectContext/ManagedObjectContextDirectory.swift
Source/ManagedObjectContext/PersistentStoreRelocator.swift
Source/ManagedObjectContext/StorageStack.swift
Tests/Source/ManagedObjectContext/StorageStackTests.swift

As we don't want to do (maybe costly) migration in share extension we need a way to check for it.

Added a method to check if store needs to be migrated

---

Source/ManagedObjectContext/PersistentStoreRelocator.swift

`PersistentStoreRelocator` always assumed there was an external record file 
(`.{store_name}_SUPPORT`), which Core Data uses to store larger binaries, e.g. images. 
This assumption is incorrect as Core Data will only store data blobs in an external record if they exceed a certain size and we reuse the `PersistentStoreRelocator` to relocate the `ZMEventModel` database used in `wire-ios-sync-engine`, which will never need an external store record file.

Don't try to move nonexistent external support files

---

Source/ManagedObjectContext/PersistentStorageInitialization.swift
Source/Utilis/FileManager+FileProtectionLock.swift
WireDataModel.xcodeproj/project.pbxproj

Refactor locked file system access functionality into an extension of `FileManager`

File system lock

---

Source/ManagedObjectContext/NSManagedObjectContext+NotificationContext.swift
Source/Model/Account.swift
Source/Model/Conversation/ZMConversation+Notifications.swift
Source/Model/Conversation/ZMConversation+Timestamps.m
Source/Model/Conversation/ZMConversation.m
Source/Model/Message/GenericMessageScheduleNotification.swift
Source/Model/Message/V2Asset.swift
Source/Model/Message/V3Asset.swift
Source/Model/Message/ZMAssetClientMessage+Download.swift
Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
Source/Model/Message/ZMClientMessage+LinkPreview.swift
Source/Model/User/ZMUser.swift
Source/Notifications/ConversationListObserverCenter.swift
Source/Notifications/MessageWindowObserverCenter.swift
Source/Notifications/NotificationDispatcher.swift
Source/Notifications/NotificationInContext.swift
Source/Notifications/SearchUserObserverCenter.swift
Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.m
Tests/Source/Model/Conversation/ZMConversationTests+Timestamp.m
Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
Tests/Source/Model/Messages/ZMClientMessageTests+TextMessage.swift
Tests/Source/Model/Observer/SearchUserObserverCenterTests.swift
Tests/Source/Model/ZMConnectionTests.m
WireDataModel.xcodeproj/project.pbxproj

Also introduce NotificationContext protocol for improved type safety when registering observers

use Persistence Store as notification context

---

Source/Model/Account.swift
Source/Model/AccountManager.swift
Source/Model/AccountStore.swift
Tests/Source/Model/AccountManagerTests.swift
Tests/Source/Model/AccountTests.swift

- Add unread count to the persisted JSON of the account
- Also renamed the method `AccountManager.add` to `AccountManager.addOrUpdate`

Persist unread count for Account

---

Source/Model/Conversation/ZMConversation.m

Reverts wireapp/wire-ios-data-model#374

Revert "More logging for message getting stuck"

---

Source/Model/Message/ConversationMessage.swift
Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m

This useful to avoid doing stuff on deleted message in the UI

 Consider a message to be deleted if it is a zombie

---

Source/Utilis/Protos/ZMGenericMessage+Utils.m
Tests/Source/Model/Messages/ZMGenericMessageTests.swift
WireDataModel.xcodeproj/project.pbxproj

- External message is not considered as `known`

Potential fix for messages getting stuck

---

Source/Model/User/ZMUser+Filename.swift
Tests/Source/Model/User/ZMUserTests.swift

Clean up NSString logic and clean up unit tests

replace the type NSString to String

---

Source/Model/Message/ZMMessage.m
Tests/Source/Model/Messages/ZMClientMessageTests+Ephemeral.swift

This PR helps to address an issue where an ephemeral message sent via the Share Extension does not obfuscate in the conversation.
When we send an ephemeral image in the client, an obfuscation timer is created and retained for that message. However, when an ephemeral image is sent via the Share Extension, the necessary timer was not being created.
When the app launches and when `ZMClientMessageTranscoder` is initialised, it calls the `ZMMessage.deleteOldEphemeralMessages:` which will fetch message old ephemerals and either restart their destruction timer if the destruction date has not been reached, otherwise it deletes the message or obfuscates it. What is missing in this method is to restart the obfuscation timer if the destruction date is not reached and the sender of the message is the …

add method to restart obfuscation timer

---

Source/Model/User/ZMSearchUser+ServiceUser.swift
Source/Model/User/ZMSearchUser.m
Source/Model/User/ZMUser.m
Tests/Source/Model/User/ZMSearchUserPayloadParsingTests.swift

It should not be possible to connect to the service user.

Forbid connecting to the service user

---

Source/ManagedObjectContext/NSPersistentStore+Metadata.swift
Source/Model/Message/ZMAssetClientMessage+Deletion.swift
Source/Utilis/Protos/ZMGenericMessage+Helper.swift
Tests/Source/Model/Messages/ZMClientMessageTests+Deletion.swift

* Fire notification to mark assets to be remotely deleted.

Fire notification to mark assets to be remotely deleted

---

Source/ManagedObjectContext/StorageStack+Backup.swift
Tests/Source/ManagedObjectContext/StorageStackBackupTests.swift

* Store metadata file and adjust backup folder structure.

Store metadata file and adjust backup folder structure

---

Source/ManagedObjectContext/StorageStack+Backup.swift
Tests/Source/ManagedObjectContext/StorageStackBackupTests.swift

* Include metadata object in backup completion handler.

Include metadata object in backup completion handler

---

Source/ManagedObjectContext/StorageStack+Backup.swift
Tests/Source/ManagedObjectContext/StorageStackBackupTests.swift

* Forward internally thrown error.

Forward internally thrown error

---

Source/ManagedObjectContext/BackupMetadata.swift

* Store metadata creation date in ISO8601 format.

Store metadata creation date in ISO8601 format

---

Source/Model/Message/ZMClientMessage+Encryption.swift
Tests/Source/Model/Messages/ZMAssetClientMessageTest+Encryption.swift
Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift

We need to sync the ephemeral messages to the sender devices.

Sync ephemeral to all devices

---

Source/Model/Conversation/ZMConversation+Ephemeral.swift

Restored `isWeeks` variable from UI project.

Restored isWeeks variable for ephemeral messages

---

Source/Model/Conversation/ZMConversation+Ephemeral.swift

Added the `timestamp` parameter to `appendSystemMessage`.

Added timestamp to the timer system message

---

Source/Model/Message/ZMAssetClientMessage+Ephemeral.swift
Source/Model/Message/ZMAssetClientMessage.swift
Tests/Source/Model/Messages/ZMClientMessageTests+Ephemeral.swift

We start expiring the text messages from the self device, but ignore images and assets.
Expire messages and assets, too.

Expire self assets from other devices

---

Source/Model/Message/Ephemeral/ZMMessageDestructionTimer.swift
Source/Model/Message/ZMMessage.m

* Add logs for ephemeral deletion and obfuscation timer.

Add logs for ephemeral deletion and obfuscation timer

---

Source/Model/Message/Message.swift
Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
Source/Utilis/MimeType.swift
Tests/Source/Model/Conversation/ZMConversationTests+Messages.swift
Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift

Identify PassKit pass file type.

Feature: PassKit file support

---

Source/Model/Conversation/ZMConversation+UnreadCount.h
Source/Model/Conversation/ZMConversation+UnreadCount.m
Tests/Source/Model/Conversation/ZMConversationTests.m

* Exclude silenced conversations from back arrow dot calculation.

Exclude silenced conversations from back arrow dot calculation

---

Source/Model/Message/Mention.swift

* Add convenience accessors checking if self is mentioned in a message.

Add convenience accessors checking if self is mentioned in a message

---

Source/Model/Conversation/ZMConversation+Mute.swift
Tests/Source/Model/Conversation/ZMConversationTests+Mute.swift

Sometimes it's necessary to check if the message has to generate the notification.

Added logic to check if message is silenced

---

Source/Model/Conversation/ZMConversation+Timestamps.swift
Tests/Source/Model/Conversation/ZMConversationTests+Transport.m

Updated according to https://github.com/wearezeta/documentation/compare/7dee94361d39...6b1389b7bb11

Asserted the backwards compatibility behavior for mentions notifications

---

README.md

Updated badge to point to Azure Pipelines.

Added Azure build badge

---

Source/Model/Message/ConversationMessage.swift

objectIdentifer → objectIdentifier

Fix "objectIdentifier" typo

---

Source/Model/Message/ZMMessage.m
Source/Public/ZMMessage.h

Add read receipt system message type. Methods for actually inserting the system message of this type will come in a separate PR.

Add read receipt system message type

---

Cartfile
Cartfile.resolved

Azure test PR

---

Cartfile

Bump components  due major transport release https://github.com/wireapp/wire-ios-transport/pull/122

Bump components

---

Source/Model/Conversation/Member.swift
Source/Model/Conversation/Permissions.swift
Tests/Source/Model/PermissionsTests.swift

Create new permissions for partner role.

Partner permissions

---

Source/Model/Conversation/Permissions.swift

Comment the struct Permissions and release data model with a major version change.

Fix: Comment the struct Permissions

---

Source/Utilis/InvalidConversationRemoval.swift
Source/Utilis/PersistedDataPatches+Directory.swift
Tests/Source/Utils/InvalidConversationRemovalTests.swift
WireDataModel.xcodeproj/project.pbxproj

Restore https://github.com/wireapp/wire-ios-data-model/pull/660

Revert "Revert "Data patch for deleting invalid conversations (#660)""

---

Source/Model/Conversation/ZMConversation.m

`ClientMessageTranscoderTests.testThatItAddsMissingRecipientInMessageRelationship` started to fail. 
`missingRecipients` is a transient relationship so faulting it too early will result in an extra roundtrip to the backend. We currently fault all messages after every save.
Don't fault messages which have missing recipients

Don't fault messages with missing clients

---

Source/Model/Message/ZMOTRMessage.m

Log the protobuf messages (sanitized) we are processing.

Log which protobuf messages are being processed

---

Source/Model/User/UserType.swift
Source/Model/User/ZMSearchUser.swift

Add emailaddress property for the UI (`ProfileViewController`).

Feature: add emailaddress property to UserType

---

Cartfile
Cartfile.resolved
WireDataModel.xcodeproj/project.pbxproj

remove libPhoneNumber

---

Source/Model/User/UserType.swift
Source/Model/User/ZMSearchUser.swift
Source/Model/User/ZMUser.swift

Expose clients on UserType for easier mocking in tests.

Expose clients on UserType

---

Source/Model/Conversation/ZMConversation+SecurityLevel.swift
Tests/Source/Model/Conversation/ZMConversationTests+Legalhold.swift

It was decided that we'd insert the legal hold system message only once when it becomes enabled or disabled, and that it wouldn't contain information about the user.
- Remove the checks for which users were added and removed
- Add user-agnostic system message for enabling legal hold

Insert legal hold system message only once

---

Source/Model/UserClient/UserClientType.swift

Expose `isSelfClient()` on the `UserClientType`

Expose isSelfClient on the UserClientType

---

Source/Model/UserClient/UserClient.swift

Legal hold is active would re-appear on every app launch
We re-fetch the self clients on every launch and we would reset the `needsToAcknowledgeLegalHoldStatus` to `true` even if we already knew the client since before.
Only reset `needsToAcknowledgeLegalHoldStatus` to `true`if it's a new client.

Legal hold was flipped even if the legal hold client was already known

---

Source/Model/Conversation/Team+Status.swift
Tests/Source/Model/TeamTests.swift
WireDataModel.xcodeproj/project.pbxproj

- Created an extension of `Team` to provide a `shouldCommunicateStatus` property.
- Updated tests accordingly

[Feature] Status Propagation

---

Source/Model/ConversationRole/Action.swift
Source/Model/ConversationRole/Role.swift
Tests/Source/Model/ConversationRole/ActionTests.swift
Tests/Source/Model/ConversationRole/RoleTests.swift
Tests/Source/Model/UserClient/UserClientTests.swift
WireDataModel.xcodeproj/project.pbxproj

Decoding a payload dictionary to `Role` with `Action`s

Feature: Role decoding

---

Source/Model/Connection/ZMConnection+Role.swift

Updated some comment (will use this to trigger a release)

Fix comments on connection add

---

Source/Model/ConversationRole/Role.swift

This is just to trigger a new release

Update a comment

---

Source/Model/Connection/ZMConnection+Role.swift

This commit is really a test for the release process

Test release scripts

---

Patches/DuplicatedEntityRemoval.swift
Source/Model/User/ZMUser.swift
Source/Model/UserClient/UserClient.swift
Source/Notifications/SideEffectSources.swift
Tests/Source/Utils/DuplicatedEntityRemovalTests.swift

Remove `lastServerSyncedActiveConversations`

Remove lastServerSynced from tests

---

Source/Model/ConversationRole/Action.swift

add `isTrackingLocalModifications` property to `Action`

add Action isTrackingLocalModifications property

---

Source/Model/Conversation/ZMConversation+Patches.swift

Expose `defaultAdminRoleName` to UI project

expose defaultAdminRoleName

---

Source/Model/User/ZMUser+Permissions.swift
Tests/Source/Model/User/ZMUserTests+Permissions.swift

Change the access control permission.

Fix: Update the access control permission for a non team conversation.

---

Source/Model/Conversation/ZMConversation+Predicates.swift
Tests/Source/Model/Conversation/ConversationTests.swift
Tests/Source/Model/Conversation/ZMConversationTests.swift
WireDataModel.xcodeproj/project.pbxproj

Searching has no return after search with a query ended with space
The searching does not finish when a empty query
Trim the query string before break down it into array.

fixed searching issue

---

WireDataModel.xcodeproj/project.pbxproj

Explicitly define the project indentation to 4 spaces so my local (2 space) setting doesn't conflict with the project 😄

[Chore] Set project level indentation

---

Source/Model/Message/ZMClientMessage+TextMessageData.swift
Source/Utilis/Protos/GenericMessage+Helper.swift

Refactor the editing message methods to use the Swift Protobuf API.

[Refactor] Edit messages using Swift Protobuf API

---

Source/Model/Conversation/ZMConversation+Confirmations.swift
Source/Model/Conversation/ZMConversation+Message.swift
Source/Utilis/Protos/GenericMessage+Helper.swift

Refactor the sending confirmation message methods to use the Swift Protobuf API.

[Refactor] Send confirmation messages using Swift Protobuf API

---

Source/Model/Message/Message.swift

- Add `isComposite` to `ConversationCompositeMessage`

[Feature] Add `isComposite` to ConversationCompositeMessage

---

Source/Notifications/DependencyKeyStore.swift

Add `ButtonState.isExpired` to observable keys

[Feature] Observe changes to `ButtonState.isExpired`

---

Source/Model/Message/File/SignatureStatus.swift
Source/Model/Message/V2Asset.swift
Source/Model/Message/V3Asset.swift
Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift

- Added PendingURL state to the Status object
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-12764
sync-engine: https://github.com/wireapp/wire-ios-sync-engine/pull/1195

[Feature]: Digital Signature Request

---

Source/Model/Message/File/SignatureStatus.swift
Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift

JIRA:  https://wearezeta.atlassian.net/browse/ZIOS-12764
sync-engine:  https://github.com/wireapp/wire-ios-sync-engine/pull/1199
ui: https://github.com/wireapp/wire-ios/pull/4236

[Feature] Propagate the digital signature infos to the UI

---

Source/ConversationList/ConversationDirectory.swift
Source/Model/Message/File/SignatureStatus.swift
Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
Source/Model/Message/ZMAssetClientMessage.swift

JIRA: https://wearezeta.atlassian.net/browse/ZIOS-12765
UI: https://github.com/wireapp/wire-ios/pull/4246
sync-engine: https://github.com/wireapp/wire-ios-sync-engine/pull/1202

[Feature]: Digital Signature: Retrieve Signature

---

Tests/Source/Model/DigitalSignature/SignatureStatusTests.swift
WireDataModel.xcodeproj/project.pbxproj

This PR provides tests that cover the SignatureStatus.

[Feature] Tests for the SignatureStatus

---

Source/Model/Message/File/SignatureStatus.swift
Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift

sync-engine: https://github.com/wireapp/wire-ios-sync-engine/pull/1212

[Feature] - Digital Signature Clean Up

---

Source/Model/Message/ZMOTRMessage.m

- Force read confirmation for composite messages

[Hotfix] Read receipts for composite

---

Tests/Source/Model/DigitalSignature/SignatureStatusTests.swift

Test that we use correct assetID and fileName for sending it as request parameters.

[Feature] Test for the SignatureStatus

---

Source/Utilis/Protos/GenericMessage+Content.swift
Source/Utilis/Protos/GenericMessage+Flags.swift
Source/Utilis/Protos/GenericMessage+Helper.swift
WireDataModel.xcodeproj/project.pbxproj

- Helpers for generic message content
- Clean up

[Refactor] Protobuf: generic message content helpers

---

Source/Model/Message/RasterImages+Protobuf.swift
Source/Utilis/Protos/GenericMessage+Assets.swift
Source/Utilis/Protos/GenericMessage+Content.swift
Source/Utilis/Protos/GenericMessage+Helper.swift
Tests/Source/Model/Messages/ZMAssetClientMessageTests+Ephemeral.swift
Tests/Source/Model/Utils/ProtobufUtilitiesTests.swift
Tests/Source/Model/Utils/ProtosTests.swift

Reduce duplicate code for hasXXX methods.

[Refactor] hasXXX methods for GenericMessage

---

Source/ManagedObjectContext/NSManagedObjectContext+EncryptionAtRest.swift
WireDataModel.xcodeproj/project.pbxproj

Add add persistent metadata key for storing if messages should encrypted at rest.

[Feature] Add persisted key for encrypting messages at rest

---

Source/Model/Conversation/ZMConversation+Mute.swift
Source/Model/Message/ConversationMessage.swift
Source/Model/Message/ZMAssetClientMessage.swift
Source/Model/Message/ZMClientMessage.swift
Source/Utilis/Protos/GenericMessage+Helper.swift
Source/Utilis/ZMUpdateEvent.swift

This PR a part of the EAR feature.
Add` isMessageSilenced()` function to the `ZMConversation`

[Feature] Add isMessageSilenced() to the ZMConversation

---

Source/Model/User/ZMUser.m
Tests/Source/Model/User/ZMUserTests+Swift.swift
Tests/Source/Model/User/ZMUserTests.m

we are converting the UUID into a transportString

[Feature]: Analytics ID Improvements

---

Source/Notifications/ChangeInfoConsumer.swift
Source/Notifications/Changes.swift
Source/Notifications/ClassIdentifier.swift
Source/Notifications/ManagedObjectObserverToken.swift
Source/Notifications/Notification.Name+ManagedObjectObservation.swift
Source/Notifications/NotificationDispatcher.ExtractedObjects.swift
Source/Notifications/NotificationDispatcher.UnreadMessages.swift
Source/Notifications/NotificationDispatcher.swift
Source/Notifications/ObjectObserverTokens/ObjectChangeInfo.swift
Source/Notifications/ZMManagedObject+ClassIdentifier.swift
WireDataModel.xcodeproj/project.pbxproj

This PR contains solely cleanup and organization (no change in behavior).

[Refactor] Change tracking cleanup

---

Tests/Source/ManagedObjectContext/CoreDataStackTests+EncryptionAtRest.swift
Tests/Source/ManagedObjectContext/NSManagedObjectContextTests+EncryptionAtRest.swift
Tests/Source/Model/Conversation/ZMConversationTests+DraftMessage.swift
Tests/Source/Model/Messages/ZMGenericMessageDataTests.swift
Tests/Source/Utils/EncryptionKeysTests.swift

BSI needs a documentation that contains security-relevant test cases which are mapped to security functions (SF) and interfaces (TSFI). Additionally we need to deliver a document for them which contains all test cases containing purpose, procedure, expected result and actual result.
This PR annotates unit/integration test cases with a comment in front of each test case function. This helps to automatically gather these test cases and create a document out of it.
There are additional pull requests in wire-ios and wire-ios-sync-engine like this.
See https://github.com/wireapp/bsi-mapping/ for the scripts that do the parsing and creation of the documents.

[Chore] Annotate data model tests with SF and TSFI tags

---

Source/Model/Confirmation/ZMMessageConfirmation.swift
Source/Model/Conversation/ZMConversation+Transport.swift
Source/Model/Message/ZMMessage.m
Source/Model/Message/ZMOTRMessage+VerifySender.swift
Source/Utilis/Dictionary+ObjectForKey.swift
Source/Utilis/ZMUpdateEvent+WireDataModel.h
Source/Utilis/ZMUpdateEvent+WireDataModel.m

Parse qualified IDs when available

[Feature] Parse qualified IDs when available

---

Source/Model/FeatureConfig/Feature.swift
Source/Model/FeatureConfig/FeatureService.swift
Source/Model/FeatureConfig/SelfDeletingMessages/Feature.SelfDeletingMessages.swift
WireDataModel.xcodeproj/project.pbxproj

**Jira:** https://wearezeta.atlassian.net/browse/SQSERVICES-541
In this PR we define the new `SelfDeletingMessage` configuration object.

Self-deleting message config (part 0)

---

Cartfile
Cartfile.resolved

Rebuild PINCache with Xcode 13.1

bump PINCache for Xcode 13

---

Patches/InvalidConversationRemoval.swift
Source/ManagedObjectContext/CoreDataStack.swift
Source/Model/FeatureConfig/Feature.swift
Source/Model/FeatureConfig/FeatureService.swift

To be able to reproduce the crash using TestFlight build, there are more public logs that can help us.
This should be reverted after debugging.

[Chore] Add public logs

---

Source/Model/FeatureConfig/FeatureService.swift

Another attempt to figure out the reason of the crash is to remove forced unwrapping from the` fetchFeatureName()` methods. This will probably bring the crash to another part of the code and may help us.

[Fix] Remove forced unwrapping

---

Source/Model/FeatureConfig/ClassifiedDomains/Feature+ClassifiedDomains.swift
Source/Model/FeatureConfig/Feature.swift
Source/Model/FeatureConfig/FeatureService.swift
WireDataModel.xcodeproj/project.pbxproj
azure-pipelines.yml

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-96" title="FS-96" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-96</a>  [iOS] Fetch classified domains
</td></table>
<br />
----
----
Add support for classified domains, which are communicated to the app from the backend as a team feature config.
----
----
----

feat: add support for classified domains FS-96

---

Source/Model/FeatureConfig/AppLock/Feature.AppLock.swift
Source/Model/FeatureConfig/ClassifiedDomains/Feature+ClassifiedDomains.swift
Source/Model/FeatureConfig/Feature.swift
Source/Model/FeatureConfig/FeatureService.swift
Source/Model/FeatureConfig/MLS/Feature.MLS.swift
Source/Model/FeatureConfig/SelfDeletingMessages/Feature.SelfDeletingMessages.swift
Source/Model/User/UserType.swift
Source/Model/User/ZMSearchUser.swift
Source/Model/User/ZMUser.swift
Tests/Source/Model/FeatureConfiguration/FeatureServiceTests.swift
WireDataModel.xcodeproj/project.pbxproj

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-536" title="FS-536" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-536</a>  [iOS] Detect and use MLS feature config
</td></table>
<br />
----
----
- Add feature config for MLS
- Added feature service tests for MLS
- Also added missing tests for other features
----
- x ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
----

feat(mls): feature config FS-536

---

MLS/Actions/ClaimMLSKeyPackageAction.swift
MLS/Actions/CountSelfMLSKeyPackagesAction.swift
MLS/Actions/SendMLSMessageAction.swift
MLS/Actions/SendMLSWelcomeAction.swift
MLS/Actions/UploadSelfMLSKeyPackagesAction.swift
WireDataModel.xcodeproj/project.pbxproj

----
----
In this PR we are moving MLS actions classes from  RequestStrategy  to DataModel framework.

chore(mls): moving mls actions to data model

---

MLS/CoreCryptoTypes.swift

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-822" title="FS-822" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-822</a>  [iOS] Update CoreCrypto
</td></table>
<br />
----
----
- Update the Core Crypto bindings, necessary to update CoreCrypto in the UI project.
----
----
----

chore: update core crypto protocol FS-822

---

MLS/CoreCryptoTypes.swift
MLS/MLSController.swift
MLS/MLSQualifiedClientID.swift
WireDataModel.xcodeproj/project.pbxproj

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-538" title="FS-538" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-538</a>  [iOS] Upload key packages
</td></table>
<br />
----
----
- Added methods to extensions of MLSCController to count, generate and upload new key packages if needed
Needs releases with:
----
----
----

feat(mls): upload key packages FS-538

---

MLS/MLSClientID.swift
MLS/MLSController.swift
MLS/MLSGroupID.swift
Source/Model/Conversation/ZMConversation+Participants.swift

----
----
Improve logging by:
- adding more logs
- adding more context to existing logs
- using only the mls log tag
----
----
----

chore(mls): improve logging

---

MLS/MLSController.swift
Resources/zmessaging.xcdatamodeld/zmessaging2.105.0.xcdatamodel/contents
Source/Model/Conversation/ZMConversation+MLS.swift
Source/Model/Conversation/ZMConversation.m
Tests/MLS/MLSControllerTests.swift
Tests/MLS/MockCoreCrypto.swift
Tests/MLS/MockMLSController.swift
Tests/Source/Helper/ZMBaseTest+Async.swift
Tests/Source/Model/Conversation/ZMConversationTests+MLS.swift
WireDataModel.xcodeproj/project.pbxproj

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-703" title="FS-703" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-703</a>  [iOS] Automatically Commit PendingProposals
</td></table>
<br />
----
----
Commit incoming pending proposals as described here: https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/601522340/Use+Case+Committing+Pending+Valid+Proposals+MLS
_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._
_Attachments like images, videos, etc. (drag and drop in the text box)_
----
----
---- …

feat: commit pending proposals FS-703

---

MLS/CoreCryptoCallbacks.swift
MLS/MLSClientID.swift
MLS/MLSController.swift
Tests/MLS/CoreCryptoCallbacksTests.swift
WireDataModel.xcodeproj/project.pbxproj

----
----
Implement the core crypto callbacks.
----
----
----

feat: implement core crypto callbacks

---

MLS/MLSController.swift
Tests/MLS/MLSControllerTests.swift

----
----
If there is a pending proposal, and you try to make another commit (such as a member add, member remove, or key update), then Core Crypto will fail stating there is an uncommitted proposal.
Commit any pending proposals (ignoring a commit delay) for the group before proceeding with the next commit.
- unit test to commit pending proposal before adding members
- unit test to commit pending proposal before removing members
- unit test to commit pending proposal before updating key material
----
----
----

feat(mls): commit pending proposals before other commits

---

MLS/CoreCryptoCallbacks.swift
MLS/CoreCryptoTypes.swift
Tests/MLS/CoreCryptoCallbacksTests.swift
Tests/MLS/MLSActionExecutorTests.swift
Tests/MLS/MockCoreCrypto.swift

----
----
This PR updates the core crypto bindings for core crypto v0.6.0-pre.4
----
----
----

chore(mls): update core crypto

---

MLS/CoreCryptoConfiguration.swift
MLS/CoreCryptoKeyProvider.swift
Source/ManagedObjectContext/NSManagedObjectContext+MLSController.swift
Tests/MLS/CoreCryptoFactoryTests.swift
WireDataModel.xcodeproj/project.pbxproj

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1072" title="FS-1072" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-1072</a>  [iOS] Share extension not working on MLS builds
</td></table>
<br />
----
----
This PR moves the core crypto setup code from sync engine to data model, so that the share engine can easily setup core crypto.
- Created `CoreCryptoFactory` as an interface for both sync and share engines to generate the core crypto configuration 
- Added a `setMLSController` method to `NSManagedObjectContext`
- Added tests for `CoreCryptoFactory`
----
----
----
1. …

feat(mls): add support for share extension FS-1072

---

MLS/Actions/FetchPublicGroupStateAction.swift
MLS/MLSController.swift
Tests/MLS/MockMLSActionsProvider.swift
WireDataModel.xcodeproj/project.pbxproj

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-958" title="FS-958" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-958</a>  [iOS] 5.1.1.1 Fetch public group state
</td></table>
<br />
----
----
- Client who wants to join an MLS group via an external commit we need to fetch the group state from the backend.
- Created a new `FetchPublicGroupStateAction`
- Added the `FetchPublicGroupStateAction` to the actions provider protocol for the `MLSController`
Needs releases with:
- https://github.com/wireapp/wire-ios-request-strategy/pull/576
----
----
----
1. …

feat(mls): added FetchGroupStateActionHandler FS-958
