wireapp/wire-ios-data-model

- Source/Model/UserClient/UserClient+Protobuf.swift
This PR fixes a memory leak occurring when generating the hexadecimal of the UserClient identifier.
> Fix leak where we would not dealloc memory for a UInt64

- Source/Model/Message/ZMAssetClientMessage.m
- Source/Model/Message/ZMClientMessage.m
- Source/Model/Message/ZMImageMessage.m
- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMClientMessageTests+Deletion.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
- Tests/ZMDataModelTestTarget/AppDelegate.m
___
When deleting a message for everyone we want to make sure to clear all possible content of the deleted message. 
___
* When calling `-removeMessage` on a `ZMMessage` we now also set the `sender` and `senderClientID ` to `nil`, reseting the timestamp would not make sense as a system message will be shown using the same timestamp on receiving devices.
* The same method called on a `ZMAssetClientMessage` did already remove the cashed file data, but did not remove a potentially present thumbnail image. The generic message data set was not removed which means that the asset could have been re-downloaded using the `assetId` and the encryption keys. Now the data set, `assetID`, as well as the generic message cache is cleared.
* When calling the same method on old, pre-e2ee messages (only …
> Clear all message data on deletion

- Source/Model/Message/ConversationMessage+Deletion.swift
- Source/Model/Message/ZMAssetClientMessage.m
- Source/Model/Message/ZMClientMessage.m
- Source/Model/Message/ZMImageMessage.m
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
- Tests/Source/Model/Messages/ZMMessageTests.m
___
* We previously removed the sender remote identifier from a message when calling `[ZMMessage removeMessage]` on it, but in case of an edit we still need this information to update the new message with the correct sender identifier. This lead to an edited message not displaying the sender name / image.
* The `[ZMMessage removeMessage]` has been renamed to `[ZMMessage removeMessageClearingSender:]` and the parameter indicates weather the sender information should be removed.
* This also fixes some flaky test for asset client messages.
> Do not clear the sender when removing a message caused by an edit

- Source/ManagedObjectContext/ZMTestSession.m
- Source/Model/Message/AssetCache.swift
- Source/Utilis/UserImageLocalCache.swift
Extracted from https://github.com/wireapp/wire-ios-data-model/pull/29
This PR fixes some random crashes in the tests when the caches has been torn down after a test but are still being accessed by an still running dispatch group.
> Fix crash in tests when caches has been torn down

- Source/Model/Message/MessageUpdateResult.swift
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
- Source/Model/Message/ZMOTRMessage.h
- Source/Model/Message/ZMOTRMessage.m
- Source/Utilis/ZMUpdateEvent+ZMCDataModel.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Deletion.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
- Tests/Source/Model/Messages/ZMClientMessageTests.m
- Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
- Tests/Source/Model/Messages/ZMMessageTests.m
- ZMCDataModel.xcodeproj/project.pbxproj
**In this PR**
Previously we were inserting the confirmation message directly when inserting a message from an updateEvent. From the outside it's intransparent if a confirmation message was inserted or not. In order to send confirmation messages in the background, `wire-ios-sync-engine` needs to know this. 
Therefore we are now returning the original message and the information if a confirmation message should be sent and insert the confirmation message afterwards (in the clientTranscoder of `wire-ios-sync-engine`).
Note: Without the changes on sync-engine this change will break confirmation messages
Merge https://github.com/wireapp/wire-ios-sync-engine/pull/39 after
> return object containing message and info if it needs confirmation

- Source/Notifications/ObjectObserverTokens/MessageObserverToken.swift
- Tests/Source/Model/Observer/ObjectObserverToken/MessageObserverTokenTests.swift
**TL;DR: This PR changes the visibility of the `reactionChangeInfo` which should not be exposed to the UI.**
The reaction observation works as follows: Every message observes its reaction relation and adds a reaction observer as soon as a reaction is added to it. If the reactions relation changes the observer fires a change with the flag `reactionsChanged`. The same change is fired when a reaction observed by the message observer changes  (e.g. more users add the same reaction), in this case the observer uses the `reactionChangeInfo` of the reaction observer to determine if a reaction changed (as the reactions relation does not have to change in this case). This change info was publicly exposed, but it should not be used to determine if a change happened as it will be `nil` in case a new …
> Mark the `reactionChangeInfo` on `MessageObserverToken` as private

- Source/Model/Message/ConversationMessage+Reaction.swift
- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
* If a message is edited the reactions should be reset.
* We now clear the reactions when calling `removeMessageClearingSender:` to ensure this data is removed in all cases when a message is removed (which is also the case for edits as a new message is inserted)
> Clear all reactions when a message is removed / edited

- Resources/zmessaging.xcdatamodeld/.xccurrentversion
- Resources/zmessaging.xcdatamodeld/zmessaging2.11.xcdatamodel/contents
- Source/Model/User/ZMUser.m
- ZMCDataModel.xcodeproj/project.pbxproj
This PR add the reverse relationship between the `User` and `Reaction` model because the relationship is a many-to-many relationship, and you need to explicitly declare that relationship.
This is more subtle in that this causes issue when the CoreData stack is persisted in the SQLite backing (SQLite needs the intermediate table for that kind of relationship which CoreData automatically create when reverse relationship is created), but the issue does not appear when in memory.
For more information: [Core Data Programming Guide](https://developer.apple.com/library/watchos/documentation/Cocoa/Conceptual/CoreData/HowManagedObjectsarerelated.html#//apple_ref/doc/uid/TP40001075-CH17-SW8)
> Add reverse relationship for between User and Reaction

- Source/Model/Conversation/ZMConversation+Transport.m
- Source/Model/Message/ZMOTRMessage.m
- Tests/Source/Model/Messages/BaseClientMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Deletion.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Unarchiving.swift
- Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
- ZMCDataModel.xcodeproj/project.pbxproj
**In this PR**
We were previously handling unarchiving in the transcoder by inspecting the event type and timestamps. For messages we should not do this, because some message events don't create a message, but only invisible side effects.
> handle unarchiving when creating messages

- Resources/zmessaging.xcdatamodeld/.xccurrentversion
- Resources/zmessaging.xcdatamodeld/zmessaging2.15.0.xcdatamodel/contents
- Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
- ZMCDataModel.xcodeproj/project.pbxproj
When deleting a message, if that message had a receipt confirmation, the model would not validate as the `message` field is mandatory in the `MessageConfirmation` entity and the save would fail. 
- The relationship is changed to `cascade` so deleting the message also deleted the confirmation.
- Create a new model version, changed the versioning system to reflect the app version
> Fix messages not being deleted when they have a confirmation

- Source/Notifications/ObjectObserverTokens/ManagedObjectContextObserver.swift
- Tests/Source/Model/Observer/ObjectObserverToken/MessageObserverTokenTests.swift
The `Reaction` observer type had an index superior than the `MessageWindowObserver`, which lead the former being processed after the later. This means that the UI would be notifies of a change from the second event onward when receiving event. By reordering the reaction observer type index, we now are correctly notified when something is changing.
> Fix observing

- Source/Model/Message/ConversationMessage+Reaction.swift
- Source/Model/Message/ZMOTRMessage.m
- Source/Model/Reaction/Reaction.swift
- Tests/Source/Model/Messages/ZMClientMessagesTests+Reaction.swift
- Tests/Source/Model/Messages/ZMMessageTests.m
- ZMCDataModel.xcodeproj/project.pbxproj
If this PR is merged, we had the ability of validating the incoming emoji, so that if we receive an emoji that we are not expecting, nothing is inserted.
So far, the only emoji we take into account is ❤️
**NOTE**: This PR breaks the UI facing API.
> Validate emoji before inserting

- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
**In this PR**
We should not expire confirmation messages because they can't be resent and would create an unsent message list indicator upon fail.
> never expire confirmation messages

- Source/Model/Message/ZMClientMessage.m
This PR prevent the conversation lastRead to be updated when receiving like POST response.
> Stop updating last read when receiving like upload confirmation

- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMMessageTests.m
The `reactions` key on `ZMMessage` was not marked as ignored, causing sync engine to try to upload it
Ignore the `reactions` key (it was ignored only in `ZMSystemMessage`, it should have been ignored in the `ZMMessage` superclass instead)
Removing a key from the list of keys to synchronize (in this case, adding it to the ignore list) will cause the bitfield holding the list of keys that need to be synchronized upstream to go out of sync, potentially causing one other random key to be marked as needing to upload instead. This is undesired and might cause erratic behaviour for that one message, but it is better than the crash loop that we have if we without this PR.
> Fix crash due to "reaction" key on messages not being ignored

- Source/Model/Message/ZMClientMessage+Encryption.swift
- Source/Model/Message/ZMOTRMessage.h
- Source/Model/Message/ZMOTRMessage.m
- Source/Model/User/ZMUser.m
- Source/Model/UserClient/UserClient+Protobuf.swift
- Source/Model/UserClient/UserClient.swift
- Source/VoiceChannel/ZMCallState.swift
- Tests/Source/Model/Messages/BaseClientMessageTests.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
- Tests/Source/Model/UserClient/UserClientTests.swift
* `UserClient.remoteIdentifier` is now an Optional
* Fix a bug where self user images could not be deleted
* Add debug information property to `ZMOTRMessage`
> Adapt updated nullability annotations

- .travis.yml
- Source/Model/Message/ZMClientMessage.m
- Source/Notifications/ObjectObserverTokens/MessageObserverToken.swift
* Link previews did not show the image on the sender side, during the migration to Swift 3 we needed to optionally bind the `imageDataIdentifier` which is only present after the image has been uploaded. As we do not receive an additional notification when the image has been uploaded and also want to dimply the (original) image before it has been uploaded on the sender side the `imageDataIdentifier` property now returns the message nonce if there is an original image but no assetId for the link preview.
* Convert an enum to the new Swift 3.0 naming guidelines.
> Return message nonce as imageDataIdentifier in case there is an original image

- Source/Model/Message/ZMMessage.m
- Source/Model/Message/ZMOTRMessage.m
- Tests/Source/Model/Messages/ZMClientMessageTests.m
We experienced the weird crash on multiple user accounts reported with the same crash log: the relation in the database is created between objects in different managed object contexts.
One of the team members had this issue permanently on the work device, so it was possible to attach with debugger to the version installed. It came out that the app was trying to establish the relation between the object that does not belong to any context (deleted one) and the existing one. Deleted one had managedObjectContext set to nil.
On closer look it came out that the object that is having managed object context nil is received from object pre-fetch cache.
Check object before using it if it is `zombie` e.g. does not belong to any managed object context.
> Discard deleted messages from prefetch

- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Message/ZMClientMessage+Encryption.swift
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
We detected the crash loop state on Alan's phone. Crash happens when client is trying to send the confirmation for message delivery. The transcoder is trying to create the message payload for the client but fail to fetch the receiver.
It seems that in conversation between A and B, B sends message to A while A if offline. Then B deletes the message. A starts the client and start receiving the notifications. One notification inserts the new message from B, so A generates the delivery pingback. Then next message in the stream asks to delete the message, so message looses sender and all the data. Then we start to send the request for uploading the delivery pingback, but we fail because the message which we are pinging back about is deleted and there is no sender info.
Solution consists of two …
> Fix for crash when trying to confirm to deleted client

- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.h
- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Message/ZMClientMessage+Encryption.swift
**In this PR**
In a previous fix, we changed the recipients for delivery messages. However, instead of otherActiveParticipants (which returns nil for 1on1 conversations) we should use connectedUser which is the other user in a 1on1.
> Fix crash delivery notifications

- Source/Model/User/ZMPersonName.m
- Tests/Source/Model/User/ZMPersonNameTests.m
If a name contains a god name we skip it by advancing the starting index but we didn't decrease the length of the range, which results in an out of bounds error.
> Fix array out of bounds for arabic names

- Source/Model/Confirmation/ZMMessageConfirmation.swift
- Source/Model/Message/ZMClientMessage+Encryption.swift
- Tests/Source/Model/Messages/ZMGenericMessageTests+NativePush.swift
- ZMCDataModel.xcodeproj/project.pbxproj
Some users reported "New message" notifications without having received any new visible content inside the application. These notifications are received when we fail to pingback to the backend after receiving a `VoIP` notification, the most probable scenario is that this happens when we receive a lot of delivery receipt pushes and fail to pingback either because of bad network conditions or because we are running in the background for too long.
As there is no actual need to send native pushes for delivery receipts (as they are only visible in the UI and should not generate a local notification) we now no longer are sending them.
> Disable sending native pushes for delivery receipts

- Source/Model/Message/ZMAssetClientMessage+Encryption.swift
- Source/Model/Message/ZMClientMessage+Encryption.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTest+Encryption.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- ZMCDataModel.xcodeproj/project.pbxproj
**In this PR**
When sending an ephemeral message we should only send it to the clients of the other user, not to the clients of the selfUser. We implemented this behaviour for text messages already, but the implementation for asset messages was missing.
I moved some tests from one file to the another. lines to review for tests start at ZMAssetClientMessageTests_Encryption: 218
> Fix send ephemeral asset only to other user

- Source/Model/Conversation/ZMConversation+Ephemeral.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Ephemeral.swift
* Add timeout thirty seconds and five minutes values for ephemeral messages
* Move accessor for all possible timeout values from the UI protect into `wire-ios-data-model`.
> Add thirty seconds and five minutes timeout values

- Resources/zmessaging.xcdatamodeld/.xccurrentversion
- Resources/zmessaging.xcdatamodeld/zmessaging2.21.0.xcdatamodel/contents
- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation+Transport.m
- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ZMClientMessage+Encryption.swift
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser.m
- Source/Model/UserClient/UserClient.swift
- Source/Notifications/ObjectObserverTokens/ConversationObserverToken.swift
- Source/Public/ZMConversation.h
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
- Tests/Source/Model/Conversation/ZMConversationTests+participants.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/CoreDataRelationshipsTests.m
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
- ZMCDataModel.xcodeproj/project.pbxproj
Backend will remove support for list of inactive participants. It is also not used on the client at all.
Removed stored inactive (past) participants for conversations. We kept unsynchronized inactive participants (a computed property) because we need to know which participants to ask the BE to remove.
Also add nullability annotation to `ZMMessage+Internal.h`
This PR is missing database migration test. This is because next topic to include in the same release also require database changes and I will do them in the same model, and write one test at the end.
> Remove inactive participants

- Resources/zmessaging.xcdatamodeld/.xccurrentversion
- Resources/zmessaging.xcdatamodeld/zmessaging2.21.1.xcdatamodel/contents
- Source/ManagedObjectContext/ZMSyncMergePolicy.m
- Source/Model/Conversation/ZMConversation.m
- Source/Model/Reaction/Reaction.swift
- Source/Model/User/ZMUser.m
- Source/Model/UserClient/UserClient.swift
- Source/Model/ZMManagedObject+Internal.h
- Source/Model/ZMManagedObject.m
- Tests/Source/ManagedObjectContext/Migrations/OTRMigrationTests.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMMessageTests.m
- Tests/Source/Model/MockDataModel/MockEntity.m
- Tests/Source/Model/MockDataModel/MockModelObjectContextFactory.m
- Tests/Source/Model/User/ZMUserTests.m
- Tests/Source/Model/UserClient/UserClientTests.swift
- Tests/Source/Model/ZMConnectionTests.m
- Tests/Source/Model/ZMManagedObjectTests.m
- ZMCDataModel.xcodeproj/project.pbxproj
**In this PR**
We are currently tracking local modifications through a bitfield that is updated whenever we save: We loop through all the entity's attributes which are sorted alphabetically and store a 0 or 1 indicating modification. However, this leads to problems when we remove properties or exclude keys that were previously tracked. Since the removed key is then missing from the entity's attributes or included in the ignored keys, the bitfield would now be shifted and keys that were not modified were assigned the wrong value which would essentially lead to a crash when syncing.
To circumvent this, we decided to store the modified keys as strings instead, so we can assign the stored value to a specific changed key with certainty. In this case if we remove keys from the database or …
> Use actual keys to track local modifications

- Source/Model/Message/ZMClientMessage+Encryption.swift
- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMClientMessageTests+Deletion.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
**In this PR**
What happened: When the receiver of an ephemeral message was looking at the message on two devices at the same time, it is possible that we delete a message locally and receive the delete from the second device before creating the payload for the local delete. In this case we will end up in a crash loop.
To avoid this: When receiving a delete, we stop any timers for ephemeral messages.
> Stop deletion timer of ephemeral message on receiving delete

- Source/Model/Message/ZMMessage.m
Since the timer is stopped asynchronously, it is still possible that we delete the sender after the timer fired. We therefore moved the deletion of the sender inside the block where the timer is cancelled and execute another block after the timer was cancelled.
> Delete the sender after the ephemeral message timer was stopped

- Resources/zmessaging.xcdatamodeld/.xccurrentversion
- Resources/zmessaging.xcdatamodeld/zmessaging2.21.2.xcdatamodel/contents
- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/AssetEncryption.swift
- Source/Model/Message/FileAssetCache.swift
- Source/Model/Message/V2Asset.swift
- Source/Model/Message/V3Asset.swift
- Source/Model/Message/ZMAssetClientMessage+Download.swift
- Source/Model/Message/ZMAssetClientMessage.h
- Source/Model/Message/ZMAssetClientMessage.m
- Source/Public/ZMConversation.h
- Source/Public/ZMMessage.h
- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- ZMCDataModel.xcodeproj/project.pbxproj
- ZMCDataModel.xcodeproj/xcshareddata/xcschemes/ZMCDataModel.xcscheme
This adds the initial logic to support receiving assets send using the `/assets/v3` endpoint, this also refactors `ZMAssetClientMessage` internally to declutter the code from constant `self.version < 3` checks.
To do so the `imageMessageData` accessor now returns different implementations of this protocol depending on the version of the underlying asset. The two new added classes, `V2Asset` and `V3Asset` manage which cache and which cache key should be used to store the asset data and where to look for the image / file data etc.
There are still a couple of missing test for the receiving part that I am working on right now.
> Add logic to receive /v3 assets

- Source/Model/Message/V2Asset.swift
- Source/Model/Message/V3Asset.swift
- Source/Model/Message/ZMAssetClientMessage.h
- Source/Model/Message/ZMAssetClientMessage.m
- Tests/Source/Model/Conversation/ZMConversationTests+messages.m
* `ZMAssetClientMessage` itself does no longer conform to `ZMImageMessageData` as it returns the `imageMessageData` of its underlying versioned asset container, thus a lot of methods have been removed.
* Move more methods into the versioned asset container classes.
> Move methods into versioned asset containers and delete unused code

- Source/Model/Message/V3Asset.swift
- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
* There was an issue on the UI in which the video playback did not work as the url was missing the file extension. We now append the filename to the asset ID when creating the cache key which is used as url.
> Append filename to cachekey

- Source/Model/Message/ZMMessage.m
**What's happening?**
We are currently experiencing a crash in `[ZMMessage updateWithTimestamp:senderUUID:eventID:forConversation:isUpdatingExistingMessage:]` 
> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Illegal attempt to establish a relationship 'sender' between objects in different contexts
It's impossible that the objects are really from different contexts since the sender is created  or fetched using the managedObjectContext of the message. It is very possible that the message is currently being deleted since this crash was introduced with deleting message. However, the flag isDeleted seems not to be returning `true` since we check for zombie objects in the method that calls this one and return early. 
To prevent further crashes, I added another …
> Avoid crash when setting sender on updated message

- Source/Model/Message/V3Asset.swift
The AssetV3PreviewDownloadStrategy uses a whitelist, when extracting the `requestImageDownload` method in https://github.com/wireapp/wire-ios-data-model/pull/80 I missed to fire the notification to whitelist the preview image.
> Fix preview images not being downloaded

- Source/Model/Message/ZMAssetClientMessage.m
- Source/Public/ZMMessage.h
* Re-add isImage flag used on the UI to check if a message is a file that represents an image, this flag was removed in 972c200 but is needed on the UI.
> Re-add isImage flag

- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m
We have several crashes when accessing a value in the managedObjectContext's userInfo. Instead of returning the proper value, it returns an object of a different class. I added a helper method to log what exactly is currently contained in the MOC's userInfo.
> Add crash info for crash when accessing MOC's userInfo

- Source/Model/Message/ZMMessage.m
- Source/Model/Message/ZMOTRMessage.m
Looking at crash logs, I noticed that the message that caused the crash is a temporary object, it is not faulted and has all properties set to nil. This hints to the object being inserted and deleted without an intermittent save. In addition to that, the crash only happens with AssetMessages.
After further investigation I found: When inserting an asset message, it is possible that the message is deleted when the sha265 digest does not match the expected one. In this case - when an NSManagedObject is inserted and deleted without intermittent save - it seems like the isDeleted flag on the object is not set (It's possible that isDeleted is computed from the deletedObjects property of the context which as the documentation states might not include inserted & immediately deleted objects). The …
> Attempt at fixing crash updating deleted asset message

- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
When sending a message we want to archive the conversation this message belongs to, until sending a message in an unarchived conversation was not possible or the conversation was unarchived on the caller site, but with forwarding and an upcoming share extension it makes more sense to move this logic into `wire-ios-data-model`.
> Unarchive a conversation when appending a message

- Source/Model/Message/ZMClientMessage+Encryption.swift
I need to expose this method so that I can encrypt `ZMGenericMessage`'s from `wire-message-strategy`
> Make encrypt function on ZMGenericMessage public

- Source/Notifications/ObjectObserverTokens/UserObserverToken.swift
- Tests/Source/Model/Observer/ObjectObserverToken/UserObserverTokenTests.swift
* There was no way of getting notified when a user's username changes, this adds the `"handle"` key to the observable keys.
* This is needed in order to dismiss the takeover screen on a secondary device when a username is set on the primary one.
> Add observation for username

- Source/Model/Message/ZMMessage+Categorization.swift
- Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift
We want to exclude certain categories when fetching messages, e.g. fetch all files but not videos
> Add filter to query for message category

- Source/Model/Message/ZMMessage+Categorization.swift
- Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift
Fixed crash loop caused by incorrect string length calculation.
> Check characters.count instead of utf8.count

- Source/VoiceChannel/VoiceChannelRouter.swift
- Source/VoiceChannel/WireCallCenterMock.swift
- Tests/Source/Model/VoiceChannel/VoiceChannelRouterTests.swift
- ZMCDataModel.xcodeproj/project.pbxproj
It wasn't possible to answer att incoming C3 call with the C3 flag turned off.
> Fix incoming C3 call with C3 flag turned off

- Source/Model/Conversation/AssetCollectionBatched.swift
Mutating the array proxy we get from the fetchRequest would copy and materialize all objects inside of it. So I now make sure it's stored in a let and never mutated.
> Avoid mutating array proxy

- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ConversationMessage+Deletion.swift
- Source/Model/Message/ConversationMessage+Reaction.swift
- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMClientMessageTests+Deletion.swift
- Tests/Source/Model/Messages/ZMClientMessagesTests+Reaction.swift
- Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift
Messages were not categorized on insert which would lead to weird reordering of the collection after fetching messages.
Also messages were not updated when they were liked, or deleted.
> Categorize on insert, update on like & delete

- Source/Model/Conversation/AssetCollection.swift
- Source/Model/Conversation/AssetCollectionBatched.swift
- Tests/Source/Model/Conversation/AssetCollectionBatchedTests.swift
- Tests/Source/Model/Conversation/AssetColletionTests.swift
Pre-categorized messages were stored as sync objects instead of UI objects and then again added as UI objects.
> Do not set assets from syncMOC

- Source/Model/Conversation/AssetCollection.swift
- Source/Model/Conversation/AssetCollectionBatched.swift
The UI is only updating the view once the view did load. If we have no messages in the conversation, the view might load after we are done fetching the messages which would result in an endless spinner.
To avoid that, we should check if the AssetCollection is doneFetching in the viewDidLoad and then update the internal flag of the VC and the loading elements accordingly
> Expose doneFetching parameter

- Source/ManagedObjectContext/NSManagedObjectContext+Debugging.swift
- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m
- Tests/Source/ManagedObjectContext/NSManagedObjectContextDebuggingTests.swift
- ZMCDataModel.xcodeproj/project.pbxproj
Adding a callback to notify when saving the managed object context fails, so that we can debug why it's happening
> Add callback when a failure to save is detected

- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
This PR fixes a race condition between the self user requests. It was possible
that the response handling for fetching the self user could interfer with
uploading your profile picture.
https://wearezeta.atlassian.net/browse/ZIOS-7798
> Fix for profile picture no being set after registration

- Source/Model/Conversation/ZMConversation+DisplayName.swift
- Source/Model/Conversation/ZMConversation.m
- Source/Public/ZMConversation.h
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
- ZMCDataModel.xcodeproj/project.pbxproj
* The logic to use the empty group conversation placeholder [has been removed here](https://github.com/wireapp/wire-ios-data-model/commit/cad79d#diff-e67417d73be307cd0a79a4351caef75eL470).
* The `displayName` logic in `ZMConversation` has been rewritten in Swift and extracted in an extension.
* Add test for empty group conversation placeholder.
> Fix missing empty group conversation name

- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation.m
- Source/Public/ZMConversation.h
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMClientMessageTests+Ephemeral.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
- Tests/Source/Model/Messages/ZMClientMessageTests.m
* At the moment we do not want to fetch link previews when sending messages through the iOS share extension (this might change at some point). 
* As the share extension does not fetch the previews itself this currently leads to the previews being fetched once the main app is opened, which is undesired. 
* This PR adds a parameter to specify if a link preview should be fetched when appending a text message.
> Add option to append a message without fetching link preview

- Source/Model/Conversation/AssetCollection.swift
- Source/Model/Conversation/AssetCollectionBatched.swift
- Tests/Source/Model/Conversation/AssetCollectionBatchedTests.swift
- Tests/Source/Model/Conversation/AssetColletionTests.swift
When writing tests for collections we need to be able to mock various messages and it's way easier when API works with protocols instead of `NSManagedObject` subclasses.
> Updated collection delegates to return more abstract types

- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
Detection of bots (as opposed to users) was done by comparing emails. Since emails are gone, detection is now done with handles.
> Use hardcoded bot handles instead of hardcoded emails

- Source/Model/Conversation/SharedModifiedConversationsList.swift
- Tests/Source/Model/Conversation/SharedModifiedConversationsListTests.swift
- ZMCDataModel.xcodeproj/project.pbxproj
In the iOS Share Extension, we set up a separate Core Data stack that uses the same persistent store as the main app, but has it's own two contexts. When sending a message the main app will not receive a change notification (as it uses different contexts). The change will be in the persistent store on disk but will not be propagated, which is why we now keep a list of touched conversations, manually turn them into faults and fire a notification for their last message with observer system in order to update the message window and notify the UI.
> Add modified conversation list to store touched conversations from an extension context

- Source/Model/Conversation/SharedModifiedConversationsList.swift
- Tests/Source/Model/Conversation/SharedModifiedConversationsListTests.swift
* In order to update the main app when changing the database from an extension we need to persist the `NSManagedObjectContextDidSave` notifications so we can merge them into the main apps contexts using `+mergeChangesFromRemoteContextSave:intoContexts:`.
* This PR adds a helper to serialise and persist the relevant data of a `Notification`s `userInfo` in the shared defaults and to access it again.
> Add helper to store save notifications

- Source/Model/Message/ConversationMessage.swift
- Source/Model/Message/ZMAssetClientMessage.m
- Source/Model/Message/ZMMessage+Categorization.swift
- Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift
In the collections we shouldn't show GIFs to save download data, but it was showing up for the sender.
Message category is cached, but was getting out of sync and didn't have the information that we can get after processing the image. In this case the image message category was not updated to reflect that it's a GIF.
> Collections: do not show gifs in the list

- Tests/Source/Model/Conversation/AssetCollectionBatchedTests.swift
In #131 the behaviour for fetching images was changed slightly and there was one failing test. On closer inspection the new result makes more sense.
> Fix test failure after last PR

- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation.m
- Source/Notifications/ObjectObserverTokens/ConversationObserverToken.swift
- Tests/Source/Model/Observer/ObjectObserverToken/ConversationObserverTokenTests.swift
When a conversation degrades from verified to not verified with a message, if the app is killed and restarted, the takeover warning of the degradation is displayed again at every restart.
- Do not display the takeover if the conversation snapshot had no security level (e.g. there was no snapshot). It means that we just restarted the app. The message will still not be sent anyway (it is already marked as "expired") in any case.
- Remove magic string
> Make sure security warning when a conversation degraded is displayed once only

- Source/Model/Message/ZMFileMetadata.swift
If the name of an asset is inferred from the local URL of the file that contains the data, it could be that the name is not meaningful (e.g. sometimes we use UUIDs as file names to be reasonably sure we don't override other older files).
Having the option to specify the name of the file independently of the actual URL of the local file avoids this problem.
> Add explicit naming of files for assets

- Source/ManagedObjectContext/NSManagedObjectContext+UserInfoMerge.swift
- Source/Model/Message/ConversationMessage.swift
- Source/Model/Message/ZMOTRMessage+SecurityDegradation.swift
- Tests/Source/Model/Messages/ZMOTRMessage+SecurityDegradationTests.swift
- ZMCDataModel.xcodeproj/project.pbxproj
Add ability to mark messages that have degraded a conversation. This info is kept in memory, not persisted, hence it needs to be merged between contexts manually. 
The actual marking when we receive a 412 will be done in another PR (potentially in WireMessageStrategy, still have to check)
- added generic method to merge user info from a different context
- added ability to mark a message as causing conversation degradation (but only on the sync context)
> Add ability to mark messages that have degraded a conversation

- Source/Model/Conversation/ZMConversation+MessageDeletion.swift
- Source/Model/Conversation/ZMConversation+NotifyOnUI.swift
- Source/Model/Conversation/ZMConversation+OTR.swift
- Source/Model/Conversation/ZMConversation.m
- Source/Public/ZMConversation.h
- Tests/Source/Model/Conversation/ZMConversationTests+OTR.m
- Tests/Source/Model/Conversation/ZMConversationTests+Timestamp.m
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
- Tests/Source/Model/Conversation/ZMConversationTests+UnreadCount.m
- Tests/Source/Model/Conversation/ZMConversationTests+Validation.m
- Tests/Source/Model/Conversation/ZMConversationTests+gapsAndWindows.m
- Tests/Source/Model/Conversation/ZMConversationTests+messages.m
- Tests/Source/Model/Conversation/ZMConversationTests+participants.m
- Tests/Source/Model/Conversation/ZMConversationTests.h
- Tests/Source/Model/Conversation/ZMConversationTests.m
- ZMCDataModel.xcodeproj/project.pbxproj
The detection of which messages caused the conversation to degrade the security level was a bit hacky, and it would case a few issues (takeover displayed at every restart, resending of all expired messages even if they were expired for other reasons).
This PR make it possible to resend/cancel only those messages that caused the conversation to degrade.
- Also fixed test subclassing (it was causing the same tests to be run many times)
- Also extracted methods not related to conversation degradation, as mentioned in https://github.com/wireapp/wire-ios-data-model/pull/135
> Better message expiration/resend in case of security degradation

- Source/Model/Conversation/ZMConversation+OTR.swift
- Source/Model/Message/ZMOTRMessage+SecurityDegradation.swift
- Tests/Source/Model/Conversation/ZMConversationTests+OTR.m
Changing the flag `causedSecurityLevelDegradation` is supped to be done only on the sync context. The code in `resendMessagesThatCausedConversationSecurityDegradation` and `doNotResendMessagesThatCausedDegradation` was modifying it on the UI context. 
- Also addressing the issue with duplicated code mentioned in: https://github.com/wireapp/wire-ios-data-model/pull/136
> Refactor common code and fix using wrong context

- Source/Model/Message/ZMAssetClientMessage.m
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
If the upload status is set to "failed" for files, it will upload the "failed to upload" placeholder. When we want to expire a message, we instead should set the transfer state to failed and the upload status to "done".
> Set status to "done" when expiring

- Source/Model/Conversation/AssetCollection.swift
When running with CoreData threading sanitizer the app used to crash on opening the collection. 
`conversation` appears to refer to instance method that is the conversation passed in as the parameter. It is created on UI context. `syncConversation` is the one to use on the sync context.
> Dispatch to correct thread

- Source/Model/Message/ZMAssetClientMessage.m
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
* Only set the uploaded state to done when the placeholder was not yet uploaded
* When a conversation degrades we do not want to send a `Asset.NotUploaded` message, but in case we already sent the placeholder (which should not happen when the conversation did degrade) we want to send it.
> Only set the uploaded state to done when the placeholder was not yet uploaded

- Source/ConversationList/ZMConversationList.m
- Source/ConversationList/ZMConversationListDirectory.h
- Source/ConversationList/ZMConversationListDirectory.m
- Source/Notifications/ObjectObserverTokens/ConversationListObserverToken.swift
- Source/Notifications/ObjectObserverTokens/GlobalConversationObserver.swift
- Source/Notifications/ObjectObserverTokens/ManagedObjectContextObserver.swift
- Source/Public/ZMConversationList.h
- Tests/Source/Model/ConversationList/ZMConversationListTests.m
**In this PR**
We have the following bug: When the user is added to a new conversation while the app is in the background, the conversation does not show up in the list. The reason for this is that the list relies on the conversation observer to insert or remove conversations. The global conversation observer however does not receive notifications while in the background. 
Currently we are only resorting the list when reentering the foreground but this does not solve the case where the conversation was inserted  or deleted. Instead we should refetch all conversations and recreate the backinglists. At the same time we should make sure that the snapshots we keep of each list is recreated to avoid wrong change notifications.
This PR adds a new API for the UI `[ZMConversationList …
> Add method to recreate conversation lists when entering the foreground

- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m
Applying patches on the main thread (or more accurately, on the sync thread but having the main thread block waiting for it) will freeze the UI if the user has a big database
> Apply patches on persisted data asynchronously to avoid blocking UI

- Source/Model/UserClient/UserClient.swift
- Tests/Source/Model/UserClient/UserClientTests.swift
It was detected during the testing that opening the verification screen after having a chat with the participant and verifying his device is breaking the session with this device.
After investigating the behavior it came out that when we opened the screen with user device for the first time we requested the fingerprint for it if it was not there, and by making so the device was marked by accident as missing. This kicked in the request to download the device prekey and when it was done the session was deleted and recreated. This caused the session to be broken for the sender.
The method to fetch fingerprint was refactored because it actually had some logical errors, also we are not forcing the session deletion when receiving the devices any more.
> Fix cannot decrypt after verifying the device

- Source/Model/UserClient/UserClient.swift
- Tests/Source/Model/UserClient/UserClientTests.swift
- Tests/Source/Model/ZMBaseManagedObjectTest.m
In order to fetch the fingerprint for a new selfUser client, we need to have a sessionIdentifier for this client. The sessionIdentifier consists of the client remoteID and the user remoteID. This in turn means, we have to set the user before trying to fetch the fingerprints.
> Set the user when inserting a new selfuser client

- Gemfile
- circle.yml
It would be good to have tests running on pull requests. CircleCI looks like the most popular tool for this so why not to try it.
Added a config that could be reused in all other repos, because it doesn't have any `wire-ios-data-model` code. The resulting config is slightly convoluted, because it re-uses exactly the same build scripts as we currently use on Jenkins.
Let's see how it all works out and maybe we can set up other repos in the same fashion.
> Added CircleCI integration

- Source/Model/User/DisplayNameGenerator.swift
- Tests/Source/Model/User/DisplayNameGeneratorTests.swift
The displayName map is created on demand - when any users displayName is accessed for the first time (or when we have inserted or updated users, but that's not happening in the share engine). This step - fetching all users and creating the displayName map - was missing due to refactoring.
> Fetch all users when first accessing displayName

- Source/Model/Message/TextSearchQuery.swift
- Tests/Source/Model/TextSearchQueryTests.swift
* Add more tests (especially regarding the transliteration rules).
* Split search query and filter elements with a length below 2 characters.
* Notify the delegate immediately if there are no valid query components. Otherwise `predicateForMessagesMatching` will return a `NSPredicate` matching all messages.
> Add more tests for text search logic

- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m
- Source/Model/Conversation/ZMConversation+DisplayName.swift
- Source/Model/Conversation/ZMConversation.m
- Source/Model/User/DisplayNameGenerator.swift
- Source/Model/User/PersonName.swift
- Source/Model/User/ZMSearchUser.m
- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser.m
- Source/Notifications/NotificationDispatcher.swift
- Source/Notifications/ObjectObserverTokens/UserChangeInfo.swift
- Source/Notifications/SnapshotCenter.swift
- Source/Public/ZMBareUser.h
- Source/Public/ZMUser.h
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Observer/ConversationObserverTests.swift
- Tests/Source/Model/Observer/MessageWindowObserverTests.swift
- Tests/Source/Model/Observer/NotificationDispatcherTests.swift
- Tests/Source/Model/Observer/SnapshotCenterTests.swift
- Tests/Source/Model/Observer/UserObserverTests.swift
- Tests/Source/Model/User/DisplayNameGeneratorTests.swift
- Tests/Source/Model/User/ZMPersonNameTests.m
- Tests/Source/Model/User/ZMUserDisplayNameGeneratorTest.m
- Tests/Source/Model/User/ZMUserTests.m
- Tests/Source/Model/ZMBaseManagedObjectTest.h
- Tests/Source/Model/ZMBaseManagedObjectTest.m
Since we only want to show first names / given names in the conversation, we don't need to calculate the displayNames on start in batch and can instead do the heavy calculations (extracting the script scheme) on demand for each user. Since PersonNames are cached, we can easily access them again later. 
I added another method for the UI to get the displayName for a user in a conversation - if we want to do that - so that we can show the full name for users who have the same given name. It creates a map on demand for this conversation. If you call this method with a different conversation than before, it discards the old map. Also the map does not update when the user changes while the conversation is in the view. This however, could make opening conversations (for the first time) slow …
> Use givenName as displayName, calculate personName on demand

- Source/Notifications/MessageWindowObserverCenter.swift
- Tests/Source/Model/Observer/MessageWindowObserverTests.swift
The UI might recreate the window for the same conversation. Since we subscribe to notifications for the window object, it would not receive notifications for the new window if we don't recreate the snapshot.
> Compare window not conversation

- Source/Model/Message/TextSearchQuery.swift
- Tests/Source/Model/TextSearchQueryTests.swift
* We were getting the count for all non-indexed `ZMMessage`s, instead of `ZMClientMessage`s. As we only care about client message for now we should restrict the fetch request to this entity.
* Add the last batch of test (testing large messages, link previews, images present in a conversation).
> Do not fetch count for all not indexed messages

- Source/Model/User/DisplayNameGenerator.swift
- Tests/Source/Model/User/DisplayNameGeneratorTests.swift
Change of design:
If a user has the same name as the selfUser his/her displayName should be:
in groups: fullName
in 1on1: givenName
The selfUser's name should always be the firstName
> Show fullName for user with selfUser’s name in groups, given name in 1on1

- Source/Model/User/DisplayNameGenerator.swift
- Tests/Source/Model/User/DisplayNameGeneratorTests.swift
When we request a displayName, we check if the fullName changed in comparison to the one we stored. If so, we recreate the displayName map.
> Update displayName map when user name changes

- Source/Notifications/ConversationListObserverCenter.swift
- Source/Notifications/MessageWindowObserverCenter.swift
- Source/Notifications/SnapshotCenter.swift
- Tests/Source/Model/Observer/ConversationListObserverTests.swift
+ minor other fixes
When the notificationDispatcher fires all notifications we forward the change infos to the changeInfoConsumer including the ConversationListObserverCenter. We were exiting early when the changes did not include any conversation changes. However, if there were conversations inserted in the same save, but none changed, then we would not fire the notification for the inserted conversation.
The main fix is in ConversationListObserverCenter line 80.
> Fix inserted connection requests not being shown in the list

- Source/Model/User/DisplayNameGenerator.swift
- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/DisplayNameGeneratorTests.swift
The method for `displayNameInConversation` is called from an ObjC interface which does not safely check for nullability.
Also, if a user's displayName is requested in a conversation he is not a member of and his name is not set, it does now not crash anymore.
> Fix crash nil userName or nil conversation

- Source/Model/Message/TextSearchQuery.swift
- Tests/Source/Model/TextSearchQueryTests.swift
* When searching in a conversation without any messages that can be searched the `TextSearchQueryDelegate` was never notified.
* Fixes the failing `wire-ios-sync-engine` test `testThatItDoesNotFindAMessageDeletedRemotely`.
> Call the delegate with empty results if there are no messages to be searched

- Source/Notifications/NotificationDispatcher.swift
- Source/Notifications/SnapshotCenter.swift
Fix 1:
When an observer performs a save when receiving a notification from the dispatcher we can currently end up in a loop because we are clearing snapshots and all changes only after they have been propagated. Now we are copying them to a local instance and/or clear them before propagating changes.
Fix 2:
In a recent PR i changed the snapshot to use valueForKey instead of primitiveValueForKey.
That was a mistake. Apparently when you use `primitiveValueForKey` it looks up the value in the CoreData snapshot. When we use `valueForKey` it refreshes CoreData's snapshot before returning the value. This way we don't notice when an object changes during a merge. Phuh...
> Various fixes notification center

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/UserClient/UserClient.swift
- Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.m
We want to be able to distinguish wether the securityLevel of a secured conversation changes due to
a) you unverified a client
b) someone added a new client
c) a new person with unverified client was added
Currently c) is not possible. In order to distinguish case c) in the UI, we now set the addedUsers property on the SystemMessage
> Set addedUsers property on system message if client of added participant

- Source/Model/Conversation/ZMConversation+Patches.swift
- Source/Utilis/PersistedDataPatches+Directory.swift
- Tests/Source/Utils/PersistedDataPatchesTests.swift
- ZMCDataModel.xcodeproj/project.pbxproj
After changes introduced in #179 users with conversations with security level `.secureWithIgnored` would get security degradation modal screen. This will also happen for conversations that were verified at some point in the past and became degraded. We need to find all conversations like this and mark them as not secure.
> Migration after conversation degradation changes

- Source/Model/Message/ZMClientMessage.m
* This logic is moved into a new strategy which utilises a modified object sync instead.
* This modifies the internal behaviour heavily, so I am unsure if it shouldn't be a major release.
> Do not re-insert client message with uploaded link preview

- Source/Model/Message/ConversationMessage+Reaction.swift
- Source/Model/Reaction/Reaction.swift
- Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift
- Tests/Source/Model/Messages/ZMMessageTests.m
* This value will be used from `wire-ios-sync-engine` and it generally makes more sense to keep it in the data model instead of the UI.
> Move concrete reaction value into data model

- Tests/Source/Model/Conversation/ZMConversationTests+messages.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMMessageTests.m
Errors are happening mostly because we now preprocess the images before uploading, removing the metadata.
For some reason, removing the metadata twice still produces the data that is different from the one where the metadata is removed once:
So I decided that it would be equally good to compare the data length with the expected data.
> Fixed failing images tests

- Source/Model/User/ZMSearchUser.m
- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMSearchUserTests.m
* When searching for an unconnected user we did not update the local user (we never refetch unconnected users at the moment).
* The local user will now be updated if the search returned a different handle or name as we have stored locally.
* This is the underlying issue which was tried to be resolved in of https://github.com/wireapp/wire-ios/pull/743 and https://github.com/wireapp/wire-ios/pull/750 and also the reason these two PR's did not solve the issue.
> Update local user if search result has different handle / name

- Source/Model/Conversation/ZMConversation+Calling.swift
- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Notifications/NotificationDispatcher.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
With V3 calling, missedCall systemMessages are inserted locally and not like previously through an push event. Therefore, we need to make sure that the conversation is updated accordingly, which means: 
1) If the conversation is archived and not silenced, we need to unarchive the conversation.
2) We need to updated the lastUnreadMissedCallDate timestamp in order to show the missedCall conversationList indicator.
Also in this PR: A minor change to how we handle nonCoreDataChanges. We used to enforce a save in order to make sure we send out the notifications with all the other changes. Instead we now check if the uiContext hasChanges which means it will most likely be saved soon. If it does not have changes, we fire the notification immediately.
> Update missedCallTimeStamp and isArchived inserting missedCall

- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.m
When blocking a user, we receive a conversation update from the backend. We process the update and call internalAddParticipants with a user that is already part of the conversation (the blocked user). Since we degrade the conversation when users are added and previously did not check of those "added" user are already part of the conversation, the securityLevel falsely decreases.
We now check if the "added user" is already there and only if not, we degrade the conversation.
> Don’t decrease security level for already added users

- Source/Notifications/ConversationListObserverCenter.swift
- Source/Notifications/NotificationDispatcher.swift
- Tests/Source/Model/Observer/ConversationListObserverTests.swift
- Tests/Source/Model/Observer/NotificationDispatcherTests.swift
**The Crash**
The app was crashing when logging in to an existing account. The reason as it seems was a timing issue with the conversationListObserver:
1) A new conversation was inserted, the list observer inserted it into the list
2) The conversationListObserver registered
3) The notification for the insertion and subsequent updates was sent
=> The app crashes since the notification "assumes" that the observer does not know about the conversation yet
**The solution**
Instead of updating the list immediately, we wait until the merge / save is complete and all change notifications are computed. Only then do we process inserted and deleted conversations and update the lists and immediately notify the observers.
> Immediately notify after updating conversation list

- Source/Public/ZMBareUser.h
* We will stop using the `/search/common` endpoint and the UI only needs to know the number of common connections. This PR updates the `ZMCommonContactsSearchDelegate` protocol accordingly.
> Update ZMCommonContactsSearchDelegate protocol

- Source/Notifications/ObjectObserverTokens/ConversationListChangeInfo.swift
- Source/Notifications/ObjectObserverTokens/Helpers/SetSnapshot.swift
- Source/Notifications/ObjectObserverTokens/MessageWindowChangeInfo.swift
- Tests/Source/Model/Observer/ConversationListObserverTests.swift
We have several crashes when updating the conversationList or other collections for which we calculate changes. These crashes can happen, when we send a notification for a change and the collection changes between creating the notification and processing the notification by the observer. The observer currently does not know about the state with which the notification was created, instead it gets the current state of the collection. 
To avoid future crashes, we can send the state of the collection at the time of creation along with the SetChangeInfo. The observer can then use this collection to populate its views or can compare the current state of the collection with the one in the notification and then reload the views instead of using the update.
> Send currentState in SetSnapShot to avoid crashes

- Source/Model/Conversation/ZMConversationMessageWindow+Internal.h
- Source/Model/Conversation/ZMConversationMessageWindow.m
- Source/Notifications/MessageWindowObserverCenter.swift
- Tests/Source/Model/Conversation/ZMConversationMessageWindowTests.m
- Tests/Source/Model/Observer/MessageWindowObserverTests.swift
- Before the `MessageWindowObserverCenter` allowed only one window snapshot.
- Bug happened when we used to display two conversation views at the same time (with force touch in conversation list).
- In this case the latter window was loosing the observer since it's snapshot was removed when first window was deallocated.
Also removed some old and unused code / notifications.
> Allow having multiple message windows

- Source/Model/UserClient/UserClient.swift
Always re-create a session when we get a prekey, even if that session exists already
> Make sure sessions with prekeys are always established

- Source/Model/Message/ZMClientMessage.m
Sometimes an expired message will have the flag "encrypted" set to false (unexpectedly) and not upload. The flag is not actually used anymore and will be removed in another PR, that will affect multiple frameworks.
I'm just changing the predicate here as a quick fix.
> Upload messages regardless of the “encrypted” flag

- Source/Notifications/NotificationDispatcher.swift
If there are changes to the context, but we "forget" to save, the non-core data change will never propagate
> Make sure we always save on non-core data changes

- Source/Notifications/ChangeCalculation/ChangedIndexes.swift
- Tests/Source/Model/Observer/ChangedIndexesTests.swift
- ZMCDataModel.xcodeproj/project.pbxproj
The current ZMChangedIndexes is based on c++ and fails when comparing Swift structs (e.g. String, UUID). Therefore the rewrite in Swift.
> Rewrite ZMChangedIndexes in Swift

- Source/Model/User/SearchUserAsset.swift
- Source/Model/User/ZMSearchUser+Internal.h
- Source/Model/User/ZMSearchUser.m
- Source/Model/User/ZMUser.swift
- Tests/Source/Model/User/ZMSearchUserTests.m
- ZMCDataModel.xcodeproj/project.pbxproj
* Update `ZMSearchUser` to expose a `completeAssetKey` to be used for v3 assets.
* `SearchUserAsset` has been added and can be either a legacy or v3 asset.
* Unfortunately an Objective-C wrapper (`SearchUserAssetObjC `) had to be added which makes this enum accessible in the `ZMSearchUser.searchUserToMediumAssetIDCache.
> Update search user for v3 profile assets

- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
Add `delivered` property to `ZMSystemMessage` since some predicates rely on it.
> Add delivered property to ZMSystemMessage

- Source/Model/Conversation/ZMCallState.swift
- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/VoiceChannel/ZMCallStateTests.swift
This is only needed to show the correct conversationListIndicator in group calling.
Merging this PR should not have an impact on previous calling & list behaviour.
> Store callState for V3 group calling in memory

- Source/Model/User/ZMUser.swift
Mapping between ZMImageFormat and size used in other places was reversed
> Fix: small and large images are mixed up

- Source/Model/User/ZMUser.m
The issue was noticed in SE integreation tests where the changes to asset v3 identifiers would not get picked up and the user stayed unsynced.
> Updated user predicate to include asset v3 identifiers

- Source/Model/Conversation/ZMConversation+Calling.swift
- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Conversation/ZMConversationTests+CallSystemMessages.swift
* We still receive update events for group calls until they use v3. This lead to the issue that we inserted a performed call system message when placing a group call, but also inserted a missed call system message in case we hung up before anyone connected (triggered by the received update event). We do not want to insert a missed call message in this case and ignore the update event if the sender is self from now on.
* This also exposes a couple of methods needed for https://github.com/wireapp/wire-ios-message-strategy/pull/56.
> Do not insert missed call system message from update event if sender is self

- Source/Model/Message/ZMMessage.m
In a v2 group call a missed call could be "completed" because it happened between other people in the chat without you joining. In this case the `reason` is `completed` and we wouldn't insert system message.
> Fix: missed call message for group calls that you didn't join

- Source/Model/Conversation/SharedObjectStore.swift
- Tests/Source/Model/Conversation/SharedObjectStoreTests.swift
This is another place where we use `NSKeyedUnarchiver` and it could potentially cause issues similar to https://github.com/wireapp/wire-ios-sync-engine/pull/338.
We make a fix-up for class names by replacing the old module name with new one and creating class from string. To test it I had to unfortunately add a dummy class to the `WireDataModel` because it will not be resolved by `NSClassFromString` otherwise.
> Fix potential crash when loading data saved before project rename

- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
- Source/Public/ZMMessage.h
- Tests/Source/Model/Conversation/ZMConversationTests.m
Since systemMessages now have children, we need to consider the children's timestamp when updating the lastReadServerTimestamp as well as when computing the lastReadMessage.
> Fix missed call message

- Source/Model/Message/ZMMessage.m
This reverts commit 109ce8622eb5b0c415bbf2b7739fff7a347ad55a and should fix the last failing SE test.
> Revert missed call message introduced in #234

- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
The V2 profile picture upload could be interrupted if the self user was
fetched before it was completed. We were missing a check for local
modifications.
This bug only seems to happen on the SE without a state machine.
> Fix profile picture race condition

- Source/Model/User/ZMSearchUser.m
- Tests/Source/Model/User/ZMSearchUserTests.m
- The issue happened to appear because we changed the implementation of how user images work with assets v3.
- In `ZMUser` `imageSmallProfileIdentifier` we rely on `localMediumRemoteIdentifier`, which is not set any more.
- In `ZMSearchUser` we used to rely to user's `localMediumRemoteIdentifier`.
Solution:
- In `ZMSearchUser` we should always forward the call to `smallProfileImageCacheKey` to user if it is there. Cache key is there.
> Fixed missing reuse identifier for avatar image

- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMClientMessageTests+Ephemeral.swift
This was happening when you have two clients that receive the ephemeral message and timer in the other client runs out faster. That client then sends out message delete event which when received by iOS client deletes the message. Because of nested perform blocks UI doesn't receive conversation change notification.
> Fix for ephemeral message negative timer

- Source/Model/Message/ZMAssetClientMessage.m
- Source/Model/Message/ZMMessage+Insert.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
The issue happened due to the check of `uploadState` in `v3_isReadyToUploadUploaded` of `AssetClientMessageRequestStrategy`.
The `ZMAssetClientMessage`'s `resend` method was setting the `uploadState` to `uploadingPlaceholder`, which is not accepted as the proper state by the request strategy for images, but works correctly for file messages.
Also fixes threading for `expireAndNotifyIfInsertingIntoDegradedConversation` which can be called from main thread and from the sync thread.
> Allow resume sending image asset messages

- Source/Model/Analytics/Clusterizer+MessageCount.swift
- Source/Model/Analytics/Clusterizer.swift
- Source/Model/Analytics/MessageCountTracker.swift
- Tests/Source/Model/Utils/MessageCountTrackerTests.swift
- WireDataModel.xcodeproj/project.pbxproj
* For analytics purposes it would be nice to know the count of pre end-to-end encryption messages in the database.
* This also moves some analytics related classes from `wire-ios-sync-engine` to `wire-ios-data-model` (see https://github.com/wireapp/wire-ios-sync-engine/pull/361).
> Track count of legacy messages

- Source/Notifications/MessageWindowObserverCenter.swift
- Source/Notifications/ObjectObserverTokens/MessageWindowChangeInfo.swift
- Tests/Source/Model/Observer/MessageWindowObserverTests.swift
When ephemeral message expires with app in the background, after it goes back to foreground the message list is not updated. The same happens if someone likes a message for example.
So the solution is a bit blunt, but should fix other yet unreported bugs - we added a flag that UI should pick up and reload the conversation even if there are no computed changes.
> Reloading message window when coming to foreground

- Source/Model/Connection/ZMConnection.m
- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
- Tests/Source/Model/ZMConnectionTests.m
- WireDataModel.xcodeproj/xcshareddata/xcschemes/WireDataModel.xcscheme
After accepting incoming connection the conversation doesn't have any messages and its `lastModifiedDate` is `1970-01-01`. We use this for sorting the conversation list and it then goes to the absolute bottom.
The fix is to use connection date as `lastModifiedDate`.
> Fix: connection list ordering issue after accepting connection

- Resources/zmessaging.xcdatamodeld/zmessaging2.30.0.xcdatamodel/contents
- Source/Model/Conversation/Member.swift
- Source/Model/Conversation/Permissions.swift
- Source/Model/Conversation/Team+Transport.swift
- Source/Model/Conversation/Team.swift
- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser.m
- WireDataModel.xcodeproj/project.pbxproj
* Add `creator` relation (inverse `createdTeams`) to `Team` entity. 
* Add methods to create or update teams and members from transport data.
> Add creator and flag specifying if members need redownload

- Source/Model/Conversation/Permissions.swift
- Source/Model/Conversation/Team.swift
- Tests/Source/Model/TeamTests.swift
* Introduce enum for transport string representation of `Permissions` `OptionSet`.
* This might be a good time to get started using [Sourcery](https://github.com/krzysztofzablocki/Sourcery) in the project…
> Introduce enum for transport string representation of Permissions

- Resources/zmessaging.xcdatamodeld/zmessaging2.30.0.xcdatamodel/contents
- Source/Model/Conversation/ZMConversation+Transport.m
- Source/Model/Conversation/ZMConversation.m
- Source/Public/ZMConversation.h
- Tests/Source/Model/Conversation/ZMConversationTests+Teams.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
* Add `managed` attribute to `ZMConversation`, indicating if a team conversation is managed or not.
* Update team payload parsing from conversation transport data.
* Create new team conversation if existing one has a user defined name.
> Update conversation creation rules and transport data parsing

- Resources/zmessaging.xcdatamodeld/zmessaging2.30.0.xcdatamodel/contents
- Source/Model/Conversation/Member.swift
- Source/Model/Conversation/Permissions.swift
- Source/Model/Conversation/Team+Transport.swift
- Source/Model/Conversation/Team.swift
- Source/Model/Conversation/ZMConversation+Transport.m
- Tests/Source/Model/Conversation/ZMConversationTests+Teams.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
- Tests/Source/Model/PermissionsTests.swift
- Tests/Source/Model/TeamTests.swift
* Add team `pictureId` and `pictureKey` fields to model schema for consistency.
* Refetch team when receiving when getting it through a conversation update (see the comment).
> Correct picture keys

- Resources/zmessaging.xcdatamodeld/zmessaging2.30.0.xcdatamodel/contents
- Tests/Source/Model/TeamDeletionRuleTests.swift
* The deletion rule from the `Member` entity to its `User` was set to `Cascade` instead of `Nullify`, resulting in the deletion of a members user once the member gets deleted.
> Fix member entity relationship deletion rules

- Source/Model/User/ZMUser+Teams.swift
- Source/Notifications/DependencyKeyStore.swift
- Source/Notifications/NotificationDispatcher.swift
- Source/Notifications/ObjectObserverTokens/ObjectChangeInfo.swift
- Source/Notifications/ObjectObserverTokens/TeamChangeInfo.swift
- Source/Notifications/ObjectObserverTokens/UserChangeInfo.swift
- Tests/Source/Helper/NotificationObservers.swift
- Tests/Source/Model/Observer/ConversationObserverTests.swift
- Tests/Source/Model/Observer/MessageObserverTests.swift
- Tests/Source/Model/Observer/NotificationDispatcherTests.swift
- Tests/Source/Model/Observer/ObjectObserverToken/TeamObserverTests.swift
- Tests/Source/Model/Observer/UserClientObserverTests.swift
- Tests/Source/Model/Observer/UserObserverTests.swift
- WireDataModel.xcodeproj/project.pbxproj
Team changes (members added / removed, name change) can be observed by registering as a `TeamObserver`.
Team insertions and deleted can be observed by registering an observer on the selfUser. Insertion & deletions should cause a `UserChangeInfo` with `teamsChanged` set to true.
I also cleaned up the observer tests a bit because we had different methods doing the same thing but being more or less reliable at doing that :-/
> Add observation for teams

- Resources/zmessaging.xcdatamodeld/zmessaging2.30.0.xcdatamodel/contents
- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation+Transport.m
- Source/Model/Conversation/ZMConversation.m
- Source/Model/User/ZMUser+Teams.swift
- Tests/Source/Model/BaseTeamTests.swift
- Tests/Source/Model/ZMConversation+TeamsTests.swift
- WireDataModel.xcodeproj/project.pbxproj
* We need to know if the self user is a guest in a conversation.
* We now set the `teamRemoteIdentifier` on the conversation in addition to setting the `team` relation, this is needed as we will delete the team when we receive a `403` from the backend when fetching `/teams/{id}` for said team but are only a guest. In this case we will now nil the relation but keep the id to know that we are only a guest.
> Add logic to check if the self user is guest in a conversation

- Resources/zmessaging.xcdatamodeld/zmessaging2.30.0.xcdatamodel/contents
- Source/Model/Conversation/ZMConversation+Transport.m
- Source/Model/Conversation/ZMConversation.m
- Source/Public/ZMConversation.h
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
- Tests/Source/Model/ZMConversation+TeamsTests.swift
* In contrast to the initial believe the backend response when fetching a conversation does not include an object for the `team` field, but only the teamId.
* There is no migration for removing the `managed` field, clients build with dependencies pinned to the `smb` branches will lose history.
> Remove conversation transport team object in favour of team id entry

- Source/ConversationList/ZMConversationListDirectory.m
- Source/Model/Conversation/ZMConversation+Predicates.swift
- Tests/Source/Model/ConversationList/ZMConversationListDirectoryTests+Teams.swift
* We don't want to show pending connection request in the team conversation list.
> Don't return connection requests in a team conversation list

- Source/Model/Conversation/Team.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/TeamTests.swift
Also selfUser was created twice in the `ZMConversationTestsBase`
> Exclude self user from team member search

- Source/ConversationList/ZMConversationList+Internal.h
- Source/ConversationList/ZMConversationList.m
- Source/ConversationList/ZMConversationListDirectory.m
* The `debugDescription` was also used as a unique identifier. We now append the team Id if we have any.
> Fix non-unique conversation list identifiers

- Source/ConversationList/ZMConversationList+Internal.h
- Source/ConversationList/ZMConversationList.m
- Source/ConversationList/ZMConversationListDirectory.m
- Source/Public/ZMConversationList.h
- Tests/Source/Model/ConversationList/ZMConversationListTests+Teams.swift
- Tests/Source/Model/Observer/ConversationListObserverTests.swift
#What's in this PR?
* The archived conversation list did not have a unique identifier for each team, which made observing archived team conversation fail.
* We now inject the team into the conversation list initializer and append its `remoteIdentifier` to the identifier if the team is nonnull.
* I was thinking of just creating a new `UUID` inside `ZMConversationList` to decouple the list from teams, but using the same identifier as the team makes debugging a lot easier.
> Move conversation list identifier creation into ZMConversationList

- Resources/zmessaging.xcdatamodeld/zmessaging2.30.0.xcdatamodel/contents
- Tests/Source/Model/TeamDeletionRuleTests.swift
* Change the deletion rule from `Team` to its conversations to no longer cascade but instead nullify.
* I did not add a new model schema, but a migration should not be required when only changing a deletion rule.
> Don't cascade a team deletion to its conversations

- Source/Model/User/ZMUser+Teams.swift
- Source/Notifications/ConversationListObserverCenter.swift
- Tests/Source/Model/TeamTests.swift
- Tests/Source/Model/ZMConversation+TeamsTests.swift
* Fix and move canAddUsers check into data model, add tests.
* The check is currently in the UI project in an extension on `ZMUser`, but makes more sense to be in `wire-ios-data-model`, also the check didn't take the result of `isGuest(in:)` into account.
> Fix and move canAddUsers check into data model

- Source/Model/Conversation/ZMConversation+Transport.h
- Source/Model/Conversation/ZMConversation+Transport.m
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
- Tests/Source/Model/Conversation/ZMConversationTests+participants.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/ZMConversation+TeamsTests.swift
* The backend does no longer return the correct date in the conversation payload (`last_event_time`), which we used to update the `lastModifiedDate` when a conversation is created with us.
* This adds an additional parameter  to the update method to inject the timestamp from the update event.
> Inject serverTimeStamp into conversation transport update method

- Source/Model/Conversation/ZMConversation+Transport.m
The bug as I see it:
1. App is offline.
2. Someone adds you to the team (A) and to the team conversation (B).
3. When A happens, we create Team and mark it to be fetched.
4. We see the event B and reset the needs to be fetched flag to false.
> Check if team is already needs to be updated from BE

- Source/Model/Conversation/Team.swift
- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser.m
- Source/Model/User/ZMUser.swift
- Tests/Source/Model/TeamTests.swift
- Tests/Source/Model/User/ZMUserTests.swift
It seems that local search by user handle was not working, it was searching only by `normalizedName`. Updated predicates to handle this situation and re-using it in team members search.
> Enable search by user handle

- Source/Notifications/SnapshotCenter.swift
- Tests/Source/Model/Observer/ConversationListObserverTests.swift
- Tests/Source/Model/Observer/SnapshotCenterTests.swift
* Add a separate dictionary to `Snapshot` to store the presence of to-one relations.
When a user is added to a team conversation as a guest, the following sequence of events is happening:
1. We receive the event for adding the conversation.
2. We create the conversation from the payload, which contains the `team_id`.
3. We create the team locally and mark it for fetching.
→ The conversation is not yet shown in the general conversation list, since it has a team.
4. We fetch the team and receive a 403 indicating that the access is forbidden.
5. We delete the team.
6. CoreData is sending a save notification in which the conversation is faulted, and our snapshot does not contain the information about the one-to-one relation `team` on the conversation, so we are ignoring the change.
7. The …
> Respect to one relationships in core date snapshots

- Source/Model/Conversation/Team.swift
There was a discussion in  #283 to convert slightly esoteric `ANY foo == bar` predicate into simple `{foo} IN {bar}`. However it doesn't seem to work on device, but the tests pass in both cases. I assume this is because in-memory CoreData store works slightly differently regarding relationships.
> IN clause in a subquery seems to not do what it should

- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
We want to consider team group conversations with only 2 participants to be one-to-one. This means supporting the same features (delivery recipes, video calling) and design.
see: https://github.com/wireapp/architecture/blob/master/teams/clients.md#one-to-one-conversation-inside-teams
> Consider team group conversations with one participant 1-to-1

- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
UI was depending on `connectedUser` only being set for one-to-one conversations.
> Don't return a connected user for a group conversation with only 2 participants

- Source/Model/User/ZMRegistrationUser.m
- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser.m
- Source/Model/User/ZMUser.swift
- Source/Public/ZMEditableUser.h
- Tests/Source/Model/User/ZMUserTests.m
Cleaned up as much code as I could find. There is one property (`originalProfileImageData`) that got deleted from CoreData, so ideally we could do only one new data model version together with #288.
Maybe I missed some code somewhere, would be glad to delete even more!
> Remove v2 profile picture upload

- Source/Notifications/ManagedObjectObserver.swift
- Tests/Source/ManagedObjectContext/ManagedObjectContextChangeObserverTests.swift
- WireDataModel.xcodeproj/project.pbxproj
Add a lightweight managed object context observer `ManagedObjectContextChangeObserver`, which should be used when in the background. For example, when replying to a message from a push notification we want to observe the delivery state of the sent message. If the send operation fails we want to present a "Failed to send message" notification to the user. As our custom observer system is not active while the application is in the background and would be quite expensive to start just for observing one message (due to the snapshot creation), the added observer can be used to get notified when objects in a specified context change.
> Add lightweight managed object context change observer

- Source/Model/Conversation/ZMConversation+Transport.m
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
- Tests/Source/Model/ZMConversation+TeamsTests.swift
* Do not insert local team when updating a conversation.
> Do not insert local team when updating a conversation

- Gemfile.lock
- Resources/zmessaging.xcdatamodeld/.xccurrentversion
- Resources/zmessaging.xcdatamodeld/zmessaging2.39.0.xcdatamodel/contents
- Source/Model/Conversation/Member+Patches.swift
- Source/Model/Conversation/Member.swift
- Source/Model/Conversation/ZMConversation+Transport.m
- Source/Model/User/ZMUser.m
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
- Tests/Source/Model/MemberTests.swift
- Tests/Source/Model/User/ZMUserTests.m
- Tests/Source/Model/ZMConversation+TeamsTests.swift
- Tests/Source/Utils/PersistedDataPatchesTests.swift
- WireDataModel.xcodeproj/project.pbxproj
* Add needsToBeUpdatedFromBackend and add persistent data patch migrating identifiers
* Add `needsToBeUpdatedFromBackend` flag to `Member` entity.
* Add `PersistedDataPatch` to set a members users `remoteIdentifier` as the `remoteIdentifier` of the member itself as well.
> Set a members users remoteIdentifier on the member itself

- Source/Model/Message/ZMOTRMessage+ConfirmationThreshold.swift
- Source/Model/Message/ZMOTRMessage.m
- Tests/Source/Model/Messages/BaseClientMessageTests.swift
- Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
- WireDataModel.xcodeproj/project.pbxproj
* Only send delivery receipts for messages received in the last 7 days.
* The exact value of this threshold is still under discussion.
> Only send delivery receipts for messages received in the last 7 days

- Source/Model/User/ZMUser+Teams.swift
- Tests/Source/Model/TeamTests.swift
There can't be guests in accounts without a team, but we were showing all other users as guests in conversations in that case. This adds a check whether there is a team or not before checking if the user is a member of said team.
> Stop considering users in account without team as guests

- Source/Model/User/ZMUser.swift
* We were not using the normalised query string when the user entered a query string with a leading @ symbol. In case the user searched for a username and started uppercase no results were found.
> Fix not using normalised query string when stripping leading at sign

- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Conversation/ZMConversationTests+messages.m
* Do not update `lastModifiedDate` for leave and rename update events.
> Do not update lastModifiedDate for leave and rename update events

- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
We wouldn't delete an email or phone from a `user.update` event. This will happen if you have two devices and delete your email, the second device will then receive a `user.update` event setting the `email` field to nil.
> Fix removing email or phone via user update

- Source/Model/Conversation/ZMConversation+Ephemeral.swift
- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests+Ephemeral.swift
- Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift
- Tests/Source/Model/TextSearchQueryTests.swift
When sending the message to group conversation without the participants the sending is not possible, since there are no receivers (ephemeral is not sent to your own devices).
Appending the message is failing in such conversations.
> Do not allow sending the ephemeral message to the empty conversation

- Source/Model/AccountManager.swift
- Source/Model/AccountStore.swift
- Tests/Source/Model/AccountManagerTests.swift
- Tests/Source/Model/AccountStoreTests.swift
* Add functions to delete persisted accounts, which will mostly be used to clean up after tests.
> Add functions to delete persisted accounts

- Source/Model/AccountManager.swift
- Tests/Source/Model/AccountManagerTests.swift
Add convenience method to add and immediately select an account. This method internally calls `add` and `select` which means `updateAccounts` will be called twice which is unnecessary and could be optimised. However I would be very surprised if this becomes an performance issue.
> Add convenience method to add and immediately select an account

- Source/Model/User/ZMUser.m
- Source/Model/UserClient/UserClient.swift
- Source/Public/ZMUser+OneOnOne.h
- Tests/Source/Model/Conversation/ZMConversationTests+Teams.swift
- Tests/Source/Model/User/ZMUserTests.m
- Tests/Source/Model/UserClient/UserClientTests.swift
Change the logic to only create fake one-to-one conversations if a user is member of your team. Also since an account can now only have one team there's no need to pass in the team when requesting a one-to-one conversation.
https://wearezeta.atlassian.net/browse/ZIOS-8810
> Don't create fake one-to-one conversations for connected users

- Source/ManagedObjectContext/NSManagedObjectContext+TearDown.swift
- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.h
- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m
We were running into an assertion during the context teardown, as the information about the context type was already lost.
We now ensure this is the last information we remove from the context `userInfo`.
> Fix crash during context teardown

- Source/ManagedObjectContext/NSManagedObjectContext+TearDown.swift
There were cases in which tests checked the context type after the context has been torn down. This should not happen, as no test should be running anymore and thus means some tests are not properly torn down or some asynchronous operations do not use the proper dispatch groups, but this also crashes the test suit, which is why we now keep the context type information present.
> Do not remove context type keys at all

- Source/ManagedObjectContext/StorageStack.swift
- Tests/Source/ManagedObjectContext/Migrations/DatabaseBaseTest.m
- Tests/Source/ManagedObjectContext/Migrations/DatabaseMovingTests.m
The initial implementation had method for creating store with optional user id parameter. This was split into two methods to be more explicit.
> Updated storage stack API when creating without user ID

- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
If user creates team conversation with 2+ participants and gives it a name, then removes all but one participants, the conversation used to convert to 1-1.
> Do not consider team named groups as 1-1

- Source/ManagedObjectContext/StorageStack.swift
- Tests/Source/ManagedObjectContext/StorageStackTests.swift
* Fix broken lookup for existing `.inMemory` `ManagedObjectContextDirectory`. Using a dictionary of type `[String: ManagedObjectContextDirectory]` fixes the issue, somehow using a different `URL` instance with the same path does not work in a dictionary (I assume it uses a reference type / `NSURL` internally and does not provide a `hash` only based on its path).
**I am failing to reproduce this issue in a Playground, but added a regression test which is failing without the changes made in this PR.**
> Use String as context directory map key to fix lookup

- Source/ManagedObjectContext/NSPersistentStoreCoordinator+Wire.swift
- Source/ManagedObjectContext/PersistentStoreRelocator.swift
- Source/ManagedObjectContext/StorageStack.swift
In SyncEngine we have another CoreData stack for storing events. We need to migrate it to support multi accounts, but `PersistentStoreRelocator` was made to work only for main store. This PR moves all main store specific information into `MainPersistentStoreRelocator` while making the original one simpler.
> Making PersistentStoreRelocator more useful

- Source/Model/User/ZMUser.m
- Source/Public/ZMUser.h
- Source/WireDataModel.h
- Tests/Source/Model/ZMTestSession.h
- Tests/Source/Model/ZMTestSession.m
- WireDataModel.xcodeproj/project.pbxproj
We use it both in UI and RequestStrategy, so for now we should keep it available for consumers.
> Adding test session to public interface

- Source/ManagedObjectContext/PersistentStoreRelocator.swift
- Tests/Source/ManagedObjectContext/DatabaseBaseTest.swift
- Tests/Source/ManagedObjectContext/StorageStackTests.swift
The `MainPersistentStoreRelocator ` assumed we stored the database in `{AppGroup-Directory}/store.wiredatabase` at some point, whereas the correct location is  `{AppGroup-Directory}/{Bundle-ID}/store.wiredatabase`.
> Fix using the wrong legacy database location

- Source/ManagedObjectContext/PersistentStoreRelocator.swift
- Source/Utilis/CryptoBox.swift
- Tests/Source/ManagedObjectContext/DatabaseBaseTest.swift
- Tests/Source/ManagedObjectContext/StorageStackTests.swift
Fix using wrong legacy otr directory when migrating keystore. Similar to (and also introduced by) https://github.com/wireapp/wire-ios-data-model/pull/346. We were reusing the same possible legacy directory locations as used when migrating the database, but the keystone was stored in a different folder.
> Fix using wrong legacy otr directory when migrating keystore

- Source/Notifications/NotificationDispatcher.swift
- Tests/Source/Model/Observer/NotificationDispatcherTests.swift
CoreData has a concept of “Uniquing” which prevents creation of multiple NSManagedObject instances pointing to the same underlying CoreData record, but it does not guarantee the same behavior for faulted objects. When the last reference to the faulted object dissapears CoreData is free to re-create the object again when needed. This poses a problem when used together with NotificationCenter because it captures the “sender” object weakly. If the sender gets deallocated the notification is not delivered to the subscriber.
To work around this issue we keep a strong reference to the object until the token is alive.
> Fix: notification for change is not fired in certain cases

- Source/ManagedObjectContext/ManagedObjectContextDirectory.swift
We hit a roadblock when trying to get tests passing with the leaks checking on. It seems that UI context gets released only when the autorelease pool is drained. Unfortunately this happens after the test suite itself is finished and we couldn't find a way to trigger this earlier.
To work around failing tests we do not track UI context in the leaks debugger anymore.
> Relax memory leak constraints

- Source/Model/Account.swift
- Atomic write is OK from apple side for small documents async read / write
See section "Building Your Content in Memory and Writing It to Disk All at Once":
https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/TechniquesforReadingandWritingCustomFiles/TechniquesforReadingandWritingCustomFiles.html
> Use atomic write to store to avoid potential data corruption with share extension

- Source/ManagedObjectContext/NSPersistentStoreCoordinator+Wire.swift
- Source/ManagedObjectContext/PersistentStorageInitialization.swift
- Source/ManagedObjectContext/PersistentStoreRelocator.swift
- Source/ManagedObjectContext/StorageStack.swift
- Source/Model/Conversation/SharedObjectStore.swift
- Source/Utilis/CryptoBox.swift
- Tests/Source/ManagedObjectContext/DatabaseBaseTest.swift
- Tests/Source/ManagedObjectContext/StorageStackTests.swift
- Tests/Source/Model/Conversation/SharedObjectStoreTests.swift
- Tests/Source/Model/Messages/OtrBaseTest.swift
- Tests/Source/Model/UserClient/UserClientKeyStoreTests.swift
The various data we persist for an account is scattered in different folders so
we decided we need clean it up and put everything inside one folder per account.
We store our data in a shared container. A shared container has the same structure
as the main bundle container. We want keep all the account related data in a folder
named by the account-id (UUID) so that it's easy to delete.
```
Accounts/
<UUID>                    -- JSON file storing basic account information
...
AccountData/
<UUID>/
otr/                  -- folder containing cryptobox sessions
store/                -- persistence store for messages etc.
events/               -- persistence store for unprocessed events
drafts/               -- persistence store for message drafts
sharedObjectStore     -- booking keeping to sync …
```
> Re-organize folder structure

- Source/Model/Account.swift
- Source/Model/AccountManager.swift
- Tests/Source/Model/AccountManagerTests.swift
- We want to store the unread conversations count per account and fire a notification when this value changes, so that the UI can respond.
- Each time the `AccountManager` updates the accounts, new `Account` objects were being instantiated and stored in the `accounts` array. That means that the address of the account objects were changing, even if the accounts remained unchanged semantically. This create problems when sending and receiving notifications tied to a specific object. Consequently, we **should not** recreate new `Account` objects to replace the existing corresponding objects in the `accounts` array, but rather update the properties of these existing account objects. As a result, any loaded account will always maintain the same address.
> store unread conversation account

- Source/Model/Message/ConversationMessage+Deletion.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
Adding a link when editing a message will always create a link preview, even if the settings disable them
Adding the option to fetch link previews when editing a `ZMMessage`.
> add option to fetch link preview when editing message

- Source/Utilis/Protos/ZMGenericMessage+Obfuscation.swift
- Tests/Source/Model/Utils/GenericMessageTests+Obfuscation.swift
Also exposes `String.obfuscated()`
> Additional test to verify that it obfuscates the emoji and Russian text

- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser.m
- Source/Model/User/ZMUser.swift
- Source/Public/ZMUser.h
- Source/Utilis/DuplicatedEntityRemoval.swift
- Source/Utilis/PersistedDataPatches+Directory.swift
- Tests/Source/Utils/DiskDatabaseTests.swift
- Tests/Source/Utils/DuplicateEntityRemovalTests.swift
- Tests/Source/Utils/DuplicatedEntityRemovalTests.swift
- WireDataModel.xcodeproj/project.pbxproj
Normalize database by removing duplicate entries at initialization.
> Normalize database by removing duplicates

- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m
- Source/Model/Conversation/ZMConversation+DisplayName.swift
- Tests/Source/Model/User/DisplayNameGeneratorTests.swift
Allow the `DisplayNameGenerator` to be used on the sync context. This is used when building local notifications in Sync Engine.
Provide a way to query for a *meaningful* display name. Previously, we would first try to construct a conversation display name by using only existing data. In the case that still no name could be generated (due to missing information), a fallback placeholder name is return, such as "..." or "Empty group conversation". When configuring the title text for a local notification, we would rather not show a title if there is no meaningful name, rather than one of these placeholders. Now it is possible to know if a meaningful name exists.
Note, the conversation's `displayName` simply returns the `meaningfulDisplayName` if it exists, otherwise it falls back to the …
> Conversation Display Name

- Source/Model/Message/ZMMessage.m
Clean up ZMSystemMessage. No logical changes.
---
When a user changes a conversation name or add/remove a participant we currently will insert
two system message for this event. This happens because the change event arrives twice, first
in the response of POST response and second in the notification stream.
Add a check before inserting these system messages for if the change has already been applied.
> Fix for double system message

- Source/Model/Message/ZMMessage.m
This check was preventing system messages being created for first time self member join events, b/c the brand new conversation has not had it’s `conversationType` set to `group` yet, and it defaults to `invalid`. Thus we were returning nil. 
However, in the first line of the method we already do event type checking (only `memberJoin`, `memberLeave`, `conversationRename` and `connectRequest` are permitted), so most of these removed checks are unneccessary. Having said that, we are assuming/expecting that the conversation referenced on the Backend actually is a group conversation.
> remove unneccessary check

- Source/Model/Connection/ZMConnection.m
- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation+Transport.m
- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
- Tests/Source/Model/Conversation/ZMConversationTests+participants.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/ZMConnectionTests.m
- Tests/Source/Model/ZMConversation+TeamsTests.swift
Remove all usage of the following fields: 
remove `status`, `status_ref`,` status_time` from the self member object
remove `status` from the other member object (it is always 0)
remove `last_event` and `last_event_time` from the conversationMeta
in addition to that the following fields has also been removed:
`archived`, `clearedEventID`, `muted`, `mutedTime`, `lastRead`
After removing these fields the following changes were necessary:
* remove/add participants based if they are part of participants list instead of checking the `status` flag.
* Set default `lastModifiedDate` and `lastServerTimestamp` when creating conversations since we will no longer set one when reading the `last_event_time`.
> Remove usage of depreciated BE fields

- Source/Utilis/ZMMessageTimer.h
- Source/Utilis/ZMMessageTimer.m
- Tests/Source/Model/Messages/ZMMessageTimerTests.swift
- WireDataModel.xcodeproj/project.pbxproj
We were not receiving APNS notifications for a failed message.
When sending a message, a `MessageExpirationTimer` (defined in `WireMessageStrategy` and a subclass of `ZMMessageTimer`) is started and if it fires, `LocalNotificationDispatcher` is alerted to generate the APNS notification. However, if the app is backgrounded while the timer is running, it would only fire the next the app is foregrounded because the timer doesn't run as a background task.
Run the timer as a background task, and end the activity once the completion handler is finished, or the timer is stopped or torn down.
`ZMMessageTimer` is actually not a single timer object, but rather a collection of concurrent timers. Thus we wish to run *each individual timer* in its own background task, to avoid other timers interfering …
> Wrap timer inside background activity

- Source/ManagedObjectContext/PersistentStoreRelocator.swift
- Tests/Source/ManagedObjectContext/DatabaseBaseTest.swift
When sharing a content from a team account via Share Extension, `NotSignedInViewController` was shown. This was reported only in few cases and only with internal builds.
I compiled the internal build with Xcode and loaded into @vytis phone. I discovered that the sharing session was stopped at:
https://github.com/wireapp/wire-ios-share-engine/blob/4ea5131a6ae17be232ff66e83d68af6abe512ba3/Sources/SharingSession.swift#L236
Going more deeper, I found that `possibleLegacyAccountFolders(applicationContainer: accountIdentifier:)` was fetching the `Bundle.main.bundleIdentifier` to compose the path of legacy folders. The problem in this case was that bundle identifiers are different between the main app and the Share Extension. In fact, this was the result of: …
> Fix ZIOS-9173: Share extension thinks that we need to login

- Source/Model/AccountManager.swift
We're posting a notification when the `AccountManager` has finished updating the accounts because it's useful for the new landing page in the UI. If we access the landing page from the settings screen, we may wish to cancel and go back to the authenticated account. In order to get the most updated state of the accounts, the UI needs to check the `AccountManager` at the right time.
> notify when accounts updated

- Source/Model/Conversation/ZMConversation.m
I'm adding debug logs to investigate a bug were group participants are involuntarily removed.
> Add debug logs when we modify the otherActiveParticipants

- Source/Model/Message/ZMAssetClientMessage+GenericMessage.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
If a remote user cancels a file upload the receiver will be stuck with placeholder message which never goes away.
The desired behaviour is that a cancelled upload gets deleted and gets re-inserted at the bottom if the sender decides to resume the upload.
We delete the message if get a `.cancelled` update. Due to a race condition with preview image downloader we need to guard against a zombie message, because accessing the `genericAssetMessage` property on a deleted  object will trigger a force unwrap.
I also changed the behaviour when a file message is canceled after it was uploaded. Previously we would mark it as canceled now we ignore it.
> Delete asset messages if they are cancelled

- Source/Model/User/ZMUser+Availability.swift
- Source/Model/User/ZMUser.swift
- Tests/Source/Model/User/ZMUserTests.swift
Some users could not set their status because they didn't include all required clients as recipeints
The `predicateForConnectedNonBotUsers` were also filtering out users without a handle.
Only filter based on connection status
> Fix not sending availability update to users without a handle

- Source/Model/User/ZMUser+Availability.swift
Changed order of statuses - swapped Away with Busy. The new order, which will also appear in the UIActionSheet, is: None, Available, Busy, Away.
> Changed order of statuses - swapped Away with Busy

- Source/Model/Message/ZMAssetClientMessage+GenericMessage.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
When sending a file and canceling it the receiver would see it as uploaded.
When canceling a file message we add a `NotUploaded.CANCELLED` state but it will also include a `uploaded: ZMAssetRemoteData` which was added when when the sender started to upload the file. This would cause the current logic to think that the file was uploaded when it was canceled.
This together with the fact we ignore a file cancellation if the file has been marked as uploaded was causing us to always ignore file cancellations.
Only consider a file as uploaded if the `uploaded: ZMAssetRemoteData` contains a `assetId.
> We were marking files as uploaded when they were canceled

- Source/ConversationList/ZMConversationListDirectory.m
- Tests/Source/Model/ConversationList/ZMConversationListDirectoryTests.m
For some reason the `clearedConversations` list was missing from the list of conversation lists. Possible consequence: the list was not updated after the app went to the background, so it was not possible to find the conversation.
> Added clearedConversations to list of conversation lists

- Source/Model/Message/ZMAssetClientMessage+GenericMessage.swift
- Source/Model/Message/ZMClientMessage.m
- Source/Model/Message/ZMOTRMessage.h
- Source/Model/Message/ZMOTRMessage.m
- Tests/Source/Model/Messages/ZMAssetClientMessageTests+Ephemeral.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessageTests.m
It was theoretically possible to edit your own message without having the `edit` icon appear. 
We were applying all updates to messages when actually the only valid update is if a link preview is added later.
Enforce that we only allow updates if the link preview changes.
> Only allow update to client message if they contain a link preview update

- Source/Model/Account.swift
- Tests/Source/Model/AccountStoreTests.swift
- Tests/Source/Model/AccountTests.swift
The `imageData` field of the `Account` object is actually designed to contain the avatar of a personal account, or an eventual image of a team account (which actually is nil).
This is causing the `SkeletonViewController` to show a grey screen while switching from personal to team account.
I've added a new field to the `Account` class, `teamImageData`. In this way, `imageData` always contains the personal avatar for both personal and team accounts, and `teamImageData` could contain a team avatar in the future - so we have a more consistent behavior. 
Needs releases with:
Issue linked to the ticket 8936.
> Split imageData logic into personal and team avatars

- Source/Model/Conversation/ZMConversationMessageWindow.m
App enters a crash loop after clearing/deleting a conversation.
When filtering out the visible messages in a conversation after clearing it we query the `delivered` property to show any pending messages. This was previously only done for `ClientMessage` since we also checked if the message was encrypted. After removing the `isEncrypted` flag we also query this on `SystemMessage` which doesn't have `delivered` property in core data, this results in a crash.
Do the filter with a block instead where we can access the `deliveryStatus` property.
> Fix crash on accessing not existing delivered key on SystemMessage

- Source/Model/Conversation/ZMConversation+UnreadCount.h
- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ConversationMessage.swift
- Source/Public/ZMConversation.h
- Tests/Source/Model/Conversation/ZMConversationTests.m
This feature is useful to mark some conversation as the one requiring attention when you already finished reading it or marking a non-important conversation as read.
Not every conversation can be marked as unread, since it must contain at least one message with the timestamp.
- Verify syncing of updated timestamps.
> Mark conversation as read or unread

- Source/Model/User/DisplayNameGenerator.swift
- Tests/Source/Model/User/DisplayNameGeneratorTests.swift
We did not refresh the display name map when a user name becomes available, this can be an issue when a non-local user is added to a conversation as it might not have been fetched yet when the display name map is populated. 
This PR adds a check whether the stored name is empty and the user name is not and will discard and recalculate the user name map in that case.
> Recalculate displayName map when a name becomes available

- Source/Model/User/ServiceUser.swift
- Source/Model/User/ZMSearchUser+Internal.h
- Source/Model/User/ZMSearchUser+ServiceUser.swift
- Source/Model/User/ZMSearchUser.m
- Source/Public/ZMSearchUser.h
- Tests/Source/Model/User/ZMSearchUserPayloadParsingTests.swift
The backend introduced the new property of the integration: summary. It is a string that summarizes the functionality of the service.
> Parse and return the summary of the integration

- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
The group conversation with the bot in the team appears as 1-1.
Currently Wire sees the group conversation with 1 user without the name in the team as a 1-1 conversation. This mode is suboptimal for the conversations with bots, since then it is not possible to add the new member to the group with only a bot. This is useful when user would like to pre-configure the bot.
The exception case was added.
> Treat the group conversation with bot as group

- Source/Model/Conversation/Team.swift
- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation.m
- Source/Public/ZMConversation.h
- Tests/Source/Model/Conversation/ZMConversationTests+CreationSystemMessages.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Teams.swift
- Tests/Source/Model/TeamTests.swift
- WireDataModel.xcodeproj/project.pbxproj
In the new conversation creation flow we have name at the point of creation. We need an API for this.
Added conversation creation method that takes a name parameter. It is currently optional, bet at a later point we should clean up the API and remove the ability to create conversation without name.
> Conversation creation with name

- Source/Model/Conversation/ZMConversation.m
- Source/Model/ZMManagedObject+Internal.h
- Source/Model/ZMManagedObject.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
* Add method to filter modified keys while ensuring they are only set once in the super class.
* Before it was not possible to remove keys that have been added by `ZMManagedObject` in `updateKeysThatHaveLocalModifications`, as setting them would result in a save, which in turn would result in a recalculation which will trigger `updateKeysThatHaveLocalModifications` being called again, leaving the object in a dirty state.
* This PR adds a separate method that subclasses can override to filter the modified keys to be set by the super class, this way the object will not be changed again.
> Add option to filter modified keys

- Source/Model/Conversation/ConversationCreationOptions.swift
Using the new Swift API is not that simple, since all the values for the conversation creation options should be passed in.
Set the default values and let user change them.
> Added default values for the conversation creation options

- Source/Model/Conversation/ZMConversation+AccessMode.swift
In SE it's necessary to determine the needed access role and mode for updating it.
> Public API to fetch correct access mode / role for allow guests

- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
- Source/Public/ZMMessage.h
- Tests/Source/ManagedObjectContext/ManagedObjectContextChangeObserverTests.swift
- Tests/Source/Model/Messages/ZMMessageTests.m
- Tests/Source/Model/Utils/MessageCountTrackerTests.swift
Some system messages have sender and users array containing the same user. We need to easily check for this in UI.
Add a property to ZMSystemMessage that is true when users array contains only single user and it's the same as sender
> Added user is sender flag

- Source/Model/Conversation/ZMConversation+AccessMode.swift
- Tests/Source/Model/Conversation/ZMConversationTests+AccessMode.swift
The conversations that were created earlier have a `"access": ["invite"]` and were treated as not allowing guests which is not correct.
Relaxed the meaning of the flag to be false when it's team-only conversation and true otherwise.
> allowGuests now means that either type of guests are allowed

- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
* Check if a user is wireless in `-canBeConnected` to ensure elements on the UI side checking this flag are updated correctly.
> Check if a user is wireless in `-canBeConnected`

- Tests/Source/ManagedObjectContext/DatabaseMigrationTests.swift
The CoreData requires the version's identifier to be updated when the new version is created.
> Added test for CoreData model identifier matching

- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ConversationMessage.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMMessageTests.m
- Added the method to check if the message can be considered unread. The messages sent by the current user cannot be marked as read.
> Allow marking message as unread, improved conversation unread

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.m
We show the devices of wireless users (unlikely to regular non-connected users), therefore it is possible to verify the fingerprints of those users. However the fingerprint verification does not make the conversation verified.
In the code we where discarding the non-connected users, since it was not possible to verify their fingerprints.
I've added an extra case for the wireless users in the conversation verification.
> Consider wireless user verification

- Source/ManagedObjectContext/BackupMetadata.swift
- Tests/Source/ManagedObjectContext/BackupMetadataTests.swift
* Remove client identifier from backup metadata.
> Remove client identifier from backup metadata

- Source/ManagedObjectContext/NSPersistentStoreCoordinator+Wire.swift
- Source/ManagedObjectContext/StorageStack+Backup.swift
- Tests/Source/ManagedObjectContext/StorageStackBackupTests.swift
- WireDataModel.xcodeproj/project.pbxproj
We would like to implement backing up the information inside CoreData database.
To minimize disruption and potentially corrupting the backup by simply copying file we try to work on CoreData layer:
1. Create a fresh `NSPersistentStore` that points to the database that we want to export
2. Try to migrate the persistent store to another location inside temporary directory. This will dump all data to a new location and invalidate the store created in step 1. We don't care about it because it's created for this purpose, all other persistent stores should not be affected.
> Add database backup methods

- Source/ManagedObjectContext/StorageStack+Backup.swift
- Tests/Source/ManagedObjectContext/StorageStackBackupTests.swift
Adds a method to StorageStack for importing a database from a backup.
This method assumes the backup directory passed in contains a uncompressed and decrypted backup.
> Add method to import local store from backup

- Source/ManagedObjectContext/NSManagedObjectContext+BackupImport.swift
- Source/ManagedObjectContext/StorageStack+Backup.swift
- Source/ManagedObjectContext/StorageStack.swift
- Source/Model/PersistentMetadataKeys.swift
- Tests/Source/ManagedObjectContext/StorageStackTests.swift
- Tests/Source/Model/ZMTestSession.m
We need to do some pre-processing after we import the database and it is good to be sure that we know when this is the case.
On export add a flag to persistent metadata to show that it is a backup
> Added a flag to exported database to show that it is a backup

- Source/ManagedObjectContext/BackupMetadata.swift
- Source/ManagedObjectContext/StorageStack+Backup.swift
- Tests/Source/ManagedObjectContext/BackupMetadataTests.swift
* Use data model schema version to verify metadata instead of app version.
> Use data model schema version to verify metadata instead of app version

- Source/Model/Account.swift
- Tests/Source/Model/AccountTests.swift
To decide if two `Account` objects are equal we compare all properties. We really care only about user identifier, because if team image changes it's still same account.
> Using only user identifier to decide if accounts are equal

- Source/ManagedObjectContext/StorageStack+Backup.swift
- Tests/Source/ManagedObjectContext/StorageStackBackupTests.swift
- Tests/Source/ManagedObjectContext/StorageStackTests.swift
When exporting the backup we set a flag on the store metadata showing that this is an exported database. It was not correctly set.
We have a bit of abstraction around `NSManagedContext` to work with persistent metadata and it gets saved only when using our `saveOrRollback` method. 
Updated the code to directly set metadata on the store.
> Fix backup export

- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMMessageTests.m
Client is crashing when syncing the notification stream.
The ephemeral message is already deleted when someone is trying to delete it again with the `delete` message type.
Check if message is already deleted.
> Do not crash when deleting ephemeral

- Source/Model/User/ZMSearchUser+Internal.h
- Source/Model/User/ZMUser+Internal.h
After integrating with SE it seems that some of the nullability annotations were not added correctly. 
`ZMUser.remoteIdentiefier` had to be left as `null_unspecified`, because in lots of places it's either force-unrwrapped or conditionally unwrapped. Will have to update in other PRs as the current priority is to finish Xcode 9.3 migration
> Updated nullability annotations

- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ZMClientMessage+Encryption.swift
- Source/Model/Message/ZMGenericMessage+Debug.swift
- Tests/Source/ManagedObjectContext/DatabaseBaseTest.swift
- WireDataModel.xcodeproj/project.pbxproj
For internal builds we allow users to send debug logs which may contain sensitive information.
Sanitize all messages from user generated content before writing them to the internal debug log.
> Sanitize generic messages for sensitive information when writing internal debug logs

- Source/Model/Message/ZMClientMessage+Encryption.swift
- Source/Model/User/ZMUser.swift
- Source/Model/UserClient/UserClient.swift
- Source/Notifications/ChangeCalculation/ChangedIndexes.swift
- Source/Notifications/ObjectObserverTokens/Helpers/KeySet.swift
- Added protocol `PrivateStringConvertible` to generate the object description that can be put into the log or the crash report.
- Use `privateDescription` when necessary.
> Do not put the private info into fatal()

- Source/Model/Conversation/ZMConversation+Ephemeral.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Ephemeral.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift
Adjust timed messages expiry time to 10 seconds, 5 minutes, 1 hour, 1 day, 1 week or 4 weeks.
> Feature: Adjust time values presets

- Source/Model/Conversation/ZMConversation+Mentions.swift
- Source/Model/Message/ZMClientMessage+Encryption.swift
- Source/Model/User/ServiceUser.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Mentions.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
We need to temporarily disable the filtering of messages, so they only go to the bots if the bots are mentioned.
Bool flag to control the messages behavior for that particular case is added.
> Allow sending the messages to bots without mention

- Source/Model/Conversation/ZMConversation+Ephemeral.swift
Reset both timer values when setting a nil timer value without having a previous one. Otherwise it's not possible to set a synced value, and then reset it to nil because we didn't reset the synced value in that case.
> Reset both timer values when setting a nil timer value without having a previous one

- Source/Model/Conversation/ZMConversation+Ephemeral.swift
1. Move the latest change for longStyleFormatter form wire-ios project to data-model
> Fix: copy date formatter updates & move MessageDestructionTimeoutValue's displayString from wire-ios

- Source/Model/Conversation/ZMConversation+Transport.m
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
We should set and read the timer as milliseconds. Another fix is coming for the SE.
> Correctly parse milisecond conversation timer

- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Conversation/ZMConversationTests+Messages.swift
* Don't update last modified date for message timer update system messages.
> Don't update last modified date for message timer update system messages

- Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
- Source/Utilis/MimeType.swift
- Tests/Source/Model/Utils/MimeTypeTests.swift
WebM is not supported by the iOS and also not known to the MIME type system. If user installs the player for WebM, for example VLC, then the format is recognized as video, but still cannot be played by the iOS integrated video player.
Manually exclude WebM from the list of the video formats.
> Do not consider WebM as the video format

- Source/ManagedObjectContext/StorageStack.swift
- Source/Model/UserClient/UserClient.swift
- Tests/Source/Model/ZMTestSession.m
* Tests using ZMTestSession were defaulting to on-disk storage, but it should be in memory. Initialising this flag got lost during a refactoring ~1 year ago.
* In tests a situation can happen that UserClient is not committed to the database and doesn't have permanentID yet, so all consecutive calls to `syncMOC.existingObject(with:)` will fail to return anything.
* Tearing down context directory a bit earlier.
> Test improvements

- Source/Model/Message/ConversationMessage+Deletion.swift
If the receiver deletes an ephemeral message, then the message is not deleted on the sender side and they are stuck with the obfuscated message.
When the deletion timer fires normally (on the receiver side), a call to `ZMMessage.deleteForEveryone(message:) is eventually invoked, which generates a delete message to be sent to participants in the client. This method name is misleading because in the case of ephemeral messages, we actually only delete for the self user and the original sender. See [here](https://github.com/wireapp/wire-ios-data-model/blob/68d5d5d5f385b15bb3cddbfe7facf12fecf5400a/Source/Model/Message/ZMClientMessage%2BEncryption.swift#L161) for details.
However, when the receiver deletes the ephemeral, they only delete the message locally. This means that when the destruction …
> delete for everyone when deleting ephemeral

- Source/Model/Conversation/ZMConversationMessageWindow.swift
The `size` property of the message window was not publicly accessible, which caused compilation problems in SE tests (cf. [Circle CI](https://circleci.com/gh/wireapp/wire-ios-sync-engine/3781?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
When this class was re-written in Swift, the size property was left with internal access.
> Make message window size public

- Source/Model/Conversation/ZMConversationMessageWindow.swift
An initializer previously available in the Objective-C implementation of `ZMConversationMessageWindow` was not made public in the Swift rewrite. This caused UI tests to fail.
> Add missing conversation message window initializer

- Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
Always call completion handler.
Completion handler for fetching image data wasn't always called which causes issues for the consumer.
> Guarantee that the completion handler is always called

- Source/Model/Message/ConversationMessage.swift
- Source/Model/Message/ZMAssetClientMessage+Download.swift
- Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
- Source/Model/Message/ZMAssetClientMessage.swift
- Source/Model/Message/ZMClientMessage+LinkPreview.swift
- Source/Model/Message/ZMImageMessage.m
- Source/Model/Message/ZMMessage.m
- Source/Public/ZMMessage.h
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+TextMessage.swift
Image were not being downloaded.
The method for requesting images was living on the base message protocol `ConversationMessage` and most of the time the underlying object is implementing the message data type protocol (image, file, text). But this is not always the case for images which resulted in a cast to fail.
Move image download methods to the relevant data type protocols to avoid having to rely on casting.
> Move image request methods to data type protocols

- Source/Model/Conversation/ZMConversation+UnreadCount.h
- Source/Model/Conversation/ZMConversation+UnreadCount.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
Adds `ZMConversation.hasUnreadMessagesInOtherConversations` which is used determine if we should show an back arrow dot.
Also expose predicates underlaying this, which is used as a debug tool in UI.
> Add hasUnreadMessagesInOtherConversations

- Source/Utilis/UTType+MIMEType.swift
We are leaking the return value from `UTTypeCreatePreferredIdentifierForTag`
the `Create` in `UTTypeCreatePreferredIdentifierForTag` indicate that this function will create an object which the caller is responsible for releasing.
Take ownership of the return value by calling `takeRetainedValue`.
> Fix memory leak caused by not taking ownership of object when expected

- Source/Model/Conversation/ZMConversation+Services.swift
- Tests/Source/Helper/ZMBaseManagedObjectTest+Helpers.swift
- Tests/Source/Model/Conversation/ZMConversationTests+CreationSystemMessages.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Services.swift
- WireDataModel.xcodeproj/project.pbxproj
We need a way to find an existing conversation with given service so we would not create duplicates.
The predicate for the matching conversation is pretty complicated, but basically is:
* Group conversation in a team
* You are part of it
* There is only one other participant
* The participant is a service with matching identifier
> Find conversation with service

- Source/Model/Conversation/ZMConversation+Services.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Services.swift
The existing logic of opening conversation with a service was not skipping conversations with custom defined name which made it easy to have multiple conversations with a service. "Open conversation" button would then open the most recent of all conversations with a service.
We filter out conversations with user defined name, so guestrooms and regular conversations created from UI are excluded. This (in most circumstances) leaves only a single conversation that we can open.
> Open service conversation: skipping conversations with a name

- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ZMMessage.m
- Source/Model/Message/ZMOTRMessage.m
- Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.m
- Tests/Source/Model/Conversation/ZMConversationTests+participants.m
- Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
Add method for verifying that a user is part of conversation.
Deleted some code for moving security level messages which is obsolete since we support adding/removing participants locally anymore.
> Update handling of missing participants

- Source/Model/Message/ZMOTRMessage.m
The integration test `[SendAndReceiveMessages testThatItAppendsClientMessages]` was failing randomly.
In this test two messages are received and then verified to be in the correct order. The messages were sometimes in the wrong order because the the conversation observer fired too early before the the messages had been sorted. This could happen since the SE context was saved in between that the new message was inserted and that the messages were sorted.
Sort messages immediately after inserting the message.
> Resort messages immediately after insertion to avoid saves in between

- Source/Model/Message/Mention.swift
- Source/Model/Message/ZMClientMessage+TextMessageData.swift
- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
Expose user object instead of the `userId` which isn't very useful in the UI.
> Expose user instead of userId on Mention

- Source/Model/Message/ZMOTRMessage+Unarchive.swift
- Source/Model/Message/ZMOTRMessage.m
- Tests/Source/Model/Conversation/ZMConversationTests+Silencing.swift
- WireDataModel.xcodeproj/project.pbxproj
Port of https://github.com/wireapp/wire-ios-request-strategy/pull/79 to data model, to unify the unarchiving logic in one place.
> Unarchive conversation if self user mentioned

- Source/Model/Message/ZMClientMessage+LinkPreview.swift
Some Link previews were not rendered when containing a valid link preview
We were expecting a link preview protobuf to either to contain a tweet or an article but this is no longer required. A link preview is by default an article and can be extended with more meta data (tweet).
Don't verify that the link preview contains an article.
> Fix some link previews not being rendered

- Source/Model/Message/ZMClientMessage+LinkPreview.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+ZMImageOwner.swift
Mention were disappearing when sending mention together with links
We didn't copy the mentions over when setting the downloaded link preview image data on a message.
Copy the mention over.
> Keep mentions when updating text message after setting image data

- Source/Model/Message/ZMOTRMessage+Unarchive.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Silencing.swift
We had a bug that the conversation was unarchived when self user is mentioned, even if the conversation is fully muted.
> Do not unarchive conversation if fully muted and mentioned

- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation+Predicates.swift
- Source/Model/Conversation/ZMConversation.m
After https://github.com/wireapp/wire-ios-data-model/pull/572, group conversation contains the matching user is not shown.
The predicate check for TeamRemoteIdentifierKey, which is not the valid key.
User TeamRemoteIdentifierDataKey instead of TeamRemoteIdentifierKey.
> Fix: Search results don't contain group conversations where the current user participates

- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
The issue happens when user is trying to upload the image bigger than 5 MB.
New logic to handle bigger images as files seem to fail when uploading the image.
Temporarily disable the new logic for the current release, fix properly for the new release.
> Temporarily ignore image size

- Source/Model/Account.swift
- Source/Model/LoginCredentials.swift
- Tests/Source/Model/AccountTests.swift
- WireDataModel.xcodeproj/project.pbxproj
When the user is logged out in the background (ex: remote client removal), and reopens the app, we show the screen to reauthenticate. However, the login field is not pre-filled as the user session is not available and we cannot access the email of the account.
When the user is removed when the app is in the foreground, we can pre-fill because the user session sends the token expired notification with the login credentials of its `ZMUser`.
However, in the case where the logout happens when we open the app, we can't pass the credentials in the notification because we don't have a user session to get the required details.
The `LoginCredentials` structure is now a part of the Account object, which makes it available in all contexts.
We also update the `Account` serialization to use `Codable` …
> Add login credentials to Account model

- Source/Model/Account.swift
- Tests/Source/Model/AccountStoreTests.swift
When updating to a build that includes the login changes, users get logged out.
This happened because we were not using the correct JSON keys for decoding the account in the account store. So the SE tried to login using the legacy store migrator, which couldn't find any account either, which caused the logout.
We fix the JSON Coding Keys for the account model to use the ones that were used in the previous version.
> ZIOS-10734: Fix user logout after updating to new login stack

- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
SSO user lost the information about it's being an SSO user after receiving any profile update.
We use one method to process /self response and any notification stream self update payload.
> Do not reset company login flag from notification stream

- Source/Model/Conversation/ZMConversation+Message.swift
- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
Changes to the API for adding a message to the conversation with a reply as well as creating text content with a reply were written in swift and used default arguments. Unfortunately, this API is also called from Objective C code in other frameworks, which requires that arguments be explicitly declared. This leads to several compilation errors requiring changes to method calls.
Redefine the old API methods that simply call the new methods with the default parameters provided.
> Provide method signatures without default args for objc

- Resources/zmessaging.xcdatamodeld/zmessaging2.56.0.xcdatamodel/contents
- Source/Model/Conversation/ZMConversation+Message.swift
- Source/Model/Message/ConversationMessage.swift
- Source/Model/Message/ZMClientMessage+TextMessageData.swift
- Source/Model/Message/ZMMessage.m
- Source/Public/ZMMessage.h
- Tests/Source/Model/Messages/ZMClientMessagesTests+Replies.swift
- Changed the relation cardinality from 1-1 to 1-many for the Message.replies-Message.quote relation.
- Fixed type to be Set, no array.
- Moved the replies from ZMTextMessage to ZMClientMessage.
> Data model: fix array vs set and relation cardinality

- Source/Model/Conversation/ZMConversation+Message.swift
- Source/Model/Message/ZMAssetClientMessage+Quotes.swift
- Source/Model/Message/ZMClientMessage+Quotes.swift
- Source/Model/Message/ZMOTRMessage+Quotes.swift
- Source/Model/Message/ZMOTRMessage+Replies.swift
- Source/Model/Message/ZMOTRMessage.m
- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
- Tests/Source/ManagedObjectContext/ZMSyncMergePolicyTests.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
- Tests/Source/Model/Messages/ZMClientMessageTests.m
- Tests/Source/Model/Messages/ZMClientMessagesTests+Replies.swift
- Tests/Source/Model/Messages/ZMMessageTests.m
- Tests/Source/Model/ZMBaseManagedObjectTest.m
- WireDataModel.xcodeproj/project.pbxproj
We need to establish a core data relationship when we receive a message containing a quote of another message.
- Changed the `ZMText` builder method to take a `ZMMessage` instead of a `id`since we need to compute the hash of the quoted content.
- The case for when a message is edited will come in a separate PR.
> Establish reply/quote relationships when receiving a message

- Source/Model/Message/ConversationMessage+Deletion.swift
- Source/Model/Message/ZMClientMessage+Edit.swift
- Source/Model/Message/ZMClientMessage+Editing.swift
- Source/Model/Message/ZMClientMessage+TextMessageData.swift
- Source/Model/Message/ZMClientMessage.m
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
- Source/Model/Message/ZMOTRMessage.m
- Source/Public/ZMMessage.h
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
- Tests/Source/Model/Observer/ConversationListObserverTests.swift
- Tests/Source/Model/TextSearchQueryTests.swift
- WireDataModel.xcodeproj/project.pbxproj
When editing a message we now update the edit message in-place instead of deleting the original message an inserting a new edited message. This has the benefit that any existing reply relationships will stay intact after a message is edited.
> Edit messages in-place

- Source/Model/Message/ZMClientMessage+TextMessageData.swift
- Source/Model/Message/ZMClientMessage.m
- Source/Model/Message/ZMMessage.m
- Source/Notifications/ObjectObserverTokens/ConversationChangeInfo.swift
- Source/Notifications/ObjectObserverTokens/MessageChangeInfo.swift
- Tests/Source/Model/Messages/ZMMessageTests.m
Fire a change notification when a quote is changed (currently only when a quote is deleted).
- `hasQuote` now only check if the protobuf contains a quote. The `quote` property might still be nil if the quote is not valid.
> Fire message change notification when quote is deleted

- Source/Public/DraftMessage.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Validation.m
- Tests/Source/Model/Conversation/ZMConversationTests+gapsAndWindows.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
Added the `quote` field to the `DraftMessage` class, and also added the supporting class `StorableQuote` and other methods. Updated tests.
> ZIOS-10799: Added quote field to DraftMessage

- Source/Model/Message/ConversationMessage+Deletion.swift
SE integration tests were failing after message editing changes.
In the failing test a message was edited but the message sending was intentionally failed, after this the edited message marked to be resent which failed to happen. The reason was for this was that we weren't allowing  messages with deliveryState  `failedToSend` to be edited.
~~Allow messages with deliveryState  `failedToSend` to be edited.~~
Revert back to previous logic which were always allowing previously edited messages to be edited again. This is safe since we can assume that an edited message was at some point successfully sent.
> Allow editing failed messages

- Source/Model/Message/ZMClientMessage+Editing.swift
- Source/Model/Message/ZMClientMessage+TextMessageData.swift
- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.swift
- WireDataModel.xcodeproj/project.pbxproj
We were losing the quote when applying a message edit.
According to the spec we do not allow users to edit the quote in a message, only the text can be edited. This means we should copy only text part of an edit but leave any existing quote as they are. We didn't do this but instead copied all the fields from the edit.
Keep the quote from the original message when applying a text edit.
> Fix editing message with quote

- Source/Utilis/Protos/ZMGenericMessage+Hashing.swift
- Tests/Source/Utils/ZMGenericMessageTests+Hashing.swift
Images quoted on iOS would show as "not available" on Web and Android.
An image hash is based on its asset id which is a string, therefore we must include a byte order marker in the beginning of the data just like we do for text message hashes.
Include byte order marker and update tests.
> Include byte order marker when hashing image asset id

- Source/Model/Message/V3Asset.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
In UI we started to post GIF only after the confirmation controller is dismissed. This caused the image appear while it is still not started to upload. 
We have the code that is requesting the download immediately when it sees the image, the data model was confused and allowed the uploading image to be set to be downloaded. This caused the uploader not to pick up the image.
Check in `requestImageDownload` if the image being uploaded now before marking it to be downloaded.
> Fix for GIFs getting stuck

- Source/Model/Message/ZMMessage.m
In order to un-brick the user's device we need to temporarily disable the assert. We need to run the in-depth investigation to fix it.
> Temp: do not assert on multiple delivery receipts

- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
Guest from ObjC world, `text.linkPreview` can be nil.
> Check if link preview exists

- Source/Model/Message/ZMClientMessage+Quotes.swift
- Source/Model/Message/ZMOTRMessage+Quotes.swift
Log when a quote is rejected because the hash doesn't match. This will make it easier to debug any issues with replies not working.
> Log a warning when a quote is rejected

- Source/Model/Message/ConversationMessage.swift
Add `readReceipts` property to `ZMConversationMessage`.
> Add readReceipts property to ZMConversationMessage

- Source/Model/Message/V3Asset.swift
- Source/Model/Message/ZMAssetClientMessage+GenericMessage.swift
Some Sync Engine tests started failing after #603 because we have a possibility (not sure if ever used in practice) to download a preview of asset message while it's still being uploaded by the sender. This (sort of) makes sense, when a person sending the message has uploaded a preview and is in the process of uploading the full asset. Then the receiver can look at the preview until an updated message with full asset come
Do not check for transfer state when we are about to download a preview for file message.
> Fix: asset message preview cannot be downloaded

- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser.m
- Source/Public/ZMEditableUser.h
- Tests/Source/Model/User/ZMUserTests.swift
As discussed, I've added the setting to `ZMEditableUser`. I am saving the setting to the context metadata, this seems to be the most appropriate. I could have added the database field to all users, but this seems unnecessary, since we don't know and don't care about the settings of other users.
> Added self user setting

- Source/Model/Message/ZMOTRMessage.h
- Tests/Source/Model/Conversation/ZMConversationTests+Silencing.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessagesTests+Replies.swift
Nullability was broken with the recent update (method can return nil).
> Fix nullability of messageUpdateResultFromUpdateEvent

- Source/Model/Confirmation/ZMMessageConfirmation.swift
- Source/Notifications/ObjectObserverTokens/ConversationChangeInfo.swift
- Source/Notifications/ObjectObserverTokens/MessageChangeInfo.swift
- Tests/Source/Model/Observer/ConversationObserverTests.swift
- Tests/Source/Model/Observer/MessageObserverTests.swift
Support for observing the changes for confirmations. Also updated how the reactions observation is working.
> Confirmations observation + Conversation hasReadReceiptsEnabled observation

- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation+Transport.m
- Source/Model/Conversation/ZMConversation.m
- Source/Public/ZMConversation.h
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
Support receipt mode when creating conversations when creating conversations locally or remotely.
> Support receipt mode when creating conversations

- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser.m
This adds one more key that indicates if the user properties must be synced.
It's set to true per default.
> Allow slow sync of user properties

- Source/Model/Message/ZMAssetClientMessage.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
If an image upload times out while sending, re-sending it would send a broken image.
We do not send placeholders for images while uploading them it therefore also doesn't make sense to send a "failed-to-upload" update for images like we do for files. When an asset message expire we didn't make a distinction between files and images so we were sending a "failed-to-upload" update for images when they expired. Upon successfully sending that update the image was marked as successfully sent since the rest of the image sending code were expecting to only send an update once the full image is uploaded.
Don't add an `NotUploaded` to image protobufs when they expire which will prevent the asset strategy from sending out an update.
> Fix broken image when an image upload fails

- Source/Model/Message/ConversationMessage.swift
We add the `needsReadConfirmation` property to the `ZMConversationMessage` protocol to be able to access it and mock it from UI.
> Expose needsReadConfirmation in the message protocol

- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
iOS client doesn't send read receipts for edited messages
We were losing the `expectsReadConfirmation` flag when applying a message edit.
Make sure to keep the `expectsReadConfirmation` flag.
> Keep read expectation when editing a message

- Source/Model/Message/ConversationMessage+Deletion.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
It is not possible to commit the edit on the read message.
We forgot to update the enum use case where we've been checking if message is possible to edit: before we had sending, failed, sent, delivered states. Now we added the new seen state.
Consider the seen state.
> Allow editing read messages

- Source/Model/Message/ConversationMessage+Reaction.swift
It was not possible to like your own message when it was marked as read.
We only allowed liking messages it their delivery state was `delivered` or `sent`.
Add the missing check for `read` state.
> ZIOS-10986: Allow liking message with read delivery state

- Source/Model/Message/ConversationMessage+Reaction.swift
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
We need to remove the confirmations when removing the message. The confirmations must persist when the message is obfuscated.
I added the code to assert the behavior and some tests on top.
> Delete read and delivery receipts when deleting the message

- Source/Model/Message/ConversationMessage.swift
Read messages could not be deleted.
We were not allowing to delete the message if the state is read. We fixed the comparison to include the read state.
This issue happened a lot during the run, it would be good to look on the issue to identify ways we can catch new delivery state changes in the future.
> ZIOS-11007: Allow deleting read message

- Source/Notifications/ObjectObserverTokens/MessageChangeInfo.swift
- Tests/Source/Model/Observer/MessageObserverTests.swift
List of read receipts didn't live update for assets
The `confirmations` property wasn't included in the list observable keys for asset messages.
Make The `confirmations` property observable.
> Fix observering of read receipts on assets

- Source/Model/Message/Ephemeral/ZMMessageDestructionTimer.swift
After #648 we have added API for creating timers explicitly. It was not very robust, because it would re-create timers if they existed.
Create timers only if they don't exist.
Tweaked the checks for correct MOC from:
```swift
if(!zm_isUserInterfaceContext) {
preconditionFailure("must be UI MOC")
}
```
to a simpler
```swift
precondition(zm_isUserInterfaceContext, "must be UI MOC")
```
> Do not create timers if they already exist

- Source/Model/Conversation/Permissions.swift
- Tests/Source/Model/PermissionsTests.swift
Renamed occurrences of `collaborator` to `partner`, to maintain consistency with feature terminology.
> Rename collaborator to partner

- Source/Model/Conversation/ZMConversation+DeleteOlderMessages.swift
- Tests/Source/Model/ConversationList/ZMConversationListTests.m
When a user tapped the "Delete and leave" button on a conversation in the conversation list, we would clear the contents of all conversations instead of clearing only the contents of the selected conversation.
In the `deleteOlderMessages` method on the conversation, we used a fetch request to delete all the messages received before the time the deletion was requested. However, this fetch request did not check the conversation of the messages, and thus would match all the messages in the database, regardless of the conversation.
In the predicate of the fetch request, we now check that the conversation of the messages matches the receiver of `deleteOlderMessages`.
> ZIOS-11133: Fix clearing all conversations when clearing only one

- Source/Model/ZMManagedObject.m
We were observing that conversations were being faulted and un-faulted repeatedly during event processing.
When fetching the self conversation we will end up calling `fetchObjectWithRemoteIdentifier:inManagedObjectContext:`which would un-fault all conversations when accessing  the `remoteIdentifier` property.
Skip the comparison for faults since we will anyway need to perform a fetch to get the object which is the current fallback if we don't find the object among the registered objects.
> Avoid unnecessary unfaulting

- Source/Utilis/InvalidConversationRemoval.swift
- Source/Utilis/PersistedDataPatches+Directory.swift
- Tests/Source/Utils/InvalidConversationRemovalTests.swift
- WireDataModel.xcodeproj/project.pbxproj
As described in  https://github.com/wireapp/wire-ios-sync-engine/pull/953 we've been creating invalid conversations.
Delete all conversations of type `.invalid` in a data patch
This should be released together or after the fix for not creating invalid conversations.
Needs releases with:
> Data patch for deleting invalid conversations

- Source/Model/Conversation/ZMConversation+Timestamps.swift
Marking messages as read does a fetch request which is fairly expensive
When we mark a message as read we currently search backwards looking for the first unread message and update the last read timestamp using the `serverTimestamp` of that message. This search is done by a fetch request which is fairly expensive.
I believe that this backwards search is a left over from the time when we updated the last read state using event identifiers. Since we nowadays update the last read using a timestamp it should not be any harm in updating the last read state using a newer timestamp.
> Avoid unnecessary fetch request when updating the last read timestamp

- Source/Model/User/ZMUser.swift
After more thorough inspection it seems that there is no need to nil the identifiers when fetching profile picture. Posting notification is enough to trigger download.
> Removed unused code for fetching profile pictures

- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ZMMessage.m
- Tests/Source/Model/Messages/ZMMessageTests+ShouldGenerateUnreadCount.swift
It's been observed that internal users get an unread badge count without seemingly having any unread conversations. 
We recently started including `.newConversation` system messages in the unread count if the conversation was started by someone else than the self user. This had the side effect of marking all conversations which were slow synced on login as unread. The badge count wouldn't update immediately since we only re-calculate the unread count when something unfaults the conversation.
Distinguish between conversations which were slow synced and conversations which were created from an update event. One way of doing this is by looking at the `lastServerTimestamp` which doesn't exist for slow synced conversations and therefore is set to the UNIX reference. timestamp.
> Old conversations generate a badge count

- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation+SystemMessages.swift
- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ZMMessage.m
- Source/Model/Message/ZMSystemMessage+NewConversation.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Teams.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMMessageTests+ShouldGenerateUnreadCount.swift
`.newConversation` system messages can now generate unread dots, this created unwanted unread  conversation for people who upgrade.
We previously tried to solve this by introducing `hasBeenModifiedSinceSlowSync` but that solution didn't cover all the edge cases,  a conversation can be modified by for example someone being added or removed causing the same issue to re-appear.
`.newConversation` system message will from now on have a correct `serverTimestamp` associated with them since that timestamp will be visible when you read the message, to enable this  we need to re-factor `appendNewConversationSystemMessageIfNeeded` to take a timestamp parameter.
NOTE: The solution for the unwanted unread conversations is done in sync engine.
> Create .newConversation system messages with a timestamp

- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m
- Tests/Source/ManagedObjectContext/ManagedObjectContextTests.m
- Tests/Source/ManagedObjectContext/MockBackgroundActivityManager.swift
- WireDataModel.xcodeproj/project.pbxproj
In several places instead of regular save we do a delayed save - an optimization that can coalesce several requests to save the data store and do only a single real save. There is a problem with this when app is in the background, because we do not wrap this operation with an active background activity and it can potentially lead to crashes and data loss.
It all depends on timing but if iOS decides to suspend the app while we are doing a save the app will crash. This happens because SQLite locks the file when saving and iOS kills the app if it encounters this while suspending the process.
We start an activity the first time someone calls `enqueueDelayedSave` and finish it when we do the real save in `saveOrRollback`.
> Make sure delayed save can be completed in background

- Source/Utilis/Protos/GenericMessage+Helper.swift
When sending location message read receipts are ignored and for sender the message is not marked as read.
After #618 we have introduced Swift protobufs and methods for reading read receipt flags were not implemented in the code that deals with location.
Add read receipt flags to Swift protobuf protocol.
> Fix: read receipts does not work when sending location

- Source/Model/User/ZMSearchUser.swift
- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
Users are not able to edit profile when the `managedBy` property is `nil`.
Added this case to the`managedByWire` property.
> Added nil condition to managedByWire

- Source/Model/Conversation/ZMConversation+Predicates.swift
- Source/Model/User/UserType.swift
- Source/Model/User/ZMSearchUser.swift
- Source/Model/User/ZMUser.swift
- Tests/Source/Model/User/ZMUserTests.swift
Expose `activeConversations` on the `UserType`. We need this property to in order to calculate the set of "active" users.
> Expose activeConversations on the UserType

- Source/Model/Message/ZMAssetClientMessage.swift
- Tests/Source/Model/Messages/CacheAssetTests.swift
GIFs were not animated
GIFs were being preprocessed like normal images, which converts them into to jpegs.
Return `needsPreprocessing = false` if the mime type indicates that the image is a gif.
> Don't preprocess GIFs

- Source/Model/Message/V2Asset.swift
- Source/Model/Message/V3Asset.swift
- Source/Model/Message/ZMAssetClientMessage.swift
App crashes after sending ephemeral gif
App crashes due to division by zero when computing image constraints because the image size is reported as zero.
The image size is zero because we don't do image preprocessing for GIFs so were relying on the value of `preprocessedSize`, which gets set to zero when the image gets obfuscated.
- Add the image size into the protobuf from the start, we don't need  the`preprocessedSize` property anymore but we have to keep for now to be compatible with older images.
- Make constraint code resilient to zero size images.
> Crash when sending ephemeral gif

- Source/Notifications/ObjectObserverTokens/UserChangeInfo.swift
Your own profile image wouldn't update immediately after changing it.
We observing when the image data changed on disk but at the time when it changes the `previewProfileAssetIdentifier` and `completeProfileAssetIdentifier` were not yet updated on the UI context. This resulted in that we fetched the old profile image from the cache instead of the new one.
Also observe changes to `previewProfileAssetIdentifier` and `completeProfileAssetIdentifier`.
> Observe asset identifier in addition to the image data

- Source/Model/Message/TextSearchQuery.swift
- Tests/Source/Model/TextSearchQueryTests.swift
Change search query length limit form 2-character to 1-character.
> Fix: Change search query length limit

- Source/Model/Message/TextSearchQuery.swift
- Tests/Source/Model/TextSearchQueryTests.swift
After discussion with QA team, we decided to keep the current query length limit to align to other platforms at this moment. The changes in https://github.com/wireapp/wire-ios-data-model/pull/697 is keep but set the limit to 1 character.
> Undo - Change search query length limit

- Source/Model/Conversation/ZMConversation+Transport.m
- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser.m
- Source/Model/ZMManagedObject+Internal.h
- Source/Model/ZMManagedObject.m
During profiling it's visible that `updateMembersWithPayload:` take up a significant time if the number of participants is big.
Inside `updateMembersWithPayload:` the line which takes the most time is `[ZMUser userWithRemoteID:userId createIfNeeded:YES inContext:self.managedObjectContext]` since it's executed for every participant added to the conversation.
Fetch all participants in one batch.
- I replaced `NSOrderedSet` with a plain `NSSet` since we don't rely on the order.
> Batch fetch users when updating conversation members

- Source/Utilis/PersistedDataPatches+Directory.swift
Having `migrateLegacyTransferState` twice in the patch list will apply the migration twice if the user upgraded from before `158.0.0`.
Remove `158.0.0` and  keep`161.0.1`.
> Avoid migrating twice when upgrading from older version

- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests+participants.m
If you leave a group the conversation will get archived, if you later get added back the conversation will stay in archive.
it's unclear what was causing the unarchiving previously. (*checking*)
Unarchive the conversation if it isn't muted.
> Unarchive a conversation when you are added to it

- Source/Model/Conversation/ZMConversation+ExternalParticipant.swift
- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation.m
- Source/Model/User/ZMUser.m
- Source/Notifications/ObjectObserverTokens/ConversationChangeInfo.swift
- Source/Notifications/ObjectObserverTokens/UserChangeInfo.swift
- Source/Notifications/SideEffectSources.swift
- Tests/Source/Model/Conversation/ZMConversationExternalParticipantsStateTests.swift
- Tests/Source/Model/Observer/ConversationObserverTests.swift
- WireDataModel.xcodeproj/project.pbxproj
The system to detect if the conversation contains guests or services was located in UI, and was not observable. 
While it is fine in most cases, there are some cases where a service can be added remotely and we get the participants changed notification before we fetch that the added user is a service, we will not update the UI to reflect that it's a service once the fetch is done (e.g. we won't show the "services are present banner").
This PR contains two solutions to this problem:
1. We move the logic from `GuestBarState` that's defined in UI into data model. We create the `ZMConversationExternalParticipantsState` enum, and the `externalParticipantsState` property on the conversation. We add the matrix and the tests for this property.
2. We make this property observable as part of …
> ZIOS-11329: Improve detection and observing of guest/services presence

- Source/Model/User/ZMUser+Availability.swift
This allows us to remove a helper in UI that implements the behavior of CaseIterable to access all the cases of the enum.
> Make Availability conform to CaseIterable

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.m
When a conversation becomes unverified after discovering a client when sending a message, we show an alert to the user asking them whether we want to send the message anyway, see the device or cancel.
If they cancel, the conversation remains degraded, and the next time the user sends a message, we show the alert again.
We do not decrease the security of the conversation when the user cancels the alert.
Mark the conversation as not secure when cancelling the alert, so that we don't ask the user again. That way, we align the behavior with calls and the upcoming legal hold feature.
> ZIOS-11422: Make the conversation not secure when ignoring the new client alert

- Source/Model/UserClient/UserClient.swift
- Source/Model/UserClient/UserClientTypes.h
- Source/Model/UserClient/UserClientTypes.m
- Tests/Source/Model/UserClient/UserClientTests.swift
- Turn `UserClient.type` and `UserClient.deviceClass` from `String` into extensible typed enums.
- Annotate `UserClientType` with nullability
- Add `update(with payload: [String: Any])` in order to move responsibility for parsing user client payload from request strategy to the data model.
> Convert deviceClass and type into typed enums

- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
Support `oneToOneConversation` for the self user by returning the self conversation.
> Return self conversation for oneToOneConversation on the self user

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
After merging the logic for degrading and legal hold, tests started failing in sync engine.
Some logic got lost in translation:
- We did not insert the list of users in the system message when a client was added.
- It was possible to move to the `notSecure` verification level from the `secureWithIgnored` state.
> Fix system message issues

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Message/ZMAssetClientMessage.swift
- Source/Model/Message/ZMOTRMessage.m
- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Legalhold.swift
We added support for legal hold flags in messages in #731. We now need to process this flag when receiving a message to update the legal hold status in the conversation.
- Update the message content protocol to conditionally return the status, only if it's set in the protobuf
- Add a method on the conversation to update the status based on the hint and current status
- Update the OTR message downstream creation method to call the method mentioned above before inserting the message
> ZIOS-11452: Process legal hold hint flag when receiving message

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
New clients are reported as new users joining the conversation.
The new clients system message included a non-empty set of  `addedUsers` which causes the UI report it as new users joining the conversation.
Don't set `addedUsers` when discovering a new clients.
> Fix: new clients are reported as new users joining the conversation

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
Tests were failing because `.newClient` system message didn't have any users.
This broke in https://github.com/wireapp/wire-ios-data-model/pull/735
Restore previous behaviour but keep the distinction between `users` and `addedUsers`
> Fix .newClient system message not having any users set

- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Conversation/ZMConversation+SystemMessages.swift
- Source/Model/Conversation/ZMConversation+Transport.m
- Source/Model/Conversation/ZMConversation.m
- Source/Model/User/ZMUser+LegalHoldRequest.swift
- Source/Model/User/ZMUser.swift
- Source/Model/UserClient/UserClient.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Legalhold.swift
- Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.m
- Tests/Source/Model/Conversation/ZMConversationTests+participants.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
- Tests/Source/Model/Observer/ConversationObserverTests.swift
- Tests/Source/Model/User/ZMUserLegalHoldTests.swift
- Tests/Source/Utils/DuplicatedEntityRemovalTests.swift
In this PR, we fix bugs related to the disclosure of legal hold to the user.
When a user under legal hold created a group conversation, the system message indicating that legal hold is enabled was inserted before the "new conversation" system messages. The expected behavior is the opposite.
The method `+[ZMConversation insertGroupConversationIntoManagedObjectContext:withParticipants:]` previously inserted the users in the conversation before inserting the new conversation message. However, the call to insert users (`-[ZMConversation internalParticipants:]`) also called the method to degrade the conversation if needed.
While this didn't have any effect on verification, because the conversation isn't verified when created, it actually caused the legal hold to be enabled, because the …
> Fix legal hold disclosure issues

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Legalhold.swift
When receiving a message with a legal hold hint, we would insert too many system messages:
```
<legal hold activated>
<message content>
<legal hold deactivated>
<legal hold activated>
```
The reason behind this is that after we finish the request to the BE to verify the legal hold hint, we'd call `updateSecurityLevelIfNeededAfterFetchingClients`, which performs an unconditional legal hold state update before we actually fetch the legal hold client. This caused a legal hold disabled system message to be inserted, and a hold-enabled message to be inserted later after we actually fetch the device. 
- Create a `ZMConversationRemoteClientChangeSet` option set to pass the type of changes that occurred to `updateSecurityLevelIfNeededAfterFetchingClients`
- If there are no changes, that means …
> ZIOS-11499: Fix redundant legal hold update messages

- Source/Model/UserClient/UserClient.swift
- Tests/Source/Model/UserClient/UserClientTests.swift
Messages fail to send certain conversations
The message depends on a client to be updated but it never updates because the server response doesn't contain the expected `class` field
The  `class` field is optional so we should not require it to be present.
> Message stuck in sending

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Legalhold.swift
When discovering a legal hold through metadata flag we would insert too many legal hold system messages.
We would update legal hold status after each client change we discover. This would cause us to disable and then immediately enabled legal hold depending on the order of how we discover the clients.
Example:
1. We receive a message with `legal hold = true` metadata flag
**We insert legal hold enabled system message**
2. We start verifying the legal hold by fetching all the clients in the conversations and discover client A and B, where client B is the legal hold client.
3. Client A metadata  arrives first and we recompute the legal hold status and discover that there's no legal hold.
**We insert legal hold disabled system message**
4. Client B metadata  arrives and we recompute the …
> Don't update legal status while we are still gathering client changes

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Message/ZMClientMessage.m
- Tests/Source/Model/Conversation/ZMConversationTests+Legalhold.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
@VictorWissink discovered several issues with edited messages when discovering legal hold.
1. An edited message doesn't trigger the legal hold discovered alert
2. An edited message which is expired can't be resent by tapping the resend button.
3. The `legal hold discovered` system message is inserted above the edited message which would falsely indicate that all the following messages are also under legal hold.
This happens when the original message which was edited message is older than the message timeout limit (60 seconds) because the fetch request which collects the undelivered messages was only looking for messages with a `serverTimestamp` not older than the message timeout limit. Edited messages don't modify the `serverTimestamp` instead they assign the `updatedTimestamp`.
When …
> Fix issues with legal hold being discovered by a message edit

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Conversation/ZMConversation.m
The integration tests started failing after we fixed the conversation list order when restoring from a backup https://github.com/wireapp/wire-ios-data-model/pull/749
Two tests started to fail:
`testThatTheConversationListOrderIsUpdatedAsWeReceiveMessages`
`testThatPreviousPotentialGapSystemMessageGetsDeletedAndNewOneUpdatesWithOldUsers`
`testThatTheConversationListOrderIsUpdatedAsWeReceiveMessages`:
This test was failing because a new group conversation would have the `lastModifiedDate` set to the 1970:s until the first message is posted. Since `lastModifiedDate`is used to calculate the conversation list order the test started to fail.
The reason why the `lastModifiedDate` was stuck to 1970:s is because we assign an initial `lastModifiedDate` when creating a conversation and since …
> Fix failing integration tests

- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
After https://github.com/wireapp/wire-ios-protos/pull/35, update the default value of `MessageContentType` form `.DISABLED` to `.UNKNOWN`.
> Fix: change default legal hold status from .disable to .unknown

- Source/Model/Conversation/Team.swift
- Source/Notifications/ObjectObserverTokens/TeamChangeInfo.swift
- Tests/Source/Model/Observer/ObjectObserverToken/TeamObserverTests.swift
- Add support for observing when the `imageData` property changes on a `Team`. 
- Add `Team.add(observer: TeamObserver, for team: Team)` so that UI can observe a team without having a reference to the managed object context.
> Add support for observing when the team image data changes

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Message/ZMOTRMessage+VerifySender.swift
- Source/Model/Message/ZMOTRMessage.m
- WireDataModel.xcodeproj/project.pbxproj
On iOS 13, App crashes at the line 
```
conversation addParticipantIfMissing:[ZMUser userWithRemoteID:updateEvent.senderUUID createIfNeeded:YES inContext:moc] date: [updateEvent.timeStamp dateByAddingTimeInterval:-0.01]];
```
`addParticipantIfMissing` does not accept optional value but it has a default value for `date`.  A mehtod with default value should not exposed to objc callers.
Refactor the method to Swift and make sure all arguments are non nil.
> Fix: app crashes when calling addParticipantIfMissing

- Source/Model/Message/FileAssetCache.swift
- Tests/Source/Model/Messages/FileAssetCacheTests.swift
If the team logo was already assigned it would not update if it was changed.
We would not download the new team logo because we would think that we already have the image data locally.
Include the team logo asset id in the cache key to differentiate between old and new team logos.
> Fix team logo not updating

- Source/Model/Conversation/ZMConversation+Timestamps.swift
`wire-ios` project access `savePendingLastRead` but it is not public. After refactoring the UI code it is not able to access `savePendingLastRead`.
> fix: make savePendingLastRead public

- Source/Model/Conversation/ZMConversation+Deletion.swift
- Source/Model/User/UserType.swift
- Source/Model/User/ZMSearchUser.swift
- Source/Model/User/ZMUser+Permissions.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Deletion.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests+Ephemeral.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- Tests/Source/Model/ModelObjectsTests+Helpers.swift
- Tests/Source/Model/User/ZMUserTests+Permissions.swift
- WireDataModel.xcodeproj/project.pbxproj
- Delete associated cached assets when deleting a conversation
- Add method `canDeleteConversation(_ : ZMConversation)`. on the `UserType`
> Add support deleting conversations

- Source/Utilis/ZMUpdateEvent+WireDataModel.m
Support extracting the conversation uuid from `.teamConversationDelete` event.
> Feature: Support extracting conversationId from .teamConversationDelete event

- Source/ConversationList/ConversationDirectory.swift
Allow other projects creating `ConversationDirectoryChangeInfo` instance
> expose ConversationDirectoryChangeInfo init for UI unit tests

- Source/Model/Conversation/ZMConversation.m
A team member with the partner role can't open team 1:1 conversation
The method for fetching a team 1:1 conversation was checking that the self user has the permission to create conversations, which partners don't have.
Remove incorrect permission check.
> Fix: partner not being able to to create or fetch a team 1:1 conversation

- Source/ConversationList/ConversationDirectory.swift
Compare `changeInfo.conversationList` with conversation list's address instead of value to prevent difference list may have the same values issue.
> Fix: compare changeInfo.conversationList pointer with conversations

- Source/Model/Conversation/ZMConversation+Labels.swift
Allow UI to get Conversation's folder label
> fix: expose ZMConversation.folder

- Source/ConversationList/ConversationDirectory.swift
- Source/ConversationList/ZMConversationList.m
- Source/ConversationList/ZMConversationListDirectory.m
- Source/Notifications/ConversationListObserverCenter.swift
- Tests/Source/Model/ConversationList/ZMConversationListDirectoryTests+Labels.swift
- WireDataModel.xcodeproj/project.pbxproj
If you create folder on a second device while the app is in the background these would not appear until the app is restarted.
When the app is in the background we do not observe any changes so we need re-fetch all conversations & folders which were potentially created in the background. 
We were not re-fetching the folders.
Also re-fetch the folders when re-starting the observation system.
> Fix: folder created while in the background does not appear until restart

- Source/Model/Conversation/ZMConversation+Predicates.swift
- Tests/Source/Model/ConversationList/ZMConversationListDirectoryTests.m
Service conversation would appear under the group section
The Group section predicate was not filtering out fake 1:1 conversations
Filter out fake 1:1 conversations.
> Fix: service conversations appearing under groups

- Source/ConversationList/FolderList.swift
The initial order of the folder is inverted.
Comparator was flipped which was compensated for in the insertion sort method.
Correct the Comparator and undo the correction in the insertion sort method.
> Fix: the initial sorting order folders is inverted

- Source/ConversationList/ZMConversationListDirectory.m
It's been observed that the folder sometimes does not update when moving a conversation.
When a `ZMConversationList` is deallocated it attempt to unregister itself with the `ConversationListSnapshotObserver` and when it's allocated it registers itself.
When the app comes back from being the background we recreate all the folder lists which caused the following to happen:
1. register newly created folders lists with the observer centre
2. assign newly created folders lists to  `listsByFolder` this will cause the old folder lists to deallocate which in turn will deregister the newly registered lists.
Nil out `listsByFolder` before assign the new folder lists to avoid scenario above.
> Fix: folder list observers not created after returning from background

- Source/Model/User/UserType.swift
- Source/Model/User/ZMSearchUser.swift
- Source/Model/User/ZMUser+Availability.swift
- Tests/Source/Model/User/UserAvailabilityTests.swift
- WireDataModel.xcodeproj/project.pbxproj
Moved the `shouldHideAvailability` property implementation & tests from `wire-ios` to `wire-ios-data-model`
> [Refactor] Add shouldHideAvailability property to ZMUser

- Source/Model/ConversationRole/Action.swift
- Source/Model/ConversationRole/Role.swift
- Tests/Source/Model/ConversationRole/ActionTests.swift
- Tests/Source/Model/ConversationRole/RoleTests.swift
Fix logic to fetched existing matching `Action`.
Create tests to check that repeated `Role` or `Action` would be fetched but not created.
> Fix: fetch role predicate fix and create tests for fetching

- Tests/Source/Model/Conversation/ZMConversationTests.m
Convert `ZMConversationTests` categories into `#pragma mark -` to fix tests not detected by Xcode issue.
> fix: ZMConversationTests.m - tests are not detected in categories

- Source/Model/Conversation/ZMConversation+Timestamps.swift
- Source/Model/Conversation/ZMConversation+Transport.swift
Fix the issue that `ZMConversation+Transport` method are not public after converted to Swift
> Fix: expose functions in ZMConversation+Transport

- Source/Model/Conversation/ZMConversation+Creation.swift
- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Conversation/ZMConversation+Transport.swift
- Source/Model/ConversationRole/Role.swift
- Source/Model/User/ZMUser.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Participants.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.m
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.swift
- Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
- Tests/Source/Model/ZMTestSession.swift
- WireDataModel.xcodeproj/project.pbxproj
Adding the ability to parse the self user role. 
Also address the fact that roles are not updated when parsing the metadata for a user that changed role.
> Parse self user role

- WireDataModel.xcodeproj/project.pbxproj
Currently our tests are crashing when the optimization is enabled. We'll temporarily disable it to unlock the team from writing more tests. We will revert this before the release.
> [HACK] Disable code optimization

- Source/Model/Conversation/ZMConversation+Patches.swift
Add and expose the default conversation role "member" for use in upstream projects and expose for objective c.
> Expose default member role name

- Source/Model/Conversation/ZMConversation+Transport.swift
- Source/Model/ConversationRole/Role.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.swift
Previously we were parsing the self role in the entire JSON payload of a conversation. 
However, we use the `updateSelfStatus` method also to parse member update events JSON fragments, and that method does not parse the self role, relying on the outer method to parse the entire conversation JSON.
This PR moves the self role parsing inside that method, so that it can be used by sync engine to parse the self role also for events.
> Parse self user role in conversation JSON fragment for self

- Source/Model/User/ZMUser+Permissions.swift
- Tests/Source/Model/User/ZMUserTests+Permissions.swift
Add check to the delete conversation permission (only creator with admin role can delete the conversation).
> Fix: Add check to the delete conversation permission

- Patches/DuplicatedEntityRemoval.swift
- Source/Model/ConversationRole/ParticipantRole.swift
- Source/Model/User/ZMUser.swift
- Source/Model/UserClient/UserClient.swift
- Source/Notifications/SideEffectSources.swift
- WireDataModel.xcodeproj/project.pbxproj
Fix crash when optimization is turned on. This was caused by `ParticipantRole.conversation` being optional in the Core Data schema but not in the Swift class.
> Fix optional field for core data

- Source/Model/Conversation/ZMConversation+Participants.swift
- Tests/Source/Model/Observer/ConversationObserverTests.swift
Added tests to assert that changes to a participant role triggers notifications that the conversation changed. I have also renamed a method for readability.
> [Chore] Tests for participant role changes

- Source/Model/Conversation/ZMConversation+Predicates.swift
- Tests/Source/Model/Conversation/ParticipantRoleTests.swift
- Tests/Source/Model/ConversationList/ZMConversationListDirectoryTests.m
Services now contain 2 members, so the predicate must be changed.
> Fix: Update predicateForTeamOneToOneConversation

- Source/Model/Conversation/ZMConversation+Patches.swift
- Tests/Source/Utils/SelfUserParticipantMigrationTests.swift
With version 2.78 of the data model, the `isSelfAnActiveMember` properties is now a computed property based on the `participantRoles`. In 2.77, `isSelfAnActiveMember`  was an actual core data (boolean) property.
There is a migration step that reads the old value for `isSelfAnActiveMember`  and update `participantRole`. However the migration step uses the new computed property (based on `participantRoles` rather than reading from the Core Data property. Therefore it would never migrate property, as there is never any `participantRoles` at the beginning of the migration.
This PR reads from the proper Core Data value during migration.
> Use primitive value `isSelfAnActiveMember` for migration

- Source/Model/User/ZMUser+Permissions.swift
Only allow user has team to delete a conversation
> Fix: Personal group creator (and Admin) should not see Delete Group option

- Source/Model/Conversation/ZMConversation+Patches.swift
- Tests/Source/Utils/RolesMigrationTests.swift
Roles for a conversation should be fetched from a team or the conversation. When we have access to the team metadata (i.e. we are part of the team), we should fetch roles from the team. If not, then from the conversation.
The code was checking if the conversation is in a team, but not if it's our team. If the conversation is in another team, we should fetch the roles from the conversation, as we won't have access to that team.
This is similar to https://github.com/wireapp/wire-ios-sync-engine/pull/1132, applying the same logic to the migration.
> Fetch conversation roles for conversations in other teams

- Source/Model/User/ZMUser+Permissions.swift
- Tests/Source/Model/User/ZMUserTests+Permissions.swift
Partner can not create a 1-to-1 conversation
Partner does not pass permission check
fix with the correct permission check
> Fix: External(partner) cannot create 1:1 with a person whom External never have 1:1 before

- Source/Model/Conversation/Permissions.swift
- Source/Model/Conversation/ZMConversation+Creation.swift
- Source/Model/User/UserType.swift
- Source/Model/User/ZMSearchUser.swift
- Source/Model/User/ZMUser+Permissions.swift
- Tests/Source/Model/Conversation/ConversationTests+gapsAndWindows.swift
- Tests/Source/Model/Conversation/ZMConversationTests+gapsAndWindows.m
- Tests/Source/Model/User/ZMUserTests+Permissions.swift
- WireDataModel.xcodeproj/project.pbxproj
add `type` parameter to `canCreateConversation` checker. Partner team role can only create 1-on-1 conversation but not other kinds.
add `type` parameter to `insertGroupConversation`.
> Fix: allow partner to create 1-on-1 conversaton but not group conversation

- Source/Model/Conversation/ZMConversation+Participants.swift
- Source/Model/Conversation/ZMConversation+Transport.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Participants.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.swift
Add a method to make sure conversation roles are refetched when needed. This method is called every time a conversation is updated from payload.
This solves the bug when roles are not fetched when a user is added to a conversation. Previously, the check on whether roles should be fetched was done at the sync engine level, when the conversation payload was not yet parsed. At the time of the check, we would not know if the conversation was a group or in a team, and the check would always fail due to incomplete information.
> Refetch roles when needed

- Source/Model/User/ZMUser+Permissions.swift
- Tests/Source/Model/User/ZMUserTests+Permissions.swift
Conversation action permissions were based on a mix of conversation roles and team roles. However, according to the new conversation roles specs, the actions should be based exclusively on the conversation role, with a few exceptions:
- deletion -> user is creator && conversation admin
- add/remove service -> user is in the team && conversation admin
Everything else is just based on conversation role.
I updated the code to reflect this, and removed a lot of old tests that were checking these permissions based on the user type or team membership.
This PR includes the deletion of a lot of tests. Unfortunately, those tests were testing the wrong behaviour.
> Make conversation permission based on conversation roles

- Patches/PersistedDataPatches+Directory.swift
The migration for conversation roles was started from the wrong version. The previous released data model version was 197. The migration was set to run if the old version was before 197, which was causing it not to be run at all.
> Using correct version number in migration

- Source/Model/Conversation/ZMConversation+Patches.swift
- Tests/Source/Utils/SelfUserParticipantMigrationTests.swift
Group participants are incorrectly migrated as members instead of admins.
During the migration of team group conversations a new `Role` was created for each conversation instead them all sharing the the same `Role` as expected. The duplicate roles would later be deleted when the `TeamRolesDownloadRequestStrategy` syncs the team roles, leaving the participants without a role and thus default to be "members".
Fetch any existing `Role` before creating a new `Role` for a team conversation.
> Fix: migration to roles failing due to duplicate Roles being inserted

- Source/Model/Conversation/ZMConversation+Patches.swift
We've seen reports that the app crashes while migrating to the new user roles
Optional values are force unwrapped
Unwrap optional values before attempting to use them.
> [Fix] crash by unwrapping optional values before attempting to use them

- Source/Model/Conversation/ZMConversation+Message.swift
- Source/Model/Conversation/ZMConversation.m
- Source/Model/Message/ZMAssetClientMessage.swift
- Source/Model/Message/ZMFileMetadata.swift
- Source/Utilis/Protos/GenericMessage+Helper.swift
Refactor the message sending methods to use the the Swift Protobuf API. This is compatible with the existing Objective-C implementation since we serialize and store the protobufs as a data blob.
> [Refactor] Send regular messages using Swift Protobuf API

- Source/Model/Conversation/ZMConversation+Predicates.swift
- Tests/Source/Model/Conversation/ConversationTests.swift
- Tests/Source/Model/Utils/String+WordTests.swift
- WireDataModel.xcodeproj/project.pbxproj
Application crashes when searching for contacts with symbol
`String.words` methods returns empty string array when the query string is "@"
Append the whole string as a word when the return array is empty. Escape the string for regex.
> Fix: Application crashes when searching for contacts with symbol

- Source/Model/Conversation/ZMConversation+Message.swift
- Source/Utilis/Protos/GenericMessage+Helper.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Messages.swift
If you reply to an image it's not included as quote.
The quoted image message was casted to a `ZMClientMessage`, which fails since image messages are of type `ZMAssetClientMessage`.
Cast quoted messages the base class `ZMOTRMessage` instead.
> [Fix] image quotes are getting lost

- Source/Model/Conversation/ZMConversation+Message.swift
Fix a mistake from the previous PR. 
- appendSelfConversationWithLastReadOf() method should be public.
- change a parameter name for appendSelfConversationWithLastReadOf method.
> Fix/make as a public appendSelfConversationWithLastReadOf method

- Source/Notifications/ObjectObserverTokens/UserChangeInfo.swift
- Tests/Source/Model/Observer/NotificationDispatcherTests.swift
- Tests/Source/Model/Observer/SearchUserObserverTests.swift
- Tests/Source/Model/Observer/UserObserverTests.swift
This PR is part of an ongoing effort to remove all concrete user objects from the UI project. See the architecture issues for more info: https://github.com/wireapp/ios-architecture/issues/89
`ZMUser` and `ZMSearchUser` references in are now hidden in `UserChangeInfo.swift`. There were three methods to add user observers, one to add an observer for a conforming `UserType`, and one each for adding observers specific to `ZMUser` and `ZMSearchUser`. The latter two methods allowed to observe a single instance or all concrete instances.
Since we can rely on the first method so observe changes in a specific `ZMUser` or `ZMSearchUser` instance, I've removed them. In their place are now two methods to add observers that are interested in changes in all concrete instances, one for each concrete …
> [Refactor] Hide Concrete Users in User Classes

- Source/Model/User/UserType.swift
- Source/Model/User/ZMSearchUser.swift
- Source/Model/User/ZMUser.m
- Source/Model/User/ZMUser.swift
- Source/Public/ZMUser.h
- Tests/Source/Model/User/ZMUserTests.m
- Tests/Source/Model/User/ZMUserTests.swift
Since the rules for displaying the verified shield have changed, we decided to create a new `verified: Bool` property in` UserType`.`verified` property shows whether the user verified own and other devices.
PR also contains the convert of trusted() and untrusted() methods from Objective C to Swift.
> [Fix] Add the verified property on the UserType.

- Source/Model/Conversation/ZMConversation+Message.swift
- Source/Utilis/Protos/GenericMessage+Helper.swift
- Tests/Source/Utils/GenericMessageTests+LinkMetaData.swift
- WireDataModel.xcodeproj/project.pbxproj
This PR is part of a refactoring sending messages using Swift Protobuf API:
- Create methods to convert LinkMetadata to LinkPreview objects.
> [Refactor] Swift protobuf - LinkPreview

- Source/Model/Conversation/ZMConversation+UnreadCount.m
- Tests/Source/Model/Conversation/ZMConversationTests.m
The unread messages badge contains a blocked conversation. 
There is no check for the predicate if the conversation is blocked.
Add a check.
> [Fix] Do not show an unread messages badge if a conversation is blocked

- Source/Model/User/UserType.swift
- Source/Model/User/ZMSearchUser.swift
This PR adds `phoneNumber` to `UserType` to make it conformable to `ZMEditableUser`. After this addition, any object conforming to `UserType` can also conform to `ZMEditableUser` given that the access requirements are met.
> [Refactor] Add phoneNumber to UserType

- Source/Model/User/ZMUser.swift
- Source/Public/ZMUser.h
- Tests/Source/Model/User/ZMUserTests.m
Add (restore) the `initials` property to the ZMUser since we need it in the UI project.
> [Feature] Add (restore) initials property to ZMUser

- Source/Model/UserClient/UserClient+SafeLogging.swift
- Tests/Source/Model/UserClient/UserClientTests+SafeLogging.swift
- WireDataModel.xcodeproj/project.pbxproj
- Added `safeRemoteIdentifier` to `UserClient`
- Added tests
> [Fix] Add safeRemoteIdentifier to UserClient

- Source/Model/Message/ZMClientMessage+Encryption.swift
- Source/Model/Message/ZMClientMessage.h
- Source/Model/User/ZMUser+Internal.h
- Source/Model/User/ZMUser+Protobuf.swift
- Source/Model/User/ZMUser.m
- Source/Utilis/Protos/GenericMessage+Helper.swift
- Source/Utilis/Protos/ZMGenericMessage+Helper.swift
- Tests/Source/Model/Messages/BaseClientMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
- Tests/Source/Model/Messages/ZMGenericMessageTests+NativePush.swift
- WireDataModel.xcodeproj/project.pbxproj
- Retire `ZMNewOTRMessage` protobuf and use `NewOTRMessage` instead
> [Refactor] Retire ZMNewOTRMessage 

- Source/Model/Message/ConversationMessage.swift
Currently the only way to check if a particular user is the sender of the message is to do a comparison with the `sender: ZMUser` property of `ZMConversationMessage`. Equation with `sender` therefore requires an instance of `ZMUser`.
In order to remove some usages of `ZMUser` from the UI project, we also need a way to check if a given `UserType` is the sender of a message.
Provide a method on `ZMConversationMessage` that checks if a `UserType` instance is the sender of the message.
> [Refactor] Add method to determine if user type is sender

- Source/Model/Conversation/ZMConversation+Creation.swift
This PR is part of an ongoing effort to remove references to concrete user objects. See https://github.com/wireapp/ios-architecture/issues/89 for more details.
---
This PR tightens some public API by changing the argument types of `[ZMUser]` to `[UserType]`.
> [Refactor] Use UserType in publicly exposed methods

- Source/Model/UserClient/UserClient.swift
Just a bug fix
When the user is logged in, Wire will report client information to the server
But under iPad, the device class will be reported as "phone"
It's should be "tablet"
userClient.deviceClass = model.hasSurffix("iPad") ? .tablet : .phone
Surffix should be Prefix.
userClient.deviceClass = model.hasPrefix("iPad") ? .tablet : .phone
> [Fix]Unable to get correct device class on iPad

- Source/Model/ButtonState/ButtonState.swift
- Source/Model/Message/ZMClientMessage+Composite.swift
- Source/Utilis/Protos/ZMGenericMessage+Utils.m
- Tests/Source/Model/Messages/ZMClientMessageTests+Composite.swift
- Fix button action not sending 
- Create button state if necessary on confirmation
> [Fix] Sending alarming response button action 

- Source/Model/ButtonState/ButtonState.swift
- Source/Notifications/DependencyKeyStore.swift
- Source/Notifications/ObjectObserverTokens/MessageChangeInfo.swift
- Source/Notifications/SideEffectSources.swift
`MessageChangeInfo` observer was observing changes to the message object, such as insertions and deletions on the `buttonStates` property. But it was not observing updates on the `ButtonState` entities. 
- Conform `ButtonState` to `SideEffectSource` protocol
- Add `ButtonState` to the observable keys of `DependencyKeyStore` 
- Update `MessageChangeInfo` to verify if the buttonState key is part of the observed changes
> [Fix] button state changes not observed

- Source/Model/Message/Message.swift
It is necessary add the action menu model logic to check if a message can be digital signed.
Check if the file contained in the message is a pdf
wire-ios: https://github.com/wireapp/wire-ios/pull/4214
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-12763
> [Feature]: SignIn Message Menu Action

- Source/Model/Message/File/SignatureStatus.swift
- Source/Model/Message/Message.swift
- Source/Model/Message/V2Asset.swift
- Source/Model/Message/V3Asset.swift
- Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
- Remove not necessary documentID parameter from SignatureStatus
- calculate encoded pdf hash.
UI: https://github.com/wireapp/wire-ios/pull/4216
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-12762
> [Feature] Calculate pdf hash

- Source/Model/User/ZMUser+Teams.swift
- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
Establish team membership, if a user belongs to the same team as the self user.
> [Feature] Establish team membership if user belongs to the self user team

- Source/Model/Conversation/ZMConversation+Participants.swift
- Source/Model/Message/Composite/CompositeMessageItemContent.swift
- Source/Model/Message/ZMMessage+Conversation.swift
- Tests/Source/Model/Messages/Composite/BaseCompositeMessageTests.swift
- Tests/Source/Model/Messages/Composite/CompositeMessageItemContentTests.swift
- Tests/Source/Model/Messages/Composite/ZMClientMessageTests+Composite.swift
- WireDataModel.xcodeproj/project.pbxproj
In a conversation with Poll Bot: 
**a)** Send a poll message 
**b)** Remove Poll Bot from the conversation 
**c)** Tap on any poll button. 
**Expected:** User should see an error immediately. 
**Actual:** It takes 10-20 second before user sees an error.
No check to verify if the service is in the conversation before sending the Button Action
Set `ButtonState.isExpired` to true in `buttonAction()` if service is not in conversation
> [Fix] error message delay when service not in conversation

- Source/Model/UserClient/UserClient.swift
- Tests/Source/Model/UserClient/UserClientTests.swift
To handle missing `team.member-leave` update events, we need to fetch the user metadata if we suspect the user has left the team.
We suspect that a user left the team if all of their clients are deleted. This can happen in response to sending a message in the conversation. The response would tell the sender that they attempted to send a message to clients that have been deleted. The self client would then update the local state by tearing down the encryption sessions for those devices and removing the devices completely. In this process, we can check if the user is a team member and no longer has any clients left, in which case we trigger the data fetch.
JIRA: https://wearezeta.atlassian.net/browse/ZIOS-12825
> [Feature] Trigger user data fetch when a team members last client is deleted

- Source/Model/Conversation/Team.swift
- Source/Model/User/UserType.swift
- Source/Model/User/ZMSearchUser.swift
- Source/Model/User/ZMUser.swift
The UI may need to trigger remote data fetches for certain objects. This is typically done by setting flags such as `needsToBeUpdatedFromBackend`, which will automatically schedule downstream requests to the backend.
These properties however are defined on concrete managed objects and are therefore not exposed through the various abstraction protocols, such as `UserType` and `TeamType`.
Extend `UserType` and `TeamType` to include methods to request data refreshes from the backend.
> [Feature] Add helper methods to request data refreshes

- Source/Model/User/UserType.swift
- Source/Model/User/ZMSearchUser.swift
- Source/Model/User/ZMUser.swift
In https://github.com/wireapp/wire-ios-data-model/pull/932 I introduced some helper methods to request data refreshes from the UI. Unfortunately, access to team objects are not exposed through the `UserType` abstraction, and consequently it is difficult to request a refresh of team metadata.
Add a method to `UserType` to request a refresh of team metadata.
> [Feature] Add method to UserType to request team data refresh

- Source/Model/User/ZMUser+Teams.swift
- Tests/Source/Model/User/ZMUserTests.m
When a team member is removed from the team we delete the membership relation, but we would re-create the membership if we ever fetched the user again.
When fetching a deleted team member it still includes the `team` property, which will trigger us to create a membership relation if it doesn't already exist.
Don't create memberships for users which are marked as deleted.
> [Fix] Don't create memberships for deleted users

- Source/Model/Conversation/ZMConversation+Mute.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Mute.swift
Alarming messages are silenced, but they should override all notifications preferences
Do not silence if message is an alarming message (composite message)
> [Fix] make alarming messages not silenced

- Source/Model/Message/Composite/CompositeMessageData.swift
- Expose optional `ZMTextMessageData` of `CompositeMessageItem` enum
Note: Sync Engine needs this for notifications
> [Fix] expose text data of CompositeMessageItem for notifications

- Source/Model/User/ZMUser+Teams.swift
- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
When processing a `team.member-leave` event we mark the user as deleted and delete their `membership`. In large teams however we will not receive this event.
In this case, we discover if a user has been removed from the team by fetching their metadata and inspecting the `deleted` and `team` keys. Currently, we will only mark the user as deleted, but the local instance of their membership will still exist.
Delete the user membership if the user is deleted and belongs to the self team.
**JIRA:** https://wearezeta.atlassian.net/browse/ZIOS-12826
> [Feature] Delete user membership they are marked as deleted

- Source/Model/Message/ZMClientMessage+Encryption.swift
- Source/Model/User/ZMUser+Availability.swift
- Tests/Source/Helper/ZMBaseManagedObjectTest+Helpers.swift
- Tests/Source/Model/User/ZMUserTests.swift
Broadcasting status messages to the entire team is not feasible for unbounded teams. Therefore we must limit the number of recipients who will receive status updates from a member.
Limit the recipients of a broadcast message to known team members and contacts. Known team members are members of the same team of the self user who participate in at least one conversation with the self user. 
Additionally, we limit the maximum number of recipients. We prioritize team member recipients over contacts. This means we take as many known team members as possible, and include any contacts until we meet the specified maximum.
Finally, the return recipients is deterministically calculated. This is means that for any given state of the database, repeated calculations for the recipients will always …
> [Feature] Limit status broadcast to known team members and contacts

- Source/Model/User/ZMUser+Availability.swift
- Tests/Source/Model/User/ZMUserTests.swift
When calculating the recipients of a broadcast message, it could happen that the self user is not included as a recipient.
The recipient list is determined as follows: 
1. A maximum number of free slots is allocated. 
2. Find all known team members, sort by their id, take as many as possible.
3. If there are still free slots available, repeat step 2 for connected users.
Currently, the self user is considered to be a known team member. If there are more free slots than known team members, then the self user will be a recipient. 
However, if there are more known team members than free slots, it is possible that the self user is not included because their sorted position at the *nth* index, where *n* is greater than the number of available free slots.
1. Add the self user as the first …
> [Fix] Guarantee self user recipient

- Source/Model/Conversation/Member.swift
We are are creating memberships when discovering team members but they are not fetched from the backend.
`needsToBeUpdatedFromBackend` is `false`
Set `needsToBeUpdatedFromBackend` to true when inserting a new membership.
> [Fix] Memberships not being downloaded

- Source/Model/User/ZMUser+Availability.swift
- Tests/Source/Model/ModelObjectsTests+Helpers.swift
- Tests/Source/Model/User/ZMUserTests.swift
The recipients of a broadcast message contain connected users, some of which are not in any team at all. These users don't see availability statuses (team on feature) and just take up available recipient slots.
Exclude connected non team users from the recipient list.
**JIRA:** https://wearezeta.atlassian.net/browse/ZIOS-12888
> [Fix] Don't broadcast to consumer connections

- Source/ManagedObjectContext/ManagedObjectContextDirectory.swift
- Source/Model/Conversation/ConversationCreationOptions.swift
- Source/Model/Conversation/ZMConversation+Creation.swift
- Source/Model/User/UserType+Materialize.swift
- Source/Model/User/ZMSearchUser.swift
- Tests/Source/Helper/ZMBaseManagedObjectTest+Helpers.swift
- Tests/Source/Model/User/ZMSearchUserTests+TeamUser.swift
- Tests/Source/Model/User/ZMSearchUserTests.m
- Tests/Source/Model/UserTypeTests+Materialize.swift
- WireDataModel.xcodeproj/project.pbxproj
- Directory results will now return team users, `ZMSearchUser` has therefore been updated to represent a team user.
- Introduce the `materialize(in:)` method which transform a sequence of ZMSearchUser (UserType) into concrete ZMUser instances. 
We can now search for team members which doesn't exist in our local database, these users will represented by a `ZMSearchUser` until the user decides to perform an action with them (add to conversation, create conversation). At that point we will transform them into concrete `ZMUser` and insert then into the local database using the `materialize(in:)` method.
> [Feature] Support for team users in ZMSearchUser

- Source/Model/Message/GenericMessage+External.swift
- Source/Model/Message/ZMGenericMessage+External.h
- Source/Utilis/Dictionary+ObjectForKey.swift
- Tests/Source/Model/Messages/GenericMessageTests+External.swift
- WireDataModel.xcodeproj/project.pbxproj
Add support to init `GenericMessage` with `ZMUpdateEvent` and `External`
> [Refactor] Add support of External for GenericMessage

- Source/Model/Message/GenericMessage+UpdateEvent.swift
- WireDataModel.xcodeproj/project.pbxproj
- Add support to init `GenericMessage` from `ZMUpdateEvent` 
- Will remove objc protobuf implementation in separate PR
> [Refactor] support `GenericMessage` init from `ZMUpdateEvent`

- Source/Utilis/Protos/GenericMessage+Assets.swift
- Source/Utilis/Protos/GenericMessage+Helper.swift
- WireDataModel.xcodeproj/project.pbxproj
- Move `Asset` related protobuf code to its own file
- Add necessary inits
> [Refactor] support assets for `GenericMessage`

- Source/Model/Message/File/SignatureStatus.swift
Send as a parameter to the BE the assetID instead of the assetID of the preview.
> [Fix] AssetId for the digital signature

- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.swift
In the UI project the verified shield is shown on the connection request page.
We increase the security level for the connection when the user verifies all of its own devices.
Do not increase the security level for the connection.
> [Fix] Do not increase the security level for the connection

- Source/Model/User/ZMUser+Availability.swift
- Tests/Source/Model/ModelObjectsTests+Helpers.swift
- Tests/Source/Model/User/ZMUserTests+Swift.swift
- WireDataModel.xcodeproj/project.pbxproj
1. The self user is counted as a broadcast recipient twice
2. Connected external team users were not being broadcasted to
3. All tests in `ZMUserTests.swift` were not running
1. At the call `remainingSlots -= recipients.count`, `remainingSlots` already includes the self user. On the right hand side, `recipients` also includes the self user.
2. The predicate `%K != NULL` for the `teamIdentifier` was not correct (not sure why though).
3. I believe because they were defined in an extension, and furthermore the base class was in Objc.
1. Calculate the remaining slots from the `maxCount`.
2. Don't rely no the predicate, but instead use standard filtering.
3. Split those swift tests into a separate class.
> [Fix] Broadcast recipients

- Source/Model/User/ZMSearchUser.swift
- Tests/Source/Model/User/ZMSearchUserTests+TeamUser.swift
Add support for team member metadata on the `ZMSearchUser`, which will enable us apply filtering logic to regarding team member in search results.
> [Feature] Add support for team member metadata on the ZMSearchUser

- Source/Model/Message/ZMClientMessage+TextMessageData.swift
When a message was edited and sent, the receiver was not receiving the updated message
the generic message object representing the edited message was created with the wrong nonce
Apply the editedNonce to the generic message object representing the edited message
> [Fix] Edit Message Not Applied

- Source/Model/User/ZMSearchUser.swift
We sometimes get into a request loop when fetching members.
The permissions field on the member response was incorrectly marked as non-optional, causing the payload decoding to fail if that field was not present.
Mark permissions field as optional.
> [Fix] Make Permissions argument optional

- Source/Model/Conversation/ZMConversation+Participants.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Participants.swift
When a participant is discovered to be deleted, they are removed from the conversation as expected. However, it can happen that at a later point in time they are re-added to the conversation, even though they are deleted. 
This happens when the app is restarted and we receive a delayed member join update event (for the deleted user), in which case the user is re-added to the conversation. It may also be possible in other undiscovered cases.
Check whether users have deleted accounts before adding them.
> [Fix] Don't add deleted participants to conversation

- Source/Model/User/ZMUser.m
- Tests/Source/Model/User/ZMUserTests.m
When a user is deleted, their name is set to "default".
When synchronizing a deleted user with the backend, the backend sets the name field to "default". This is likely to erase metadata for the deleted user. However, when parsing the payload we will set the local user objects name to "default", overwriting their existing username.
Don't update the user name if the user is marked as deleted.
> [Fix] Don't update name for deleted users

- Source/Model/Connection/ZMConnection.m
- Tests/Source/Model/ZMConnectionTests.m
We have seen clients reporting to have a connection with itself.
It's unclear exactly when such connection can be created.
Guard against such connection being created by validating that the `to` field is not referring to the self user.
> [Fix] Guard against connections referring to the self user

- Source/Model/Message/ZMOTRMessage+UpdateEvent.swift
Add more detailed logging when we abort processing of a message because we can't decode the protobuf.
> [Fix] Add more detailed logging when aborting processing of a message

- Source/Utilis/Protos/GenericMessage+Content.swift
Use `WireProtos.Reaction` instead of `Reaction` for the computed property `hasReaction`.
> [Fix] Correct the 'hasReaction' computed  property

- Cartfile
- Cartfile.resolved
- WireDataModel.xcodeproj/project.pbxproj
Dependency on `wire-ios-protos` as branch named "24.0" which doesn't exist
Fix syntax for declaring the dependency on `wire-ios-protos` of major version 24.0.
> [Fix] Dependency on wire-ios-protos in Cartfile

- Source/Model/Message/ZMOTRMessage+UpdateEvent.swift
- Source/Utilis/Protos/GenericMessage+Debug.swift
- WireDataModel.xcodeproj/project.pbxproj
We do not remove the text content of protobuf message before logging them. 
It was removed during the protobuf refactoring.
Create helper methods that were in objc version.
**Jira ticket:**
https://wearezeta.atlassian.net/browse/ZIOS-13496
**Old objc code:**
https://github.com/wireapp/wire-ios-data-model/blob/220.0.5/Source/Model/Message/ZMGenericMessage%2BDebug.swift#L73
> [Fix] Internal debug message for the GenericMessage

- Source/Model/Conversation/ZMConversation+Timestamps.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
A badge count is sometimes generated for a conversations where all messages are read.
The badge count is calculated by counting the number of conversations which have a `estimatedUnreadCount > 0`. This is a conversation property in the database which is calculated by counting the messages which are newer than `lastReadServerTimestamp`. It's supposed to be re-calculated when a message is inserted, deleted, updated or when the `lastReadServerTimestamp` is changed.
We've observed that sometimes the `lastReadServerTimestamp` had been updated without re-calculating the `estimatedUnreadCount` value. It's unclear exactly why this started to happen now but my guess is that something changed related to when objects are faulted / re-fetched, because we explicitly re-calculate the value when we …
> [Fix] Attempt to fix wrong badge count

- Source/Utilis/EncryptionKeys.swift
- Tests/Source/Utils/EncryptionKeysTests.swift
- WireDataModel.xcodeproj/project.pbxproj
Add support for creating encryption keys necessary for EAR. The idea is that the `EncryptionKeys` struct should only be initialised when the application runs in the foreground and the user is authenticated. An attempt to initialise `EncryptionKeys` in any other scenario will throw an error.
**NOTE:** The Secure Enclave is not available in the simulator so when running there the account key is stored in the keychain instead.
> [Feature] Support creating/deleting/accessing encryption keys for EAR

- Source/Model/Message/File/SignatureStatus.swift
- Tests/Source/Model/DigitalSignature/SignatureStatusTests.swift
The PR try to solve the following issue:
If the user tap multiple time in a super short interval on the "Complete Signing" button before we close the OTP screen the request for the digital signature is made multiple times, this cause we don't have control to enable end disable the button (Swisscom web page).
> [Feature]: Avoid Digital Signature Multiple Requests

- Source/Utilis/EncryptionKeys.swift
- Tests/Source/Utils/EncryptionKeysTests.swift
When activating EAR we need to have the encryption keys available immediately, this is currently not possible without asking the user to authenticate with biometrics
Modify `createKeys()` to return the newly created keys.
> [Feature] Return EncryptionKeys after creation

- Source/Utilis/EncryptionKeys.swift
- Tests/Source/Utils/EncryptionKeysTests.swift
The database key does not work with AES256GCM encryption.
The expected key length is 256 bits (32 bytes), but the actual key length is 2048 bits (256 bytes).
Change the key length.
> [Fix] Database key should be 256 bits

- Source/ManagedObjectContext/ManagedObjectContextDirectory+EncryptionAtRest.swift
- Tests/Source/ManagedObjectContext/ManagedObjectContextDirectoryTests.swift
- WireDataModel.xcodeproj/project.pbxproj
In order to encrypt and decrypt message content in the database, we need access to the database key. The database key should never persisted and only live in RAM. We should aim to keep the references to the key to an absolute minimum so as to avoid the key surviving for extended periods of time. Furthermore, keeping the references to the key to a strictly small set of known objects allows us to remove those references when we want, such as when moving to the background.
For these reasons, I believe it's best to avoid passing the database key through all the codepaths from high level business logic to low level database access, where the encryption / decryption takes place. Instead, we can provide access to the database key for all managed objects through their corresponding managed object …
> [Feature] Store the database key in each contexts userInfo

- Source/Utilis/EncryptionKeys.swift
The private key stored in the Secure Enclave can't be fetched on a real device.
The fetch request fails with error code -50 indicating that the get query is configured incorrectly. Looking at the properties of the get query when running on a real device we can see that we are trying to set `kSecUseAuthenticationUISkip` to `true`, which is incorrect. `kSecUseAuthenticationUISkip` is value and not a property key.
Correctly configure the `kSecUseAuthenticationUI` property.
> [Fix] Private key can't be retrieved on a real device

- Source/Model/Message/ZMGenericMessageData.swift
- Tests/Source/Model/Messages/ZMGenericMessageDataTests.swift
When encrypting generic message data we now provide additional data which will be bound to the ciphertext. A ciphertext bound to contextual data can only be decrypted with the same contextual data. For this reason, it should not change over the life of the ciphertext. 
The chosen contextual data is a combination of the user id and client id. In the case of restoring a backup on a new device, the client id will change, however we will not be backing up generic message data in its encrypted form.
> [Feature] Provide additional data when encrypting

- Source/ManagedObjectContext/ManagedObjectContextDirectory+EncryptionAtRest.swift
- Source/ManagedObjectContext/NSManagedObjectContext+EncryptionAtRest.swift
- Source/Model/Message/ZMGenericMessageData.swift
- Source/Utilis/EncryptionKeys.swift
- Tests/Source/ManagedObjectContext/ManagedObjectContextDirectoryTests.swift
- Tests/Source/Model/Messages/ZMGenericMessageDataTests.swift
We are currently storing the database key in the MOCs and also in the `SyncStatus` in SE. This PR attempts to unify these to approaches so that keep all the keys in one place in memory.
- Store all encryption keys instead of only database key
- Update tests
> [Refactor] Store all encryption keys in the MOC

- Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
Someone can send to the user a file in Wire which will be sent as an `Asset`.
The asset contains among other things the name of the file. In the code that I linked to we are creating a path to a file on the file system which has the same name.
An attacker can choose to send a file path in the name like ".../.../secret.txt" this will fool our code which creates the file URL to navigate to place on disk which was not intended.
We should do some validation on name property so that an attacker can't traverse the file system. The easiest way is always taking the lastPathComponent from the file name.
[lastPathComponent.playground.zip](https://github.com/wireapp/wire-ios-data-model/files/5101320/lastPathComponent.playground.zip)
> [Fix]: Path Traversal on Attachments

- Source/ManagedObjectContext/NSManagedObjectContext+ZMKeyValueStore.swift
- WireDataModel.xcodeproj/project.pbxproj
This PR is a part of Notification service extension refactoring.
wireapp/wire-ios-request-strategy/pull/240
> [Refactor] Move NSManagedObjectContext extension from SE

- Source/Model/Message/TextSearchQuery.swift
- Tests/Source/Model/Messages/BaseClientMessageTests.swift
- Tests/Source/Model/TextSearchQueryTests.swift
When inserting a message we update `normalizedText`, which contains a normalised version of the text message suitable for searching. This was also happening when `encryptMessagesAtRest` was enabled which defeats its purpose since we would then store a plain text version of the message in the database. 
Skip updating the `normalizedText` property when `encryptMessagesAtRest` is enabled in the same way we do for obfuscated messages.
> [Fix] Dont set normalizedText when encrypt messages at rest is enabled

- Source/Model/UserClient/PushToken.swift
- Tests/Source/Model/UserClient/PushTokenTests.swift
To be able to decoder push token without `type` property we need to have a custom decoder. All old clients will have `type` by default as `.voip`.
> [Refactor] Add PushToken decoder

- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.swift
Badge count is not updating when receiving a notification in the background.
After the EAR refactoring we started to [calculate an estimated unread count](https://github.com/wireapp/wire-ios-sync-engine/pull/1305) when scheduling notifications. This change was relying on the fact this estimated unread count would get updated again when the app put into the foreground and we perform the full event processing and read unread count can be calculated.
This didn't work because the estimated unread count was updated too early because we calculate the unread count when a `ZMConversation` is awoken by a fetch. This was happening before we could update the badge count and was reverting estimated unread count since messages haven't been inserted into the database at this point.
Stop calculating the …
> [Fix] Badge count not updating on receiving a push notification

- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationPerformanceTests.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
- WireDataModel.xcodeproj/project.pbxproj
- WireDataModel.xcodeproj/xcshareddata/xcbaselines/F9C9A5051CAD5DF10039E10C.xcbaseline/55BD42EF-71F0-4CB8-A473-F9E5849C2044.plist
- WireDataModel.xcodeproj/xcshareddata/xcbaselines/F9C9A5051CAD5DF10039E10C.xcbaseline/Info.plist
Accessing the `conversationType` property on `ZMConversation` is a relatively expensive operation.
Although the `conversationType` is a Core Data attribute, we have a custom accessor that will override the value if the conversation is a group conversation in a team but should be considered as a 1:1 conversation. There are certain criteria that must be satisfied to consider the group as a 1:1, and most of these criteria are fast to check. The most expensive check involves querying the conversation participants, and in the worst case scenario the entire set of all participants is enumerated 4 times. This is due to non-lazy sequence transformations over the `participantRoles` property (mapping and filtering).
By checking the count of `localParticipantRoles` (an O(1) expense) before accessing …
> [Performance] Optimize conversation type calculation

- Source/Model/Conversation/ZMConversation.m
Accessing users during event processing was often ending up doing a fetch request which is expensive.
All users were faulted on a save even though we have a rule to keep users in memory if they belong to a recently modified conversation. This rule was broken since the introduction of participant roles, it was putting `ParticipantRole` objects in the set of `usersToKeep`, which is expected to only contains `ZMUser` objects.
Call `localParticipants` instead which returns a set of `ZMUser`:s.
> [Fix] Don't fault users which are likely to be accessed again soon

- Source/Notifications/NotificationDispatcher.OperationMode.swift
- Source/Notifications/NotificationDispatcher.swift
- Tests/Source/Model/Observer/NotificationDispatcherTests.swift
- WireDataModel.xcodeproj/project.pbxproj
This PR is part of ongoing work to refactor the NotificationDispatcher such that it can operate in an "economical" mode which favors speed over detail.
To be able to change the tracking behavior of `NotificationDispatcher` at runtime so that it uses the `PotentialChangeDetector` and fires notifications less frequently.
Added `public operationMode: OperationMode` to the notification dispatcher to differentiate between normal operation and economical operation.
> [Performance] Change tracking operation mode

- Source/Notifications/NotificationDispatcher.swift
After the `NotificationDispatcher` leaves `economical` mode, the `ConversationListObserverCenter` doesn't post complete change information. The visual effect of this is the conversation list doesn't display the up to date state.
While in `economical` mode, the `NotificationDispatcher` uses the `PotentialChangeDetector` to accumulate change information. Unlike the normal explicit change detector, the potential change detector doesn't report change dependencies as also being changed. In other words, if a message is inserted in the database, the message insertion is detected, but the conversation of that message is not considered changed. The `ConversationListObserverCenter` relies on these transitive changes to post change information to the conversation list.
When the conversation list …
> [Fix] Conversation list observer is out of sync after economical mode

- Source/Notifications/NotificationDispatcher.swift
- Tests/Source/Helper/NotificationObservers.swift
- Tests/Source/Model/Observer/NotificationDispatcherTests.swift
Restoring a large backup freezes the app
After restoring a large backup all messages goes through the observer system and specifically the `NewUnreadMessageChangeObserver`. This change observer relies the `unreadMessages` property in the `NotificationDispatcher` which collects unread messages. These unread messages never gets reset though so we keep reporting more and more message as unread, which causes the UI thread to freeze.
Reset the `unreadMessages` property after firing the notifications.
We also don't want to run the all existing messages through observer system when restoring a backup but that will be fixed in a separate PR.
> [Fix] Restoring a large backup freezes the app

- Source/Model/Message/ZMMessage.m
Fetching message by nonce is very slow for users with large databases
By turning on the SQL debugging with `-com.apple.CoreData.SQLDebug 4` we can see that fetching a message by nonce ends up using the `ZMESSAGE_Z_ENT_INDEX`, which is indexing messages by their entity type (ClientMessage or AssetMessage). This is not very efficient when looking for a specific message since we search through either all ClientMessage or all AssetMessage messages.
```
EXPLAIN QUERY PLAN SELECT t0.Z_ENT, t0.Z_PK, t0.Z_OPT, t0.ZCACHEDCATEGORY, t0.ZDELIVERED, t0.ZDESTRUCTIONDATE, t0.ZEXPECTSREADCONFIRMATION, t0.ZEXPIRATIONDATE, t0.ZISEXPIRED, t0.ZISOBFUSCATED, t0.ZLINKATTACHMENTS, t0.ZMODIFIEDKEYS, t0.ZNEEDSLINKATTACHMENTSUPDATE, t0.ZNEEDSTOBEUPDATEDFROMBACKEND, t0.ZNONCE_DATA, t0.ZNORMALIZEDTEXT, …
```
> [Performance] Use correct index when fetching messages by nonce

- Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
Asset filenames currently have excessing diacritics stripped from them, but it would be better to normalize the filename to contain only characters from the POSIX fully portable character set.
Fortunately we already have a `String` extension that handles this, we just have to use it.
> [Improvement] Normalize asset filenames

- Source/Model/Message/ZMMessage.m
As reported in https://github.com/wireapp/wire-ios/issues/4431 when the `MessageExpirationTimer` fetches ephemeral messages it uses the `Z_Message_hiddenInConversation_isExpired_serverTimestamp_delivered` index, which isn't optimal.
```
CoreData: details: SQLite: EXPLAIN QUERY PLAN SELECT t0.Z_ENT, t0.Z_PK, t0.Z_OPT, t0.ZCACHEDCATEGORY, t0.ZDELIVERED, t0.ZDESTRUCTIONDATE, t0.ZEXPECTSREADCONFIRMATION, t0.ZEXPIRATIONDATE, t0.ZISEXPIRED, t0.ZISOBFUSCATED, t0.ZLINKATTACHMENTS, t0.ZMODIFIEDKEYS, t0.ZNEEDSLINKATTACHMENTSUPDATE, t0.ZNEEDSTOBEUPDATEDFROMBACKEND, t0.ZNONCE_DATA, t0.ZNORMALIZEDTEXT, t0.ZSENDERCLIENTID, t0.ZSERVERTIMESTAMP, t0.ZHIDDENINCONVERSATION, t0.ZQUOTE, t0.Z10_QUOTE, t0.ZSENDER, t0.ZVISIBLEINCONVERSATION, t0.ZASSETID_DATA, t0.ZASSOCIATEDTASKIDENTIFIER_DATA, t0.ZISDOWNLOADING, …
```
> [Performance] Use correct index when fetching ephemeral messages

- Source/ManagedObjectContext/ManagedObjectContextDirectory.swift
- Source/Model/Connection/ZMConnection.swift
- Source/Model/Conversation/Team+Patches.swift
- Source/Model/Conversation/ZMConversation+Creation.swift
- Source/Model/Conversation/ZMConversation+Patches.swift
- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Conversation/ZMConversation+Services.swift
- Source/Model/Conversation/ZMConversation+UnreadCount.swift
- Source/Model/Message/TextSearchQuery.swift
- Source/Model/Message/ZMMessage+Categorization.swift
- Source/Model/Message/ZMMessage+Removal.swift
- Source/Model/UserClient/UserClient+Patches.swift
- Source/Model/ZMManagedObject+Internal.h
- Tests/Source/ManagedObjectContext/DatabaseMigrationTests.swift
- Tests/Source/ManagedObjectContext/StorageStackBackupTests.swift
- Tests/Source/ManagedObjectContext/StorageStackTests.swift
- Tests/Source/Model/Conversation/ConversationTests+gapsAndWindows.swift
- Tests/Source/Model/Conversation/ConversationTests.swift
- Tests/Source/Model/TextSearchQueryTests.swift
- Tests/Source/Utils/DuplicatedEntityRemovalTests.swift
change `sortedFetchRequest` and its overrides return type to nonnull
> fix: change sortedFetchRequest return to nonnull

- Resources/zmessaging.xcdatamodeld/zmessaging2.87.0.xcdatamodel/contents
- Source/ManagedObjectContext/ExtendedSecureUnarchiveFromData.swift
App crashes when accessing a `modifiedKeys` property on an entity when running iOS 12
```
NSInvalidArgumentException:
Object of class __NSSingleObjectSetI is not among allowed top level class list (
NSArray,
NSDictionary,
NSString,
NSNumber,
NSDate,
NSData,
NSURL,
NSUUID,
NSNull
)
```
Is thrown by `[NSSecureUnarchiveFromDataTransformer reverseTransformedValue:]`.
This started to happen because we switched to use secure encoding for our transformable properties in Core Data since it's recommend by Apple and will soon be the default. This works great on iOS 13 and iOS 14 but fails on iOS 12 since `NSSet` is not included in the list of allowed top level classes and `modifiedKeys` stores a `NSSet`
Add `NSSet` to the list of allowed top level classes in our custom secure transformer and use it …
> [Fix] Crash when accessing modifiedKeys property on iOS 12

- Source/Model/User/ZMUser+AnalyticsIdentifier.swift
- Source/Model/User/ZMUser.m
- Source/Model/User/ZMUser.swift
- Tests/Source/Model/User/ZMUserTests+AnalyticsIdentifier.swift
- Tests/Source/Model/User/ZMUserTests.m
- WireDataModel.xcodeproj/project.pbxproj
When the analytics id is first generated, we want to append it to the self conversation so that the other devices of the self user can receive it and use it when sending events.
Appending the analytics id to the self conversation when it is generated leads to a stack overflow.
The id is generated when accessing the self user for the first time. Accessing the self conversation depends on accessing the self user, so an infinite recursion of the self user and self conversation occurs.
Lazily generate the analytics id when it is accessed, if needed. By using custom accessor methods, we can also enforce which kind of users should have an analytics id.
> [Refactor] Generate analytics identifier

- Source/Model/User/ZMUser+AnalyticsIdentifier.swift
- Source/Utilis/Protos/GenericMessage+Content.swift
- Tests/Source/Model/User/ZMUserTests+AnalyticsIdentifier.swift
When the analytics identifier is generated for the self user, we must send it to the other devices for that user so that they can be notified of the new identifier to use.
To send the identifier within an EE2E payload, we post a `DataTransfer` message containing the identifier to the self conversation.
In a future PR, this data transfer message will be received on other clients and processed.
> [Feature] Broadcast analytics identifier when generated

- Source/ManagedObjectContext/StorageStack+Backup.swift
Backups exported when EAR is enabled also have EAR enabled when imported which is not the expected behaviour.
When we create a backup we disable EAR for the backup but we were missing to persist the store metadata so the `encryptMessagesAtRest` flag was still set to `true` even though EAR had been disabled.
Persist store metadata.
> [Fix] Exporting backups under EAR

- Source/Model/FeatureConfig/AppLock/AppLockController.swift
- Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
Inject a `selfUser` into the `AppLockController` initializer and combine the AppLock rules from bundle and CoreData.
This PR is one in a series for refactoring for AppLock. Full description of refactoring you can find here:
wireapp/wire-ios-data-model#1078
> [Refactor] Add selfUser to AppLockController initializer

- Source/Model/Conversation/Team+Feature.swift
- Source/Model/FeatureConfig/Feature.swift
- Source/Model/FeatureConfig/FeatureLike.swift
- Tests/Source/Model/TeamTests.swift
We currently have an `enqueueBackendRefresh()` method that can trigger a BE to update the feature. Since we don't have any feature in the new entity of Core data, we should create a new default  feature and then trigger BE to update it.
> [Refactor] Modify enqueueBackendRefresh() to refresh  features

- Resources/zmessaging.xcdatamodeld/zmessaging2.88.0.xcdatamodel/contents
- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
- Source/Public/ZMMessage.h
- Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.swift
- WireDataModel.xcodeproj/project.pbxproj
When we insert a decryption error system message we now store the error code on the system message so we can display it to the user.
> [Feature] Expose decryption error code on system messages

- Source/Model/User/UserType.swift
- Source/Model/User/ZMSearchUser.swift
- Source/Model/User/ZMUser.swift
Add `isTrust` to `Usertype` for easier mocking.
Should `ZMSearchUser` `isTrust` always return false?
> add isTrust to UserType protocol

- Source/Model/User/ZMUser.m
App crashes on launch
In `[ZMUser updateWithTransportData:(NSDictionary *) authoritative:(Bool)]` we access the value stored in the dictionary at the `service` key.
The value returned is an instance of `NSNull`.
We expect that value to be an instance of `NSDictionary`.
Before we try to access its values, we check that it isn't `nil`.
However, since it is an instance of `NSNull`, it is not `nil`.
Consequently, we treat it as a `NSDictionary` and the app crashes.
use `optionalDictionaryForKey` to get the dictionary
> [Fix] app crash when `service` payload is null

- Source/Model/FeatureConfig/AppLock/AppLockController.swift
- Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
- Tests/Source/Utils/TransferApplockKeychainTests.swift
Remove `useCustomCodeInsteadOfAccountPassword` from the Feature.Config because we don't use it anymore in the UI. The fallback to unlock Wire is always a custom passcode.
> [Refactor] Remove useCustomCodeInsteadOfAccountPassword from the Feature.Config

- Source/Model/Account+Keychain.swift
- Source/Model/FeatureConfig/AppLock/AppLockController.swift
- Tests/Source/Model/AccountTests.swift
- WireDataModel.xcodeproj/project.pbxproj
We would like to be able to automatically delete the passcode keychain item when deleting an account. 
- It can happen that the app crashes when creating the passcode keychain item.
- There is no way to delete the passcode keychain item when deleting an account (in the sync engine).
- The keychain item is created when the `AppLockController` is initialized, which happens very early in the app cycle because it is a singleton. It can happen when logging with a new account, the the `remoteIdentifier` is not yet set on the `selfUser`, which is being implicitly forced unwrapped by the keychain item.
- Currently keychain item deletion is only possible through the `AppLockController`, but typically we only have a reference to `Account` when deleting accounts.
- Make the keychain item lazy.
- Add …
> [Fix] Passcode keychain item creation and deletion

- Source/ManagedObjectContext/NSManagedObjectContext+UpdateRequest.swift
- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Source/Model/Message/ZMMessage+Internal.h
- Source/Model/Message/ZMMessage.m
- Source/Model/UserClient/UserClient.swift
- Source/Public/ZMMessage.h
- Tests/Source/Model/UserClient/UserClientTests+ResetSession.swift
- WireDataModel.xcodeproj/project.pbxproj
Add a new system message type `.decryptionFailedResolved`. When a session is reset we will update all existing `.decryptionFailed` system messages to `.decryptionFailedResolved` to signal to the user that the decryption error has been fixed and there's no need to reset the session anymore.
The failing tests are due to not updated database migration tests and can be disregarded.
> [Feature] Add method for resolving past decryption failed system messages

- Source/Model/Message/ZMMessage.m
- Source/Public/ZMMessage.h
add `NSSet <id<UserType>>*userTypes` to `ZMSystemMessageData` to allow UI project to mock `ZMSystemMessageData` with `UserType` mocks.
> add userTypes to ZMSystemMessageData

- Source/Notifications/ObjectObserverTokens/MessageChangeInfo.swift
- Source/Notifications/ObjectObserverTokens/UserClientChangeInfo.swift
- In order to enable the UI react to when a session reset is completed I've added `sessionHasBeenReset` to the `UserClientChangeInfo`.
- Since system message will now change their type when a session is reset, I've added `systemMessageType` to the `observableKeys`.
The failing tests are due to not updated database migration tests and can be disregarded.
> [Feature] Support for observing session resets

- Patches/MigrateSenderClient.swift
- Patches/PersistedDataPatches+Directory.swift
- Tests/Source/Utils/MigrateSenderClientTests.swift
- WireDataModel.xcodeproj/project.pbxproj
We now set the `senderClientID` when inserting `.decryptionFailed` system messages since we need it to distinguish which client caused the decryption error. We also need to populate this field on any existing `.decryptionFailed` system messages otherwise they wouldn't get updated when the user resolves the decryption error (See https://github.com/wireapp/wire-ios-data-model/pull/1102)
> [Feature] Add migration of senderClientID for decryption error system messages

- Patches/PersistedDataPatches+Directory.swift
- Source/Model/Conversation/ZMConversation+SecurityLevel.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Participants.swift
We were getting reports that user's would end up with 1:1 conversations with the self user. 
This is likely a side effecting of the long existing issue of `localParticipants` relationship sometimes being reported as empty. If this would happen when receiving a message from the self user in a 1:1 conversation we would try re-establish the connection. This never makes for the self user though since he/she should never have a connection.
This bug was probably introduced with the addition of participant roles because then we started to include the self user in the `localParticipants` relationship  (previously named `activeParticipants`).
- Return early in `addParticipantAndSystemMessageIfMissing()` if it's the self user who's missing.
- Re-apply the patch which cleans up invalid connections …
> [Fix] Don't create connection with self user

- Source/Model/Conversation/ZMConversation+Timestamps.swift
- Tests/Source/Model/Conversation/ZMConversationTests+UnreadMessages.swift
There are some sync engine test failing due to the change in https://github.com/wireapp/wire-ios-data-model/pull/1097 that removed the optimization to update the last read server timestamp when a message was updated.
I'm reverting these changes now to unblock a release train and will address the fix in a separate PR.
> [Revert] Preventing last read update for updated messages

- Source/Model/Conversation/ZMConversation+Confirmations.swift
- Source/Model/Conversation/ZMConversation+Internal.h
- Source/Model/Conversation/ZMConversation+Timestamps.swift
- Source/Model/Conversation/ZMConversation.m
- Tests/Source/Model/Conversation/ZMConversationTests+Confirmations.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
An alternate solution for the issue first described in https://github.com/wireapp/wire-ios-data-model/pull/1097 and initially solved in https://github.com/wireapp/wire-ios-data-model/pull/1110 which was later reverted.
It can happen that read receipts are not being sent for some messages that expect them. For example, receive a message, but immediately after reading that message, send a new message. If it is sent within 3 seconds, the original message won't receive a read receipt.
The method which triggers the generation of read receipts (`enqueueMarkAsReadUpdate()`) uses an artificial delay of 3 seconds to throttle invocations to that method. If the method is called with a timestamp A, and meanwhile that conversation `lastReadServerTimeStamp` is advanced to a value greater than A, then …
> [Fix] Read receipts not sent for some messages

- Patches/TransferApplockKeychain.swift
- Tests/Source/Utils/TransferApplockKeychainTests.swift
Patch migration tests were failing on the simulator.
The shared container doesn't exist on the simulator and one of the app lock keychain migration tests was relying on it to create the account manager to migrate the custom passcode for all accounts at once.
It's not necessary to migrate all accounts at once, the migration will be performed individually for each account. Therefore, just migrate the passcode for the self user. To do this however, we must not delete the legacy passcode from the keychain.
I also decided not to hard crash if the migration fails. If it does fail, the worst that happens is that the user would need to create a new custom passcode, which isn't so bad.
> [Fix] App lock passcode migration 

- Source/ManagedObjectContext/StorageStack+Backup.swift
When trying to import an old Wire build it will sometimes fail with the message:
"Something went wrong: your history couldn't be restored"
Since https://github.com/wireapp/wire-ios-data-model/pull/1071 we open the backup db to prepare it for importing before we perform the actual import. When opening an old core data store it might need to be migrated before we can make any changes but we tried to open it with the following options:
```
let options = NSPersistentStoreCoordinator.persistentStoreOptions(supportsMigration: false)
```
This means that any backed up store which needs migration will fail to import.
Allow migration when opening store.
> [Fix] Can't import backups from old versions of Wire

- Source/Model/Message/ZMMessage.m
- Source/Public/ZMMessage.h
- Tests/Source/Model/Messages/ZMMessageTests+SystemMessages.swift
- WireDataModel.xcodeproj/project.pbxproj
Introduce `isDecryptionErrorRecoverable` to expose decryption errors which can be resolved by resetting the session.
> [Fix] Introduce isDecryptionErrorRecoverable

- Source/Public/ZMMessage.h
Existing system message would change type after upgrading to the latest version of Wire
New entries were added to the `ZMSystemMessageType` enum which is represented as integer in the database. Adding a new entry to the enum changes the integer associated for all cases after the new entry:
```
enum Foo {
case A = 0
case B = 1
}
enum Foo (edited) {
case A = 0
case C = 1
case B = 2
}
```
Add new entries at the end of the enum.
> [Fix] Existing system message changing type due to changed enum order

- Source/Model/Conversation/ConversationLike.swift
- Source/Model/Conversation/ZMConversation+AccessMode.swift
- Source/Model/Message/ConversationMessage.swift
- Tests/Source/Model/CoreDataRelationshipsTests.m
Move Conversation form UI project protocol to `ConversationLike`. Put the Swift only property in extension to protocol `SwiftConversationLike` and create a new alias `Conversation` to combine them.
> Move Conversation properties to ConversationLike

- Source/Model/Message/Composite/CompositeMessageItemContent.swift
- Source/Model/Message/ZMClientMessage+TextMessageData.swift
- Source/Public/ZMMessage.h
- Tests/Source/Model/Conversation/ZMConversationTests+Messages.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Editing.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Replies.swift
Add `quoteMessage` with type `ZMConversationMessage` to `ZMTextMessageData` to allow mocking `quota` with creating a `ZMMessage` managed object.
> Add quoteMessage to ZMTextMessageData

- Source/Model/Analytics/AnalyticsLike.swift
- WireDataModel.xcodeproj/project.pbxproj
This is a part of an ongoing effort to refactor the analytics system to align it to the implementation spec and improving and cleaning up the code along the way.
**Define a new and simpler analytics interface.** It may be extended later if needed and will eventually replace `AnalyticsType`.
**Add type safety.** At the lowest level, events and attributes are stringly typed. By defining types for events, attribute keys and attribute values, we can avoid typo errors that lead to inconsistencies. By defining `AnalyticsAttributeKey` as a struct, we are not limiting the range of possible keys (as would happen with an enum) and can use static constants to improve usability, such as
```swift
extension AnalyticsAttributeKey {
static let conversationType = AnalyticsAttributeKey(rawValue: …
```
> Define AnalyticsLike (Part 1)

- Source/Model/Analytics/AnalyticsAttributeKey.swift
- Source/Model/Analytics/AnalyticsAttributeValue.swift
- Source/Model/Analytics/AnalyticsAttributes.swift
- Source/Model/Analytics/AnalyticsEvent.swift
- Source/Model/Analytics/AnalyticsLike.swift
- Source/Model/Analytics/Dictionary+AnalyticsRawValue.swift
- WireDataModel.xcodeproj/project.pbxproj
This is a part of an ongoing effort to refactor the analytics system to align it to the implementation spec and improving and cleaning up the code along the way.
- Add conformances to `AnalyticsAttributeValue` for various types.
- Add a helper extension to produce a stringly typed dictionary. Useful to avoid repeatedly converting type safe attribute dictionaries.
- Move types to separate files for better readability.
> Add conformances to AnalyticsAttributeValue (Part 2)

- Source/Model/Conversation/ConversationLike.swift
Add `mutedMessageTypes` to `SwiftConversationLike` protocol to allow mocking that property.
> add mutedMessageTypes to SwiftConversationLike

- Patches/InvalidFeatureRemoval.swift
- Patches/PersistedDataPatches+Directory.swift
- Source/Model/Conversation/Team+Feature.swift
- Source/Model/FeatureConfig/AppLock/AppLockController.swift
- Source/Model/FeatureConfig/Feature.swift
- Source/Model/FeatureConfig/FeatureLike.swift
- Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
- Tests/Source/Model/FeatureConfiguration/FeatureLikeTests.swift
- Tests/Source/Model/FeatureConfiguration/FeatureTests.swift
- Tests/Source/Model/TeamTests.swift
- Tests/Source/Utils/InvalidFeatureRemovalTests.swift
- WireDataModel.xcodeproj/project.pbxproj
We assert that there can only be a maximum of one instance of `Feature` for any given feature name, however this assertion is failing sometimes.
While we have checks to only insert a feature instance if none is present, it is possible that two instance can be created simultaneously from different contexts.
Previously we were trying to create default instances when trying to fetch an instance and finding that it wasn't created yet. This is a **lazy** approach.This over-complicates things and makes it difficult to reason about when we're inserting feature instances and in which context.
Instead I think we should take an **eager** approach and try to create the default instances (if needed) as early as possible so that it is available for use immediately. This simplifies things a lot since …
> [Fix] Feature insertion race condition

- Source/Model/Conversation/ConversationLike.swift
- Source/Model/Conversation/ZMConversation+AccessMode.swift
Add `verifyLegalHoldSubjects` and `sortedActiveParticipantsUserTypes` to `ConversationLike` protocol to allow legal hold tests in UI project to mock these properties.
> add verifyLegalHoldSubjects and sortedActiveParticipantsUserTypes to ConversationLike

- Source/Model/Confirmation/ZMMessageConfirmation.swift
- Source/Model/Message/ConversationMessage.swift
Add `UserType` property `userType` to `ReadReceipt` protocol to allow mocking `NSManaged` `user` property
> Add UserType getter to ReadReceipt

- Source/Model/Analytics/AnalyticsAttributeValue.swift
- Tests/Source/Utils/AnalyticsAttributeValueTests.swift
- WireDataModel.xcodeproj/project.pbxproj
In order to protect the privacy of BI data, numeric attribute values should be rounded. Previously this was done on the UI side by adding an extension to `Int` to round the value. This is error prone because you need to remember to round the int value.
A more type safe solution is to remove the `Int` conformance of `AnalyticsAttributeValue` and instead define a `RoundedInt` container.
> Define RoundedInt (Part 3)

- Source/ManagedObjectContext/NSPersistentStoreCoordinator+Wire.swift
After https://github.com/wireapp/wire-ios-data-model/pull/1144 we now show the DB migration screen on every app launch.
We removed a rule for only migrating the database when the model version has changed since that path killing the app on any error.
The path for killing the app no longer exists after some further refactoring so we can restore the old behaviour of only attempting a migration when the model version changed.
> [Fix] Restore logic for only migrating when model version changed

- Source/ManagedObjectContext/ManagedObjectContextDirectory.swift
Revert https://github.com/wireapp/wire-ios-data-model/pull/1149 since it breaks the SE tests. This change will come with https://github.com/wireapp/wire-ios-data-model/pull/1151 instead.
> [Chore] Revert "Release 251.0.2"

- Source/Model/Conversation/ZMConversation+ExternalParticipant.swift
- Source/Model/User/UserType+External.swift
- Tests/Source/Helper/ZMBaseManagedObjectTest+Helpers.swift
- Tests/Source/Model/Conversation/ZMConversationExternalParticipantsStateTests.swift
- WireDataModel.xcodeproj/project.pbxproj
As part of the UI improvement, we should update the "External users" banner and display an additional case where external partners are present in the conversation. For this reason, we need to extend the existing  `ExternalParticipantsState`. 
https://wearezeta.atlassian.net/browse/SQSERVICES-394
> [Feature] Add a new state to the ExternalParticipantsState for a conversation

- Source/Model/Conversation/ZMConversation+Predicates.swift
- Tests/Source/Model/Observer/ConversationListObserverTests.swift
Since we have a new connection status `blockedMissingLegalholdConsent`, we should exclude these conversations from the valid conversation list.
> [Fix] Update predicate for valid conversations

- Source/Model/Message/ConversationMessage+Reaction.swift
- Source/Model/Message/ZMClientMessage+LinkPreview.swift
- Source/Utilis/Protos/GenericMessage+Helper.swift
- Tests/Source/Model/Messages/GenericMessageTests+LegalHoldStatus.swift
- Tests/Source/Model/Messages/GenericMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessagesTests+Reaction.swift
- Tests/Source/Model/Utils/PBMessageValidationTests.swift
When data model is build as a XCFramework and link with other frameworks, compile error occurs.
`Designated initializer cannot be declared in an extension of 'Mention'` and similar error for `Reaction`
User static method instead of `init` in extensions. 
Add `typealias WireProtosMention = WireProtos.Mention` to prevent linker ambiguity issue when linking this framework.
> Fix: Designated initializer cannot be declared in an extension of 'Mention'

- Source/Utilis/Protos/GenericMessage+Helper.swift
After https://github.com/wireapp/wire-ios-data-model/pull/1169, request strategy still can not found `WireProtos.Mention.createMention` method when import Data modal via XCFramework
`WireProtos.Mention` and `WireDataModel.Mention` are ambiguous when linking
Since `WireDataModel.Mention` is found by the linker, I created a method of `WireDataModel.Mention` to convert `WireDataModel.Mention` to `WireProtos.Mention` and use it in request strategy.
> fix ambiguous mention extension

- Source/Utilis/Protos/GenericMessage+Helper.swift
When testing conversion to XCFramework, `WireProtos.Reaction.createReaction` can not be found. Similar PR: https://github.com/wireapp/wire-ios-data-model/pull/1170
generated Swift interface can not find method `createReaction` under `WireProtos.Reaction`, seems it has ambiguity between `WireProtos.Reaction` & `WireDataModel.Reaction`.
Create a container enum `ProtosReactionFactory` wrapper to solve the namespace issue.
> Add ProtosReactionFactory to fix WireProtos.Reaction extension not generated correct in Swift interface

- Source/Model/Message/ZMClientMessage+Encryption.swift
- Source/Model/ZMManagedObject.m
Refactor the message sending so that all strategies rely on a single code path for sending messages. This reduces code * test duplication.
- `updateUnderlayingMessageBeforeSending()` has been moved to data model so that it can be shared among strategies.
- Don't hardcode the  `remoteIdentifierDataKey`
> [Refactor] Message sending

- Tests/Source/Model/Messages/ZMMessageTests.m
- Tests/Source/Model/Messages/ZMMessageTests.swift
- WireDataModel.xcodeproj/project.pbxproj
After converting to XCFramework, test compile failed for:
```
Symbol: _OBJC_CLASS_$__TtC13WireDataModel15ZMClientMessage
Referenced from: objc-class-ref in ZMMessageTests.o
```
Unknown, but seems related to `@objcMembers` signature of ZMClientMessage
Convert `ZMMessageTests. testThatSpecialKeysAreNotPartOfTheLocallyModifiedKeysForClientMessages` to swift
> Convert testThatSpecialKeysAreNotPartOfTheLocallyModifiedKeysForClientMessages to Swift

- Source/Model/Message/RasterImages+Protobuf.swift
When running test on M1 Mac iOS simulator, `UTType(mimeType: )` always return nil and cause `hasRasterImage` always false
Unknown
As a workaround, check `mimeType` is SVG to return it is a raster image or not.
related PR:
https://github.com/wireapp/wire-ios-images/pull/43
> Fix: UTType init returns nil on M1 Mac

- Tests/Source/Model/Messages/ZMMessageTests.h
- Tests/Source/Model/Messages/ZMMessageTests.m
- Tests/Source/Model/Messages/ZMMessageTests.swift
Convert `testThatFlagIsNotSetWhenSenderIsNotTheOnlyUser` to swift for preparing create a protocol for `ZMUpdateEvent`
> convert testThatFlagIsNotSetWhenSenderIsNotTheOnlyUser to Swift

- Source/Model/Message/ConversationMessage.swift
Add `isRestricted` property to `ZMConversationMessage` which we can use and mock in the UI project.
> [Feature] Add isRestricted property to ZMConversationMessage protocol

- Source/ManagedObjectContext/CoreDataStack.swift
- Source/Model/ZMManagedObject+Fetching.swift
- Source/Model/ZMManagedObject+Internal.h
- Source/Model/ZMManagedObject.m
- Tests/Source/Model/ZMManagedObjectFetchingTests.swift
If a client for some reason ended up with federated user in their database it could in theory introduce a collision with a local user.
If `fetch(with remoteIdentifier: UUID, domain: String?, in context: NSManagedObjectContext)` was called without a domain and the self doesn't have domain assigned it would end up with the following fetch request:
```
"remoteIdentifier == %@"
```
which doesn't match on the domain and therefore could return a federated user.
Ensure that domain is nil or equal to the self user domain when searching for local users.
> [Feature] Avoid unintentionally fetching federated users

- Source/Model/FeatureConfig/Feature.swift
- Source/Model/FeatureConfig/FeatureService.swift
- Tests/Source/Model/FeatureConfiguration/FeatureTests.swift
**Jira:** https://wearezeta.atlassian.net/browse/SQSERVICES-541
In this PR we do some refactoring to support showing an alert to the user when the self-deleting message config changes:
- Move responsibility to post feature change notifications to the `FeatureService`.
- Extend the `FeatureChange` type to include changes for other feature configs.
I found that there are two ways that we notify the ui layer of config changes:
1. posting a notification when receiving an update event (in the request strategy project) 
2. posting a notification when setting properties on the `Feature` entity.
3. General clean up along the way
> Self-deleting message config (part 2)

- Tests/Source/Model/ZMConnectionTests.m
Fix the duplicated KVP in dictionary detected by Xcode 13
> Fix: duplicate KVP in dictionary

- Source/Model/User/ZMUser+Permissions.swift
Application would crash in `isGuest(in:)` when perform data model patches which delete objects
`managedObjectContext` is force unwrapped on a user object where it is nil because the object has been deleted.
Guard unwrap the context.
> Fix: Crash in isGuest(in:)

- Source/Public/DraftMessage.swift
App sometimes crashes when accessing `draftMessage`
If conversation in question has just been deleted the `managedObjectContext` can be nil.
Unwrap the `managedObjectContext` before using it.
> Fix: Don't crash when accessing draft message on a deleted conversation

- Patches/InvalidDomainRemoval.swift
- Patches/PersistedDataPatches+Directory.swift
- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.h
- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m
- Source/Model/Conversation/ZMConversation+Creation.swift
- Source/Model/Conversation/ZMConversation+Deletion.swift
- Source/Model/Message/FileAssetCache.swift
- Source/Model/Message/V2Asset.swift
- Source/Model/Message/V3Asset.swift
- Source/Model/User/ZMUser+Create.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+Deletion.swift
- Tests/Source/Model/User/ZMUserTests.m
- Tests/Source/Utils/InvalidDomainRemovalTests.swift
- WireDataModel.xcodeproj/project.pbxproj
There are instances of Wire servers which share the same database but run on different domains. This causes the iOS client to stop receiving  and sending messages in some cases.
In this multi domain setup it's possible to login to account A1 on server S1 (domain: s1.com) and on server S2 (domain s2.com) since they both share the same database. When this user sends a message from S1 the qualified ID of the sender will be (uuid: 123, domain: s1.com) and when it's sent from S2 the qualified ID will be (uuid: 123, domain: s2.com).
The iOS client will treat these qualified IDs as coming from different user since the domain is different and thus insert a user object for each one of them. This causes problems since they are actually referring to the same user on the backend.
- Ignore the domain …
> Fix: Handle conflicting domains FS-119

- Source/Model/Conversation/ZMConversation+Participants.swift
- Source/Model/ConversationRole/ParticipantRole.swift
- Source/Model/User/ZMUser+Availability.swift
- Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Transport.swift
- Tests/Source/Utils/SelfUserParticipantMigrationTests.swift
App crashes in `[ZMConversation refreshObjectsThatAreNotNeededInSyncContext:self]`
When fetching the `localParticipants` the app crashes if a `ParticipantRole` doesn't have user since it's declared as non-optional. However when deleting users there's no current rule to delete the corresponding `ParticipantRole` the user can actually be nil.
Declare `user` as optional.
> Fix: App crashes in [ZMConversation refreshObjectsThatAreNotNeededInSyncContext:self]

- Source/Utilis/PINCache+ZMessaging.swift
When this framework is built with downstream request strategy, compile fails
```
Compiling AppDelegate.swift
[21:29:59]: ▸ ❌  /Users/runner/work/1/s/DerivedData/Build/Products/Debug-iphonesimulator/WireDataModel.framework/Modules/WireDataModel.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:2878:20: 'PINCache' is not a member type of class 'PINCache.PINCache'
[21:29:59]: ▸ extension PINCache.PINCache {
```
Seems it is a namespace issue of we also encountered when building other framework. Remove the public access since the helpers are only used in this framework.
> Fix: downstream framework can not compile Xcode 13 framework

- Source/Model/FeatureConfig/Feature.swift
- Source/Model/User/ZMUser+Permissions.swift
1. Remove the `selfDeletingMesssages` status check from `canModifyEphemeralSettings()` method, and with these changes, we allow ephemeralSettings for conversations to be changed despite the feature flag status. More context you can find [here](https://wearezeta.atlassian.net/browse/SQSERVICES-955).
2. Set `hasInitialDefault` to **false** after updating the status and config data.
> [Fix] Setup hasInitialDefault property

- Source/Model/Connection/ZMConnection+Fetch.swift
App would crash on login due to hitting an assertion about corrupted connection data
When fetching connections from core data during the slow sync we would start fetching the wrong connection if we had a connection without the `to` field populated. 
This would happen because the fetch predicate ends with `|| to.domain == NULL`, which is always true if the `to` field is not populated.
this was surfaced after https://github.com/wireapp/wire-ios-data-model/pull/1254 was merged since now we don't assign the domain if federation is not enabled.
Add the missing `(` `)` to get the expected priority for the statements.
> Fix: returning the wrong connection causing data corruption and crashes SQCORE-1161

- Source/ManagedObjectContext/CoreDataStack.swift
There's a crash when we try to update the public version from TestFlight.
We create default feature configs in a sync context, but fetch them in a view context. This could be the cause of the crash.
Create default feature configs in the view context and save the context.
> [Fix] App crashes after update

- Source/ConversationList/ConversationDirectory.swift
- Source/Model/AccountDeletedObserver.swift
- Source/Model/Conversation/Team.swift
- Source/Model/Message/TextSearchQuery.swift
- Source/Model/User/ServiceUser.swift
----
----
Replace all protocol extends class with AnyObject
> Fix: xcode13 warning - Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead

- Resources/zmessaging.xcdatamodeld/zmessaging2.97.0.xcdatamodel/contents
- Tests/Source/Utils/InvalidConversationRemovalTests.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQCORE-1178" title="SQCORE-1178" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10803&avatarType=issuetype" />SQCORE-1178</a>  [iOS] ParticipantRole has invalid deletion rule
</td></table>
<br />
----
----
When batch deleting a conversation an exception is thrown:
```
error: Unhandled opt lock error from executeBatchDeleteRequest Constraint trigger violation: Batch delete failed due to manadatory OTM nullify inverse on Conversation/participantRoles and userInfo {
NSExceptionOmitCallstacks = 1;
NSLocalizedFailureReason = "Constraint trigger violation: Batch delete failed due to manadatory OTM nullify inverse on …
```
> Fix: Crash when batch deleting conversations SQCORE-1178

- .github/workflows/semantic-commit-lint.yml
----
----
We want to ensure that PR titles follow semantic commit rules
Add the semantic commit linter workflow from Wire's .github repo
N/A
----
----
----
> ci: Add semantic commit lint of PR titles SQPIT-769

- Patches/PersistedDataPatches.swift
- Tests/Source/Utils/PersistedDataPatchesTests.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1031" title="SQSERVICES-1031" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10803&avatarType=issuetype" />SQSERVICES-1031</a>  [iOS] Release build crashes
</td></table>
<br />
----
----
In the testflight build, we are observing that the data model patches are being run when they shouldn't be. This leads to database corruption and eventually crashes. 
It appears that the framework version number is old and therefore the app thinks it's updating from a very old version so it applies historical patches.
To test this idea, we need to know exactly which version number is being stored and retrieved. Since we can't debug …
> chore: add public logs for db patches to assist crash debugging SQSERVICES-1031

- Patches/PersistedDataPatches.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1031" title="SQSERVICES-1031" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10803&avatarType=issuetype" />SQSERVICES-1031</a>  [iOS] Release build crashes
</td></table>
<br />
----
----
The database patches should only we run when the app has upgraded and uses a new data model version, but we are observing that they're running all the time, even on a fresh install.
The current version of the framework is fetched from the framework bundle, which is used to determine whether the patches should be run. For some reason, when this code is run in the testflight app, the Bundle we retrieve is actually the main app bundle, …
> fix: use private class for fetching framework bundle SQSERVICES-1031

- .github/workflows/mergePR.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-773" title="SQPIT-773" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQPIT-773</a>  update Github action merge PR to update version.xcconfig
</td></table>
<br />
----
----
Recent framework release does not update `version.xcconfig`
It was done by Jenkins script, after we use `mergePR` action this feature is not included
Add this feature to mergePR action.
This action is tested in https://github.com/wireapp/wire-ios-canvas/pull/33
Add @agisilaos and @sb88k to admin list so that they can use this spell
> fix: update merge spell action to bump version.xcconfig SQPIT-773

- WireDataModel.xcodeproj/project.pbxproj
----
----
By default, Xcode can't find any packages installed by homebrew on Apple Silicon Macs, since they're now installed to a different location that isn't on the default $PATH (`/opt/homebrew/bin/`, rather than `/usr/local/bin`).
Workaround: explicitly add this location to `$PATH` before attempting to run `SwiftLint`.
----
> chore: SwiftLint add support for Apple Silicon brew directory

- .swiftlint.yml
- Source/Model/Conversation/AssetCollectionBatched.swift
- Source/Model/User/PersonName.swift
- Tests/Source/Model/Conversation/AssetCollectionBatchedTests.swift
- Tests/Source/Model/Conversation/AssetColletionTests.swift
- Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
- Tests/Source/Model/Observer/ChangedIndexesTests.swift
- Tests/Source/Utils/BatchDeleteTests.swift
----
----
This PR fixes errors and warnings related two SwiftLint rules:
**Reduce Boolean Violation**: Use `allSatisfy` instead `(reduce_boolean)`
**Shorthand Operator Violation**: Prefer shorthand operators (+=, -=, *=, /=) over doing the operation and assigning. `(shorthand_operator)`
----
> fix: SwiftLint warnings for rules `shorthand_operator` and `reduce_boolean`

- Source/Model/Conversation/ZMConversation+AccessMode.swift
- Tests/Source/Model/Conversation/AccessRoleMappingTests.swift
- Tests/Source/Utils/RolesMigrationTests.swift
- WireDataModel.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1052" title="SQSERVICES-1052" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />SQSERVICES-1052</a>  [iOS] Separate access controls for guests and services
</td></table>
<br />
----
----
This PR, introduces the mapping between the old access role and the new one. This is an essential part for the separation of access controls for guests and services. The reason why is because backend and clients should implement the same logic (send both fields, accept either, and translate everything to the new values). The mapping will help us achieve just that.
These two methods are going to be …
> fix: Introduce mapping for accessRole and accessRoleV2 for the separation of access controls for guests and services SQSERVICES-1052

- .swiftlint.yml
- Source/Model/Conversation/Permissions.swift
- Source/Model/Conversation/ZMConversation+AccessMode.swift
- Source/Model/Message/ZMMessage+Categorization.swift
- Source/Model/User/PersonName.swift
- Tests/Source/Model/User/ZMUserTests+Swift.swift
----
----
This PR fixes SwiftLint warnings related to two rules:
- **Legacy Hashing Violation**: Prefer using the `hash(into:)` function instead of overriding `hashValue` `(legacy_hashing)`
- **Legacy Constructor Violation**: Swift constructors are preferred over legacy convenience functions. `(legacy_constructor)`
In addition to that I fixed a couple of indentation issues. Last but not least I removed `multiple_closures_with_trailing_closure` from the list since it didn't produce any warnings or errors.
----
> fix: SwiftLint warnings for `legacy_constructor` and  `legacy_hashing`

- Source/Utilis/APIVersion.swift
- Tests/Source/Utils/APIVersionTests.swift
- WireDataModel.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-422" title="FS-422" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-422</a>  [iOS] Clients need to know if the backend support federated endpoints or not
</td></table>
<br />
----
----
- Moved `APIVersion` from RS to DM
- Added accessors for domain and federation flag
----
----
----
> feat: add api version accessors for domain and federation flag - FS-422

- Tests/Source/ManagedObjectContext/CoreDataStackTests+EncryptionAtRest.swift
- Tests/Source/ManagedObjectContext/NSManagedObjectContextTests+EncryptionAtRest.swift
- Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTests.swift
- Tests/Source/Model/User/ZMUserTests+Permissions.swift
- Tests/Source/Utils/EncryptionKeysTests.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-897" title="SQPIT-897" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQPIT-897</a>  Create BSI documentation containing test cases for Federation M3
</td></table>
<br />
----
----
Some test cases were hard to understand. It was sometimes not clear what "it" stands for in the test name.
Added comments and updated test name titled. Additionally deleted some mapping for tests which were marked without being actually relevant for security testing.
----
----
----
1. E.g. …
> chore: Rename and comment test cases and delete mapping from non-security relevant ones SQPIT-897

- Source/Model/Conversation/ZMConversation+Creation.swift
- Source/Model/User/ZMUser+Create.swift
- Tests/Source/Model/Conversation/ZMConversationTests.m
- Tests/Source/Model/Conversation/ZMConversationTests.swift
- Tests/Source/Model/User/ZMUserTests+Swift.swift
- Tests/Source/Model/User/ZMUserTests.m
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-484" title="FS-484" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-484</a>  [iOS] Use federation flag to decided when to use fully qualified ids
</td></table>
<br />
----
----
use `APIVersion` federation flag to ignore domain when creating users and conversations
----
----
----
> feat: use `APIVersion` federation flag to ignore domain when creating users and conversations FS-484

- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.h
- Source/ManagedObjectContext/NSManagedObjectContext+zmessaging.m
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-514" title="FS-514" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-514</a>  [iOS] Remove old federation flag
</td></table>
<br />
----
----
Remove the old federation feature flag since it has been replaced with API versioning.
----
----
----
> chore: remove old federation flag FS-514

- Source/ManagedObjectContext/NSManagedObjectContext+CoreCrypto.swift
- WireDataModel.xcodeproj/project.pbxproj
----
----
Moving the extension of `NSManagedObjectContext` providing the core crypto accessor to the data model layer in order to make it accessible to the frameworks that need it
> chore: move core crypto accessor

- MLS/Bytes+Random.swift
- MLS/CoreCryptoTypes.swift
- MLS/MLSController.swift
- Source/Model/Message/GenericMessage+UpdateEvent.swift
- Source/Utilis/ZMUpdateEvent.swift
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockCoreCrypto.swift
- Tests/MLS/MockMLSController.swift
- Tests/Source/Helper/XCTestCase+ErrorAssertion.swift
- WireDataModel.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-650" title="FS-650" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-650</a>  [iOS] Receive an MLS message
</td></table>
<br />
----
----
This PR introduces support for decrypting MLS messages.
- Added `decrypt` method to `MLSController`
- Added support to init a `GenericMessage` from an update event of type `.conversationMLSMessageAdd`
- Added unit tests for the `decrypt` method
- Added mock of `decrypt` method
- Introduced `XCTestCase+ErrorAssertion` extension to help simplify errors and throws assertions 
----
----
----
1. …
> feat(mls): add support for decrypting messages FS-650

- MLS/Actions/SendMLSMessageAction.swift
- MLS/MLSController.swift
- Source/ManagedObjectContext/NSManagedObjectContext+MLSController.swift
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockConversationEventProcessor.swift
- Tests/MLS/MockMLSActionsProvider.swift
- WireDataModel.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-542" title="FS-542" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-542</a>  [iOS] Add a user to an MLS group
</td></table>
<br />
----
----
We forgot to implement the update events that are returned when posting the mls handshake messages. This PR:
- Changes the result type of `SendMLSMessageAction` from `Void` to `[ZMUpdateEvent]`.
- Defines a `ConversationEventProcessorProtocol` which is some object that will process the events.
- Adds an instance of the event processor to the `MLSController`, it will be injected from other layers.
- Pass the events received from the message action …
> feat: mls conversation event processing FS-542

- MLS/MLSController.swift
- Source/Model/Conversation/ZMConversation+MLS.swift
- Tests/Source/Model/Conversation/ZMConversationTests+MLS.swift
- WireDataModel.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-544" title="FS-544" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-544</a>  [iOS] Process incoming welcome
</td></table>
<br />
----
----
Add the possibility to fetch a conversation with the group id. This is useful when we need to process the incoming welcome message and only have the group id rather than the usual remote identifier.
- unit test for fetching the conversation.
----
----
----
> feat(mls): fetch conversations with mls group id FS-544

- MLS/MLSClientID.swift
- MLS/MLSController.swift
- Source/Model/Conversation/ZMConversation+Participants.swift
- Source/Utilis/String+Bytes.swift
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockMLSController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-546" title="FS-546" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-546</a>  [iOS] Admin removes a user from an MLS group
</td></table>
<br />
----
----
- Added `removeMembersFromConversation` method in `MLSMLSController`.
- Added the call of in `ZMConversation+Participants` and handled the case for proteus and mls.
- Added tests for `removeMembersFromConversation` in `MLSMLSController`.
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title …
> feat: mls remove user from mls group FS-546

- MLS/CoreCryptoTypes.swift
- MLS/MLSController.swift
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockCoreCrypto.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-859" title="FS-859" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-859</a>  [iOS] Update CoreCrypto
</td></table>
<br />
----
----
- Update CoreCrypto to 0.3.1 by updating the Core Crypto protocol wrapper.
- Updating mocks
- Updating tests
- Calling `commitAccepted` when a handshake message is successfully sent
[Change notes for 0.3.0:](https://github.com/wireapp/core-crypto/blob/v0.3.0/CHANGELOG.md#030---tbd)
- updated tests
----
----
----
1. E.g. `feat(conversation-list): Sort …
> chore(mls): update core crypto to 0.3.1 FS-859

- Source/Model/Message/ZMMessage+Conversation.swift
- Source/Model/Message/ZMMessage.m
- Source/Utilis/ZMUpdateEvent+WireDataModel.m
- Tests/Source/Model/Messages/ZMMessageTests.m
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-675" title="FS-675" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-675</a>  [iOS] Distribute CONFKEY to all members of conversation [temp-M4]
</td></table>
<br />
----
----
Some logic around processing update events for new messages are failing for messages sent with mls.
An example is that when receiving a call message, we rely on the sender id in the update event. The sender id is extracted from the payload, but only if the event type is `conversationOtrMessageAdd` or `conversationOtrAssetAdd`. If it's an mls message, we will always return `nil`, even though the sender id exists. …
> fix(mls): add `conversationMLSMessageAdd` to missing checks FS-675

- MLS/MLSController.swift
- Resources/zmessaging.xcdatamodeld/zmessaging2.105.0.xcdatamodel/contents
- Source/Model/Conversation/ZMConversation+MLS.swift
- Source/Model/Conversation/ZMConversation.m
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockMLSController.swift
- Tests/Source/Model/Conversation/ZMConversationTests+MLS.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-688" title="FS-688" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-688</a>  [iOS] Send external proposal to join group I am already in
</td></table>
<br />
----
----
This PR takes care of sending external add proposals to join MLS conversations that are `pendingJoin`
- added `epoch` property to `ZMConversation`
- added implementation to send external add proposals
- small refactor of the `sendMessage` method
- Added tests to `MLSControllerTests`
- Updated some error-asserting tests 
----
----
----
1. …
> feat(mls): send external add proposals FS-688

- MLS/CoreCryptoTypes.swift
- MLS/MLSController.swift
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockCoreCrypto.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-963" title="FS-963" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-963</a>  [iOS] Update to Core Crypto 0.5.1
</td></table>
<br />
----
----
- Update Core Crypto to 0.5.0.
- Refactor how we mock Core Crypto: 
- Instead of providing a mock result or a mock error, provide a mock function
- Remove the `Calls` struct that counts the invocations of methods... it's hard to maintain and not necessary, since we can make assertions in the mock functions.
- Update tests to account for the new mock approach.
----
----
----
1. …
> chore: update to Core Crypto 0.5.0 FS-963

- MLS/MLSController.swift
- Source/Model/Conversation/ZMConversation+Participants.swift
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockMLSController.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Participants.swift
----
----
This PR introduces support for leaving MLS groups. When leaving an MLS group, we need to follow the same flow as with proteus, but we also need to ask core crypto to wipe the group from the local database. 
We need to make a distinction between removing other participants from the group and removing the self user from the group: 
- When removing others, we ask core crypto to remove members, which returns a commit that we then send to the group. 
- When removing the self user, we should use the `RemoveParticipantAction` which will ask the backend to remove the user. The backend then notifies the user's clients that they've been removed and this is where we'll ask core crypto to wipe the conversation (in RS). 
- Added a `wipeGroup` …
> feat(mls): leave conversation

- MLS/MLSController.swift
- MLS/MLSGroup.swift
- MLS/StaleMLSKeyMaterialDetector.swift
- Resources/zmessaging.xcdatamodeld/zmessaging2.105.0.xcdatamodel/contents
- Source/Model/Conversation/ZMConversation+MLS.swift
- Source/Utilis/Date+Helpers.swift
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockStaleMLSKeyDetector.swift
- Tests/MLS/StaleMLSKeyDetectorTests.swift
- Tests/Source/Helper/ZMBaseManagedObjectTest+Helpers.swift
- WireDataModel.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-547" title="FS-547" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-547</a>  [iOS] Send commit(UpdatePath) periodically
</td></table>
<br />
----
----
This PR adds functionality to automatically update key material for each MLS group with key material older than 90 days. Changes include:
- Add new entity `MLSGroup`, which is just an MLS Group id and `lastKeyMaterialUpdate`. It can be used in the future to contain other MLS group metadata.
- Store the last key update date when the key material is first created (new group, joined group) or updated
- Add `StaleMLSKeyMaterialDetector` …
> feat(mls): automatically update key material FS-547

- MLS/StaleMLSKeyMaterialDetector.swift
----
----
The app was crashing when updating key material.
We were fetching core data entities from the wrong thread.
Switch to the correct thread to fetch objects.
----
----
----
> fix(mls): fetch objects from correct thread

- MLS/MLSGroup.swift
----
----
The app crashes because somewhere in the sync logic it tries to call `modifiedKeys` (objc code) on `MLSGroup` (swift code), which isn't implemented. 
Mark `MLSGroup` as not being tracked for local modifications.
Tested manually.
----
----
----
> chore(mls): don't track local modifications

- MLS/MLSController.swift
- Source/ManagedObjectContext/NSManagedObjectContext+MLSController.swift
- Tests/MLS/MLSControllerTests.swift
----
----
Key packages were not uploaded when logging in with a new client after logging out
The decision to replenish key packages depends on the last time we checked if there are enough key packages. If the last check happened less than 24 hours ago, we don't replenish key packages. Otherwise, we do.
We store the date of the last time we checked key packages in the `UserDefaults` under the suite name `com.wire.mls`. This means that the date saved under theses user defaults is shared between all the user's accounts.
What happens then is:
- We have a fresh Wire app
- User A logs in with client A.1. It checks the date in the user defaults, which is nil, and decides to upload key packages
- User A logs out
- User A logs in with client A.2. The …
> fix(mls): replenish key packages

- MLS/MLSController.swift
- Source/Model/Message/GenericMessage+UpdateEvent.swift
- Source/Model/Message/ZMOTRMessage+UpdateEvent.swift
- Tests/MLS/MLSControllerTests.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-973" title="FS-973" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-973</a>  [iOS]: Sharing of assets in mls group doesn't work from Web to iOS
</td></table>
<br />
----
----
Assets sent from web clients fail to be downloaded on iOS clients
When assets are sent from web, we receive two messages. The first message lets us know about the asset so we can show a placeholder, and the second message lets us know that the asset was uploaded. These messages have the same identifier.
When we receive the first message as an update event, we create a `ZMAssetClientMessage` and insert it in the …
> fix(mls): sharing of assets from web to iOS FS-973

- MLS/MLSController.swift
- Source/Model/Conversation/ZMConversation+Participants.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-876" title="FS-876" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-876</a>  [iOS] Admin cannot add participants to an existing MLS group through group details page 
</td></table>
<br />
----
----
If adding a participant failed, the app would crash.
The log message uses a property of a Core Data entity, but we're not on the context's thread.
Capture the property outside of the task.
Manually tested.
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in …
> fix(mls): crash when adding a participant FS-876

- MLS/CoreCryptoActor.swift
- MLS/MLSActionExecutor.swift
- MLS/MLSController.swift
- Tests/MLS/MLSActionExecutorTests.swift
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockMLSActionExecutor.swift
- WireDataModel.xcodeproj/project.pbxproj
----
----
It's possible to interleave MLS commits, which results in error. For instance, we may try to commit pending proposals in to 2 different groups. Each action involves generating the commit via CoreCrypto, sending it to the backend, and merging the commit when the backend responds with a success. If we try to generate the second commit before we've merged the first commit, CoreCrypto will throw an error.
Make the flow of `generate commit -> send commit -> merge commit` atomic. From a concurrency point of view, this flow is a critical section where we need to ensure mutual exclusion. To do this, we make use a Swift's `actor` concurrency type to ensure mutual exclusion for specific methods and shared resources. The shared resource in this …
> feat(mls): make commits atomic

- MLS/Actions/SendMLSMessageAction.swift
- MLS/MLSActionExecutor.swift
- MLS/MLSController.swift
- MLS/SyncStatusProtocol.swift
- Source/ManagedObjectContext/NSManagedObjectContext+MLSController.swift
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockSyncStatus.swift
- WireDataModel.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1039" title="FS-1039" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-1039</a>  [iOS] Handle network errors when sending a commit
</td></table>
<br />
----
----
This PR implements retrying operations when the commit fails to be sent to the backend. There are three strategies to take, depending on the type of server error:
- give up:  there is no way to recover, so we just give up and notify the user
- discard the pending commit, perform a quick sync (to process any incoming mls messages), then try the operation again (creating a new commit)
- keep the commit, perform a quick sync, …
> feat(mls): retry operations on commit failure FS-1039

- MLS/MLSActionExecutor.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-876" title="FS-876" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-876</a>  [iOS] Admin cannot add participants to an existing MLS group through group details page 
</td></table>
<br />
----
----
When I add participants to an mls group (old or new), it always fails.
When adding participants to a group, we first try to commit pending proposals if any exist. None exist, and we throw the error `noPendingProposals`. This error then gets caught and converted to a `failedToGenerateCommit` error. This error gets caught and stops the flow of adding participants.
We shouldn't stop the flow …
> fix(mls): can't add participants to existing group FS-876

- MLS/MLSController.swift
- Tests/MLS/MLSControllerTests.swift
- Tests/MLS/MockMLSController.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1055" title="FS-1055" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-1055</a>  [iOS] Message sending fails in an mls group when the user left the mls group 
</td></table>
<br />
----
----
If a user leaves a group, then sometimes the remaining participants can't send messages in the group.
There are multiple things going wrong here. First, we sometimes get in a state where we have a conversation marked as having pending proposals, but don't actually have any. This causes the client to repeatedly try to commit pending proposals, but it will always fail.
Secondly, if there is a pending …
> fix(mls): clear pending proposal date if no pending proposals found FS-1055

- MLS/MLSController.swift
- Tests/MLS/MLSControllerTests.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1093" title="FS-1093" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-1093</a>  [iOS] MLS groups are not showing on iOS client while creating it from another iOS client or web client 
</td></table>
<br />
----
----
If encryption at rest (EAR) is enabled, then the self client can't be added to mls groups.
When the app is launched and the user logs in, it will create and register an mls client. It will then generate and upload key packages. However, when EAR is enabled, this flow gets interrupted because the user needs to authenticate with biometrics and then enable EAR. As a result, no …
> fix(mls): can't be added to groups when EAR enabled FS-1093

- MLS/MLSClientID.swift
- MLS/MLSQualifiedClientID.swift
- Tests/MLS/MLSClientIdTests.swift
- Tests/MLS/MLSQualifiedClientIdTests.swift
- WireDataModel.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1162" title="FS-1162" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-1162</a>  [iOS] iOS devices cannot be removed from conversation
</td></table>
<br />
----
----
iOS devices cannot be removed from conversation
The MLS client identifier passed to core crypto (`userID:clientID@domain`) contains an uppercased userID. However core crypto expects the identifier to be lowercased. This causes mismatches in the identifiers.
make sure the MLS client identifier is lowercased
- Added tests for `MLSQualifiedClientID` and `MLSClientID`
----
----
----
1. …
> fix(mls): iOS devices cannot be removed from conversation FS-1162

- MLS/MLSClientID.swift
- MLS/MLSController.swift
- Source/Model/Conversation/ZMConversation+Participants.swift
- Source/Model/UserClient/FetchUserClientsAction.swift
- Tests/Source/Model/Conversation/ZMConversationTests+Participants.swift
- WireDataModel.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1176" title="FS-1176" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-1176</a>  [iOS] Group admin is not able to remove the participants from a mls group on col 1 and col 3
</td></table>
<br />
----
----
1. User A creates MLS group with user B 
2. User B logs in with new client3. 
3. User A removes user B from group
Result: User B cannot be removed from group
User B's new client was never fetched by user A, and thus not passed to core crypto 
Fetch a user's clients before asking core crypto to remove them
Added tests for `removeParticipants`
----
----
----
1. …
> fix(mls): can't remove users from mls group FS-1176
